import { expect, test } from '@playwright/test';

import { t } from '../helpers/i18n';
import { isMockLlmMode, readRunContext } from '../helpers/test-context';
import { CANNED_REPLY } from '../mock-llm/canned';

/**
 * Chat-thread depth flows against the seeded E2E agent:
 *
 *  1. Start a NEW thread (send a message), confirm the round-trip, capture the
 *     thread id from the URL, open the history sidebar, and re-open the thread
 *     from history — then delete the thread we just created (the only state
 *     this spec mutates, and it cleans up after itself).
 *  2. The seeded "Summarize Text" prompt (autoInstall) surfaces in the chat
 *     composer's Prompt Library dialog.
 *
 * Mirrors `chat.spec.ts`: the composer-fill retry (draft-key flip) is reused
 * verbatim, and any LLM-content assertion is gated behind `isMockLlmMode()`.
 */

// Unique per run so a created thread never collides on the shared backend and
// the user bubble is unambiguous. (The thread *title* is auto-generated by the
// backend and isn't deterministic, so selectors never rely on it.)
const THREAD_MESSAGE = `E2E thread probe ${Date.now().toString(36)}`;

// The seeded prompt's TITLE, from
// `fixtures/config/default/prompts/summarize-text.json`. Not translated UI
// copy — it's fixture content, so it stays a single literal (mirrors the
// `WORKFLOW_NAME` constant in `automation.spec.ts`).
const SEEDED_PROMPT_TITLE = 'Summarize Text';

const THREAD_URL = /\/chat\/([A-Za-z0-9]{16,})(?:[/?#]|$)/;

test('starts a thread, finds it in history, reopens it, then deletes it', async ({
  page,
}) => {
  const { organizationId } = readRunContext();

  await page.goto(`/dashboard/${organizationId}/chat`);

  const composer = page.getByRole('textbox', {
    name: t('chat.aria.chatInput'),
  });
  await expect(composer).toBeVisible({ timeout: 60_000 });
  await expect(composer).toBeEnabled();

  // Draft-key flip retry — see `chat.spec.ts` for the full rationale. The
  // controlled textarea re-seeds from storage once the user-id key settles, so
  // a single type-then-send can ship a truncated message; retry until it sticks.
  await composer.click();
  await expect(async () => {
    await composer.fill('');
    await composer.pressSequentially(THREAD_MESSAGE);
    await expect(composer).toHaveValue(THREAD_MESSAGE);
  }).toPass({ timeout: 30_000 });

  const sendButton = page.getByRole('button', {
    name: t('chat.send'),
    exact: true,
  });
  await expect(sendButton).toBeEnabled();
  await sendButton.click();

  // Optimistic user bubble appears immediately, and the send creates a thread
  // (the URL gains a thread id). Capture it for the re-open + delete steps.
  await expect(page.getByText(THREAD_MESSAGE).first()).toBeVisible({
    timeout: 30_000,
  });
  await page.waitForURL(THREAD_URL, { timeout: 60_000 });
  const threadId = THREAD_URL.exec(page.url())?.[1];
  expect(threadId).toBeTruthy();

  if (isMockLlmMode()) {
    await expect(page.getByText(CANNED_REPLY).first()).toBeVisible({
      timeout: 120_000,
    });
  } else {
    // Live LLM: assert only the turn completes (Stop reverts to Send).
    await expect(
      page.getByRole('button', { name: t('chat.send'), exact: true }),
    ).toBeVisible({ timeout: 120_000 });
  }

  // Open the history sidebar (desktop viewport — the toggle flips `isHistoryOpen`).
  // Its label flips Show⇄Hide, so target the "Show" state to open it.
  await page
    .getByRole('button', { name: t('chat.showHistory') })
    .first()
    .click();

  // The populated sidebar renders a "CHATS" section; the freshly created thread
  // is the newest un-projected (and unpinned) chat, so it's the first row in
  // that section. Scope the row lookup to the chat-history sidebar region.
  await expect(
    page.getByText(t('chat.chatsSection'), { exact: true }).first(),
  ).toBeVisible({ timeout: 60_000 });

  // Re-open the thread from history. Leave the thread (New chat → base /chat),
  // then navigate back by URL — a deterministic "open from history" that
  // doesn't depend on the auto-generated thread title for a row selector.
  await page
    .getByRole('button', { name: t('chat.newChat') })
    .first()
    .click();
  await page.waitForURL(/\/chat(?:[/?#]|$)/, { timeout: 60_000 });

  await page.goto(`/dashboard/${organizationId}/chat/${threadId}`);
  await page.waitForURL(THREAD_URL, { timeout: 60_000 });
  // The thread's prior user message is restored, proving the thread reopened.
  await expect(page.getByText(THREAD_MESSAGE).first()).toBeVisible({
    timeout: 60_000,
  });

  // Clean up the thread this test created (rule 4 permits deleting our own
  // freshly created state). Open history, open our row's actions menu, delete,
  // and confirm.
  await page
    .getByRole('button', { name: t('chat.showHistory') })
    .first()
    .click();

  // Scope to the list <section> that holds the "Chats" header — this excludes
  // the chat-header's own "More actions" (Export) menu, which shares the label.
  // The seeded org has no projects, so the only row-actions menu inside this
  // section belongs to a chat row; our freshly created thread is the newest
  // un-projected (unpinned) chat, so it's the first such row.
  const listSection = page
    .locator('section')
    .filter({
      has: page.getByText(t('chat.chatsSection'), { exact: true }),
    })
    .first();
  const rowActions = listSection
    .getByRole('button', { name: t('chat.moreActions') })
    .first();
  await rowActions.scrollIntoViewIfNeeded();
  await rowActions.click();

  await page
    .getByRole('menuitem', { name: t('common.actions.delete'), exact: true })
    .click();

  // DeleteDialog confirm button is labelled "Delete chat".
  await page
    .getByRole('button', { name: t('chat.deleteChat'), exact: true })
    .click();

  // Deleting the open thread routes back to the base chat surface.
  await page.waitForURL(/\/chat(?:[/?#]|$)/, { timeout: 60_000 });
});

test('the seeded "Summarize Text" prompt is listed in the prompt library', async ({
  page,
}) => {
  const { organizationId } = readRunContext();

  await page.goto(`/dashboard/${organizationId}/chat`);

  // Ensure the composer (and thus its toolbar) has mounted before reaching for
  // the Save-options menu that opens the library.
  await expect(
    page.getByRole('textbox', { name: t('chat.aria.chatInput') }),
  ).toBeVisible({ timeout: 60_000 });

  // The composer's Save-options menu (bookmark) carries the "Prompt library"
  // item that opens the dialog.
  await page
    .getByRole('button', { name: t('chat.savePromptMenu') })
    .first()
    .click();
  await page
    .getByRole('menuitem', { name: t('chat.promptLibrary'), exact: true })
    .click();

  // The library dialog opens (title from the `prompts` namespace).
  await expect(
    page.getByRole('dialog').filter({
      has: page.getByText(t('prompts.library.title'), { exact: true }),
    }),
  ).toBeVisible({ timeout: 60_000 });

  // The seeded autoInstall prompt is listed by its title.
  await expect(
    page.getByText(SEEDED_PROMPT_TITLE, { exact: true }).first(),
  ).toBeVisible({ timeout: 60_000 });
});
