import { parseFrontmatter } from '@tale/ui/parse-frontmatter';

import frontmatterManifest from '@/app/content/frontmatter.json';

export interface DocFrontmatter {
  title: string;
  description: string;
  noindex: boolean;
}

export interface DocPage {
  /** URL path relative to `/docs`, e.g. `components/button`. */
  slug: string;
  frontmatter: DocFrontmatter;
  body: string;
}

interface ManifestEntry {
  slug: string;
  frontmatter: Record<string, string | boolean>;
}

function normaliseFrontmatter(
  raw: Record<string, string | boolean>,
): DocFrontmatter {
  return {
    title: typeof raw.title === 'string' ? raw.title : '',
    description: typeof raw.description === 'string' ? raw.description : '',
    noindex: raw.noindex === true,
  };
}

// Frontmatter for every page, generated by `scripts/build-content.ts` and
// imported synchronously. The rail, the breadcrumbs and prev/next only ever
// read frontmatter, so they resolve with no body access at all. Bodies live
// behind `ensureDocBody`.
// oxlint-disable-next-line typescript/no-unsafe-type-assertion -- generated manifest, fixed shape
const manifest = frontmatterManifest as Record<string, ManifestEntry>;
const documents = new Map<string, DocPage>();
for (const entry of Object.values(manifest)) {
  documents.set(entry.slug, {
    slug: entry.slug,
    frontmatter: normaliseFrontmatter(entry.frontmatter),
    body: '',
  });
}

/** Parse a glob path like `…/content/components/button.md` into a slug. */
function slugFromPath(path: string): string | null {
  const match = /\/content\/(.+)\.md$/.exec(path);
  return match ? match[1] : null;
}

// Per-page body loaders keyed by slug. A LAZY glob: each markdown file is its
// own chunk, fetched only when the route loader calls `ensureDocBody`. This
// MUST stay lazy — an eager glob compiles to hoisted static imports that pull
// the whole content tree on module load, in dev as well as in the bundle.
const bodyLoaders = new Map<string, () => Promise<string>>();
{
  const lazy = import.meta.glob('../../content/**/*.md', {
    query: '?raw',
    import: 'default',
  }) as unknown as Record<string, () => Promise<string>>;
  for (const [path, load] of Object.entries(lazy)) {
    const slug = slugFromPath(path);
    if (slug) bodyLoaders.set(slug, load);
  }
}

const bodyCache = new Map<string, string>();

/**
 * Load a page's body into the cache. Call it from the route loader so the
 * body is ready before the component renders — SSR awaits it during
 * prerender, the client awaits one dynamic import on navigation. Idempotent,
 * and a no-op for a slug that has no page.
 */
export async function ensureDocBody(slug: string): Promise<void> {
  if (!documents.has(slug) || bodyCache.has(slug)) return;
  const load = bodyLoaders.get(slug);
  if (!load) return;
  const raw = await load();
  bodyCache.set(slug, parseFrontmatter(raw).content);
}

/**
 * Resolve a page by slug. Frontmatter is always present; `body` is filled
 * only once {@link ensureDocBody} has run for that slug (the route loader
 * does this) and is an empty string otherwise.
 */
export function getDocPage(slug: string): DocPage | null {
  const doc = documents.get(slug);
  if (!doc) return null;
  const body = bodyCache.get(slug);
  return body === undefined ? doc : { ...doc, body };
}

/** Every slug the manifest knows, in manifest (alphabetical) order. */
export function allDocSlugs(): string[] {
  return [...documents.keys()];
}
