/**
 * Golden corpus for validation error text.
 *
 * Error text is public API: agents parse it behaviorally, so the FULL
 * rendered issue list (code, nodeId, path, message, hint, and the structured
 * at / params / related twins) for a battery of small invalid documents is
 * pinned in golden-errors.yml. A diff here means a message or a location
 * changed — review it like any API change.
 *
 * After an intentional change, regenerate the fixture with:
 *
 *   GOLDEN_UPDATE=1 bunx vitest --run --project server \
 *     lib/engine/core/validate/golden-errors
 *
 * and commit the reviewed golden-errors.yml alongside the change.
 */

import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

import { beforeAll, expect, it } from 'vitest';
import { parse, stringify } from 'yaml';

import { nodeVmRunner } from '../../runners/node-vm';
import { memoryStore } from '../../selftest/memory-store';
import { CODE_META, CODES, type IssueCode } from '../errors';
import { registerNodeType, setCodeRunner } from '../slots';
import { parentPointer, resolvePointer } from '../syntax/pointer';
import type { Automation, Issue } from '../types';
import { validate } from './index';

const GOLDEN_PATH = fileURLToPath(
  new URL('golden-errors.yml', import.meta.url),
);

const HEADER = `# Golden corpus of rendered validation issues — generated by
# golden-errors.test.ts, one entry per fixture document.
#
# Error text is public API. Never edit this file by hand: change the
# validator, review the diff, and regenerate with
#   GOLDEN_UPDATE=1 bunx vitest --run --project server lib/engine/core/validate/golden-errors
`;

/** The caller's store the corpus resolves subautomation references against —
 * and asks about models (one id is served by nobody) and about what the
 * organization has: two skills, a connected GitHub, an unconnected Gmail,
 * one secret, two agent runtimes. The test connectors below (weather, mail,
 * web) are not in its catalog, so no other fixture reads a connection (a
 * capability step's connection is held by `org-state.test.ts`). */
const store = memoryStore({
  unavailableModels: ['nonexistent/model-xyz'],
  orgFacts: {
    skills: new Set(['reply-style', 'summarize-thread']),
    connectors: {
      catalogued: new Set(['github', 'gmail', 'task']),
      connected: new Set(['github']),
      needsCredential: new Set(['github', 'gmail']),
    },
    secrets: new Set(['SUPPORT_SIGNATURE']),
    harnesses: new Set(['claude-code', 'codex']),
    raisedEvents: ['task.created', 'task.status_changed', 'comment.created'],
  },
});

beforeAll(async () => {
  setCodeRunner(nodeVmRunner());
  // The schedule trigger-input-mismatch is checked against.
  await store.setTrigger('scheduled-report', {
    kind: 'schedule',
    cron: '0 6 * * *',
  });
  // The webhook whose fixed input trigger-input-not-templated reads.
  await store.setTrigger('templated-hook', {
    kind: 'webhook',
    input: { owner: '{{ payload.repository.owner }}', repo: 'tale' },
  });
  // A trigger bound before the platform refused names it does not raise.
  await store.setTrigger('stale-event-trigger', {
    kind: 'event',
    event: 'task.create',
  });

  const noop: Automation = {
    version: 1,
    name: 'send-digest',
    nodes: [{ id: 'noop', type: 'transform', code: 'return input;' }],
  };
  store.save('send-digest', noop);
  store.save('send-digest', noop);
  // Called with an input it refuses by subautomation-input-invalid.
  store.save('weekly-report', {
    ...noop,
    name: 'weekly-report',
    inputs: {
      type: 'object',
      properties: { n: { type: 'number' } },
      required: ['n'],
      additionalProperties: false,
    },
  });
  store.save('draft-reply', {
    version: 1,
    name: 'draft-reply',
    nodes: [
      { id: 'draft', type: 'agent', model: 'test-model', prompt: 'Draft it.' },
    ],
  });
  store.save('send-mail', {
    version: 1,
    name: 'send-mail',
    nodes: [{ id: 'send', type: 'mail.send', input: { to: 'a@b.test' } }],
  });
  registerNodeType({
    type: 'weather.current',
    kind: 'connector',
    outputKind: 'structured',
    description: 'test connector: current weather',
    allowedFields: ['input'],
    requiredFields: ['input'],
    connector: {
      name: 'weather.current',
      description: 'current weather for a city',
      inputSchema: {
        type: 'object',
        properties: {
          city: { type: 'string' },
          units: { type: 'string', enum: ['metric', 'imperial'] },
          days: { type: 'integer' },
        },
        required: ['city'],
        additionalProperties: false,
      },
      outputSignature: '{ tempC: number }',
      hasEffect: false,
      mock: () => ({ tempC: 21 }),
    },
  });
  // The HTTP connector's read, as its connector declares it in short.
  registerNodeType({
    type: 'http.get',
    kind: 'connector',
    outputKind: 'structured',
    description: 'test connector: an HTTP GET',
    allowedFields: ['input', 'credential'],
    requiredFields: ['input'],
    connector: {
      name: 'http.get',
      description: 'read from an HTTPS API',
      inputSchema: {
        type: 'object',
        properties: {
          url: { type: 'string' },
          query: { type: 'object' },
          headers: { type: 'object', additionalProperties: { type: 'string' } },
        },
        required: ['url'],
        additionalProperties: false,
      },
      outputSignature: '{ status: number, body: unknown }',
      hasEffect: false,
      mock: () => ({ status: 200, body: null }),
    },
  });
  registerNodeType({
    type: 'mail.send',
    kind: 'connector',
    outputKind: 'structured',
    description: 'test connector: send a mail (a write)',
    allowedFields: ['input'],
    requiredFields: ['input'],
    connector: {
      name: 'mail.send',
      description: 'send a mail',
      inputSchema: {
        type: 'object',
        properties: { to: { type: 'string' } },
        required: ['to'],
        additionalProperties: false,
      },
      outputSignature: '{ id: string }',
      hasEffect: true,
      mock: () => ({ id: 'm-1' }),
    },
  });
  registerNodeType({
    type: 'web.fetch_text',
    kind: 'connector',
    outputKind: 'unstructured',
    description: 'test connector: fetch a page as text',
    allowedFields: ['input'],
    requiredFields: ['input'],
    connector: {
      name: 'web.fetch_text',
      description: 'fetch a page as plain text',
      inputSchema: {
        type: 'object',
        properties: { url: { type: 'string' } },
        required: ['url'],
        additionalProperties: false,
      },
      outputSignature: '{ text: string }',
      hasEffect: false,
      mock: () => ({ text: 'page text' }),
    },
  });
});

// ---------------------------------------------------------------- fixtures

/** A minimal valid document; each fixture breaks exactly one aspect. */
function flow(over: Record<string, unknown> = {}): Record<string, unknown> {
  return {
    version: 1,
    name: 'fixture-flow',
    nodes: [{ id: 'main', type: 'transform', code: 'return 1;' }],
    output: '{{ nodes.main.output }}',
    ...over,
  };
}

function chainOf(count: number): Record<string, unknown> {
  const nodes = Array.from({ length: count }, (_, i) => ({
    id: `t${i}`,
    type: 'transform',
    code: i === 0 ? 'return 1;' : `return nodes.t${i - 1}.output;`,
  }));
  return flow({ nodes, output: `{{ nodes.t${count - 1}.output }}` });
}

const fixtures: Record<string, unknown> = {
  'not-an-object': 42,
  'unknown-top-field': flow({ edges: [] }),
  'version-unsupported': flow({ version: 2 }),
  'version-missing': {
    name: 'fixture-flow',
    nodes: [{ id: 'main', type: 'transform', code: 'return 1;' }],
    output: '{{ nodes.main.output }}',
  },
  'name-invalid': flow({ name: 'My Flow' }),
  'inputs-not-an-object': flow({ inputs: 'city' }),
  'inputs-schema-malformed': flow({
    inputs: { type: 'object', properties: ['city'], required: 'city' },
  }),
  'nodes-missing': { version: 1, name: 'fixture-flow', nodes: [] },
  'nodes-too-many': chainOf(41),
  'secret-api-key': flow({
    nodes: [
      {
        id: 'gen',
        type: 'llm',
        model: 'test-model',
        prompt: 'Authorization: sk-00000000000000000000',
      },
    ],
    output: '{{ nodes.gen.output.text }}',
  }),
  'secret-injected-values': flow({
    nodes: [
      {
        id: 'main',
        type: 'transform',
        input: {
          authorization: 'Bearer 00000000000000000000',
          api_key: 'k0000000000000000000',
        },
        code: 'return input;',
      },
    ],
  }),
  'tests-invalid': flow({
    tests: [
      { name: 'missing-input' },
      { name: 'bad-expect', input: {}, expect: { outputs: 1 } },
    ],
  }),
  'node-not-an-object': flow({ nodes: ['main'], output: 'static result' }),
  'node-id-invalid': flow({
    nodes: [{ id: 'Main', type: 'transform', code: 'return 1;' }],
    output: 'static result',
  }),
  'node-id-duplicate': flow({
    nodes: [
      { id: 'main', type: 'transform', code: 'return 1;' },
      { id: 'main', type: 'transform', code: 'return 2;' },
    ],
  }),
  'unknown-node-type': flow({
    nodes: [{ id: 'main', type: 'transfrom', code: 'return 1;' }],
  }),
  'unknown-node-type-keyword': flow({
    nodes: [
      { id: 'fetch', type: 'connector', input: { city: 'Berlin' } },
      { id: 'main', type: 'transform', code: 'return 1;' },
    ],
  }),
  'node-unknown-field': flow({
    nodes: [{ id: 'main', type: 'transform', code: 'return 1;', prompt: 'hi' }],
  }),
  'llm-missing-model': flow({
    nodes: [{ id: 'gen', type: 'llm', prompt: 'Say hi' }],
    output: '{{ nodes.gen.output.text }}',
  }),
  'llm-model-unavailable': flow({
    nodes: [
      {
        id: 'gen',
        type: 'llm',
        model: 'nonexistent/model-xyz',
        prompt: 'Say hi',
      },
    ],
    output: '{{ nodes.gen.output.text }}',
  }),
  'transform-missing-code': flow({
    nodes: [{ id: 'main', type: 'transform' }],
  }),
  'node-field-types': flow({
    nodes: [
      {
        id: 'main',
        type: 'transform',
        code: 'return 1;',
        when: 5,
        input: ['x'],
        maxRepeats: 3,
      },
    ],
  }),
  'code-syntax': flow({
    nodes: [{ id: 'main', type: 'transform', code: 'return (;' }],
  }),
  'code-no-io': flow({
    nodes: [
      {
        id: 'main',
        type: 'transform',
        code: 'return fetch("https://example.com").json();',
      },
    ],
  }),
  'code-no-return': flow({
    nodes: [{ id: 'main', type: 'transform', code: 'const total = 1;' }],
  }),
  'output-schema-not-an-object': flow({
    nodes: [
      {
        id: 'gen',
        type: 'llm',
        model: 'test-model',
        prompt: 'Say hi',
        outputSchema: 'json',
      },
    ],
    output: '{{ nodes.gen.output.text }}',
  }),
  'output-schema-malformed': flow({
    nodes: [
      {
        id: 'gen',
        type: 'llm',
        model: 'test-model',
        prompt: 'Say hi',
        outputSchema: { type: 'object', properties: ['headline'] },
      },
    ],
    output: '{{ nodes.gen.output.text }}',
  }),
  'elseof-target-invalid': flow({
    nodes: [
      { id: 'plan', type: 'transform', code: 'return 1;' },
      { id: 'main', type: 'transform', code: 'return 2;', elseOf: 'plan' },
    ],
  }),
  'repeat-max-invalid': flow({
    nodes: [
      {
        id: 'main',
        type: 'transform',
        code: 'return 1;',
        repeatUntil: '{{ output }}',
        maxRepeats: 99,
      },
    ],
  }),
  'onerror-invalid': flow({
    nodes: [
      { id: 'main', type: 'transform', code: 'return 1;', onError: 'retry' },
    ],
  }),
  'subautomation-ref-invalid': flow({
    nodes: [
      { id: 'sub', type: 'subautomation', automation: 'Daily Digest@next' },
    ],
    output: '{{ nodes.sub.output }}',
  }),
  'subautomation-not-found': flow({
    nodes: [{ id: 'sub', type: 'subautomation', automation: 'daily-digest' }],
    output: '{{ nodes.sub.output }}',
  }),
  'subautomation-version-not-found': flow({
    nodes: [{ id: 'sub', type: 'subautomation', automation: 'send-digest@9' }],
    output: '{{ nodes.sub.output }}',
  }),
  'subautomation-has-agent-node': flow({
    nodes: [{ id: 'sub', type: 'subautomation', automation: 'draft-reply' }],
    output: '{{ nodes.sub.output }}',
  }),
  'subautomation-has-write': flow({
    nodes: [{ id: 'sub', type: 'subautomation', automation: 'send-mail@1' }],
    output: '{{ nodes.sub.output }}',
  }),
  'expr-syntax-prompt': flow({
    nodes: [
      {
        id: 'gen',
        type: 'llm',
        model: 'test-model',
        prompt: 'Hello {{ input. }}',
      },
    ],
    output: '{{ nodes.gen.output.text }}',
  }),
  'expr-syntax-regex-modifier': flow({
    nodes: [
      {
        id: 'main',
        type: 'transform',
        code: 'return 1;',
        when: '{{ /(?i:yes)/.test(input.answer) }}',
      },
    ],
  }),
  'expr-syntax-when': flow({
    nodes: [
      { id: 'main', type: 'transform', code: 'return 1;', when: '{{ (( }}' },
    ],
  }),
  'ref-unknown-node': flow({
    nodes: [
      { id: 'fetch', type: 'transform', code: 'return 1;' },
      {
        id: 'main',
        type: 'transform',
        code: 'return nodes.fetch.output + nodes.fetc.output;',
      },
    ],
  }),
  'ref-self': flow({
    nodes: [
      { id: 'main', type: 'transform', code: 'return nodes.main.output;' },
    ],
  }),
  'ref-not-output': flow({
    nodes: [
      { id: 'fetch', type: 'transform', code: 'return 1;' },
      { id: 'main', type: 'transform', code: 'return nodes.fetch.result;' },
    ],
  }),
  'ref-bare': flow({
    nodes: [
      { id: 'fetch', type: 'transform', code: 'return 1;' },
      {
        id: 'gen',
        type: 'llm',
        model: 'test-model',
        prompt: 'Data: {{ nodes.fetch }}',
      },
    ],
    output: '{{ nodes.gen.output.text }}',
  }),
  'ref-cycle': flow({
    nodes: [
      { id: 'a', type: 'transform', code: 'return nodes.b.output;' },
      { id: 'b', type: 'transform', code: 'return nodes.a.output;' },
    ],
    output: '{{ nodes.b.output }}',
  }),
  'ref-unstructured-path': flow({
    nodes: [
      { id: 'gen', type: 'llm', model: 'test-model', prompt: 'Summarize' },
      {
        id: 'main',
        type: 'transform',
        code: 'return nodes.gen.output.summary;',
      },
    ],
  }),
  'ref-unstructured-path-connector': flow({
    nodes: [
      {
        id: 'page',
        type: 'web.fetch_text',
        input: { url: 'https://example.com' },
      },
      {
        id: 'main',
        type: 'transform',
        code: 'return nodes.page.output.title;',
      },
    ],
  }),
  'item-without-foreach': flow({
    nodes: [
      {
        id: 'gen',
        type: 'llm',
        model: 'test-model',
        prompt: 'Item {{ item.name }}',
      },
    ],
    output: '{{ nodes.gen.output.text }}',
  }),
  'template-unterminated': flow({
    nodes: [
      {
        id: 'gen',
        type: 'llm',
        model: 'test-model',
        prompt: 'Hello {{ input.name',
      },
    ],
    output: { greeting: '{{ nodes.gen.output.text }}', note: 'braces {{' },
  }),
  'input-key-unknown': flow({
    inputs: { type: 'object', properties: { city: { type: 'string' } } },
    nodes: [
      {
        id: 'gen',
        type: 'llm',
        model: 'test-model',
        prompt: 'Weather for {{ input.citi }}',
      },
    ],
    output: '{{ nodes.gen.output.text }}',
  }),
  'connector-input-invalid': flow({
    nodes: [
      {
        id: 'w',
        type: 'weather.current',
        input: { units: 'kelvin', extra: true },
      },
    ],
    output: '{{ nodes.w.output }}',
  }),
  'http-input-checks': flow({
    nodes: [
      {
        id: 'orders',
        type: 'http.get',
        input: {
          url: 'http://api.example.com/orders?api_key=abcdef0123456789abcd',
          headers: { Authorization: 'Basic x', Accept: 'application/json' },
        },
      },
    ],
    output: '{{ nodes.orders.output }}',
  }),
  'http-credentialed-step': flow({
    nodes: [
      {
        id: 'orders',
        type: 'http.get',
        credential: 'Shop API',
        input: { url: '/orders', query: { status: 'open' } },
      },
    ],
    output: '{{ nodes.orders.output }}',
  }),
  'output-missing': {
    version: 1,
    name: 'fixture-flow',
    nodes: [{ id: 'main', type: 'transform', code: 'return 1;' }],
  },
  'unused-node': flow({
    nodes: [
      { id: 'stale', type: 'transform', code: 'return 1;' },
      { id: 'main', type: 'transform', code: 'return 2;' },
    ],
  }),

  // The analysis pass: types, iteration, names and the ways a run can go.
  'expr-unknown-name': flow({
    nodes: [
      {
        id: 'gen',
        type: 'llm',
        model: 'test-model',
        prompt: 'Hello {{ inptu.name }}',
      },
    ],
    output: '{{ nodes.gen.output.text }}',
  }),
  'item-out-of-scope': flow({
    nodes: [
      {
        id: 'each',
        type: 'transform',
        forEach: '{{ item.rows }}',
        code: 'return item;',
      },
    ],
    output: '{{ nodes.each.output }}',
  }),
  'item-without-foreach-code': flow({
    nodes: [{ id: 'main', type: 'transform', code: 'return item ?? 1;' }],
  }),
  'ref-unknown-field': flow({
    nodes: [
      {
        id: 'calc',
        type: 'transform',
        code: 'return { count: 1, items: [] };',
      },
      {
        id: 'main',
        type: 'transform',
        input: { n: '{{ nodes.calc.output.cuont }}' },
        code: 'return input.n;',
      },
    ],
  }),
  'type-mismatch-connector': flow({
    nodes: [
      { id: 'calc', type: 'transform', code: 'return { count: 1 };' },
      {
        id: 'w',
        type: 'weather.current',
        input: { city: '{{ nodes.calc.output.count }}' },
      },
    ],
    output: '{{ nodes.w.output }}',
  }),
  'type-mismatch-foreach': flow({
    nodes: [
      { id: 'calc', type: 'transform', code: 'return { items: [1, 2] };' },
      {
        id: 'each',
        type: 'transform',
        forEach: '{{ nodes.calc.output }}',
        code: 'return item;',
      },
    ],
    output: '{{ nodes.each.output }}',
  }),
  'template-null-interpolation': flow({
    nodes: [
      {
        id: 'gen',
        type: 'llm',
        model: 'test-model',
        prompt: 'Name the article.',
        outputSchema: {
          type: 'object',
          properties: { title: { type: 'string' } },
        },
      },
      {
        id: 'post',
        type: 'llm',
        model: 'test-model',
        prompt: 'Write about {{ nodes.gen.output.title }}.',
      },
    ],
    output: '{{ nodes.post.output.text }}',
  }),
  'foreach-not-array': flow({
    nodes: [
      { id: 'calc', type: 'transform', code: 'return { items: [1, 2] };' },
      {
        id: 'each',
        type: 'transform',
        forEach: 'nodes.calc.output.items',
        code: 'return item;',
      },
    ],
    output: '{{ nodes.each.output }}',
  }),
  'agent-iteration-unsupported': flow({
    nodes: [
      {
        id: 'review',
        type: 'agent',
        model: 'test-model',
        forEach: '{{ [1, 2] }}',
        prompt: 'Review item {{ item }}.',
      },
    ],
    output: '{{ nodes.review.output }}',
  }),
  'condition-constant': flow({
    nodes: [
      {
        id: 'main',
        type: 'transform',
        when: 'yes {{ input.go }}',
        code: 'return 1;',
      },
    ],
  }),
  'repeat-never-true': flow({
    nodes: [
      {
        id: 'main',
        type: 'transform',
        code: 'return 1;',
        repeatUntil: '{{ false }}',
        maxRepeats: 3,
      },
    ],
  }),
  'repeat-until-static': flow({
    nodes: [
      {
        id: 'main',
        type: 'transform',
        code: 'return 1;',
        repeatUntil: '{{ input.done }}',
      },
    ],
  }),
  'maybe-null': flow({
    nodes: [
      { id: 'base', type: 'transform', code: 'return 1;' },
      {
        id: 'check',
        type: 'transform',
        when: '{{ input.go }}',
        code: 'return { ok: true };',
      },
    ],
    output: {
      base: '{{ nodes.base.output }}',
      ok: '{{ nodes.check.output.ok }}',
    },
  }),
  'maybe-null-optional-in-text': flow({
    nodes: [
      { id: 'base', type: 'transform', code: 'return 1;' },
      {
        id: 'check',
        type: 'transform',
        when: '{{ input.go }}',
        code: 'return { summary: "s" };',
      },
      {
        id: 'notify',
        type: 'transform',
        when: 'ready {{ nodes.check.output?.summary }}',
        code: 'return 1;',
      },
    ],
    output: {
      base: '{{ nodes.base.output }}',
      line: 'Summary: {{ nodes.check.output?.summary }}',
      pick: '{{ nodes.check.output[input.key] }}',
    },
  }),
  'uncaught-failure': flow({
    nodes: [
      { id: 'base', type: 'transform', code: 'return 1;' },
      {
        id: 'fetch',
        type: 'transform',
        onError: 'continue',
        code: 'return { rows: [] };',
      },
    ],
    output: {
      base: '{{ nodes.base.output }}',
      rows: '{{ nodes.fetch.output.rows }}',
    },
  }),
  unreachable: flow({
    nodes: [
      {
        id: 'never',
        type: 'transform',
        when: '{{ false }}',
        code: 'return 1;',
      },
      { id: 'main', type: 'transform', code: 'return 2;' },
    ],
    output: {
      main: '{{ nodes.main.output }}',
      never: '{{ nodes.never.output ?? null }}',
    },
  }),
  'unused-node-readers-unreachable': flow({
    nodes: [
      { id: 'prep', type: 'transform', code: 'return 1;' },
      {
        id: 'never',
        type: 'transform',
        when: '{{ false }}',
        input: { v: '{{ nodes.prep.output }}' },
        code: 'return input.v;',
      },
      { id: 'main', type: 'transform', code: 'return 2;' },
    ],
  }),
  'output-maybe-empty': flow({
    nodes: [
      {
        id: 'main',
        type: 'transform',
        when: '{{ input.go }}',
        code: 'return 1;',
      },
    ],
  }),
  'subautomation-input-invalid': flow({
    nodes: [
      {
        id: 'sub',
        type: 'subautomation',
        automation: 'weekly-report',
        input: { m: 2 },
      },
    ],
    output: '{{ nodes.sub.output }}',
  }),
  'trigger-input-mismatch': flow({
    name: 'scheduled-report',
    inputs: {
      type: 'object',
      properties: { city: { type: 'string' } },
      required: ['city'],
      additionalProperties: false,
    },
  }),
  'trigger-input-not-templated': flow({
    name: 'templated-hook',
    inputs: {
      type: 'object',
      properties: { owner: { type: 'string' }, repo: { type: 'string' } },
    },
  }),
  'tests-input-invalid': flow({
    inputs: {
      type: 'object',
      properties: { city: { type: 'string' } },
      required: ['city'],
    },
    tests: [{ name: 'no city', input: {} }],
  }),
  'tests-effect-unknown': flow({
    nodes: [{ id: 'send', type: 'mail.send', input: { to: 'a@b.test' } }],
    output: '{{ nodes.send.output }}',
    tests: [
      {
        name: 'sends the mail',
        input: {},
        expect: { effects: [{ connector: 'mail.sned' }] },
      },
    ],
  }),
  'tests-expect-type': flow({
    nodes: [{ id: 'calc', type: 'transform', code: 'return { count: 1 };' }],
    output: { count: '{{ nodes.calc.output.count }}' },
    tests: [
      { name: 'counts', input: {}, expect: { output: { count: 'one' } } },
    ],
  }),
  // Each malformed part of a test, once: its description, its stand-ins,
  // an expected effect, the node states and the expected failure.
  'tests-invalid-parts': flow({
    nodes: [
      { id: 'main', type: 'transform', code: 'return 1;' },
      { id: 'ask', type: 'llm', model: 'test-model', prompt: 'Hi' },
    ],
    tests: [
      {
        name: 'stand-ins',
        input: {},
        description: 5,
        mocks: 'main',
        failures: { main: 404 },
      },
      {
        name: 'expectations',
        input: {},
        expect: {
          effects: [
            { input: {} },
            { connector: 'llm', input: {}, inputIncludes: {} },
            { connector: 'llm', absent: false },
          ],
          nodes: { main: 'done' },
        },
      },
      {
        name: 'fails with an output',
        input: {},
        expect: { failure: { node: 'main', code: 1 }, output: 1 },
      },
    ],
  }),
  'tests-too-many': flow({
    tests: Array.from({ length: 51 }, (_, i) => ({
      name: `case ${i + 1}`,
      input: {},
    })),
  }),
  'tests-unknown-field': flow({
    tests: [{ name: 'stands in', input: {}, mock: { main: 2 } }],
  }),
  // A misspelled field of an expected effect is ignored when the test is
  // judged, so the test checks less than it says, or the opposite.
  'tests-unknown-field-effect': flow({
    nodes: [{ id: 'send', type: 'mail.send', input: { to: 'a@b.test' } }],
    output: '{{ nodes.send.output }}',
    tests: [
      {
        name: 'never sends',
        input: {},
        expect: { effects: [{ connector: 'mail.send', absnt: true }] },
      },
    ],
  }),
  'tests-name-duplicate': flow({
    tests: [
      { name: 'same', input: {} },
      { name: 'same', input: {} },
    ],
  }),
  'tests-mock-unknown-node': flow({
    tests: [{ name: 'stands in', input: {}, mocks: { mainn: 2 } }],
  }),
  'tests-mock-conflict': flow({
    tests: [
      {
        name: 'both',
        input: {},
        mocks: { main: 2 },
        failures: { main: 'the service is down' },
      },
    ],
  }),
  'tests-mock-not-list': flow({
    inputs: {
      type: 'object',
      properties: { items: { type: 'array' } },
    },
    nodes: [
      {
        id: 'each',
        type: 'transform',
        forEach: '{{ input.items }}',
        code: 'return { seen: true };',
      },
    ],
    output: '{{ nodes.each.output }}',
    tests: [
      { name: 'one item', input: { items: [1] }, mocks: { each: { id: 1 } } },
    ],
  }),
  'tests-mock-type': flow({
    nodes: [{ id: 'calc', type: 'transform', code: 'return { count: 1 };' }],
    output: '{{ nodes.calc.output.count }}',
    tests: [{ name: 'counts', input: {}, mocks: { calc: { count: 'one' } } }],
  }),
  'tests-expect-node-unknown': flow({
    tests: [{ name: 'names', input: {}, expect: { nodes: { mian: 'ran' } } }],
  }),
  'tests-expect-path-impossible': flow({
    inputs: {
      type: 'object',
      properties: { n: { type: 'number' } },
    },
    nodes: [
      {
        id: 'big',
        type: 'transform',
        when: '{{ input.n > 10 }}',
        code: 'return "big";',
      },
      {
        id: 'small',
        type: 'transform',
        elseOf: 'big',
        code: 'return "small";',
      },
    ],
    output: '{{ nodes.big.output ?? nodes.small.output }}',
    tests: [
      {
        name: 'both sizes',
        input: { n: 1 },
        expect: { nodes: { big: 'ran', small: 'ran' } },
      },
    ],
  }),
  // The automation runs the node, but never while the failure the test
  // simulates for the node it reads holds.
  'tests-expect-path-impossible-simulated': flow({
    nodes: [
      {
        id: 'ping',
        type: 'mail.send',
        input: { to: 'a@b.test' },
        onError: 'continue',
      },
      {
        id: 'after',
        type: 'transform',
        input: { id: '{{ nodes.ping.output.id }}' },
        code: 'return input.id;',
      },
    ],
    output: '{{ nodes.after.output ?? "no mail" }}',
    tests: [
      {
        name: 'reads the mail',
        input: {},
        failures: { ping: 'down' },
        expect: { nodes: { after: 'ran' } },
      },
    ],
  }),
  'tests-expect-failure-impossible': flow({
    nodes: [
      { id: 'main', type: 'transform', code: 'return 1;', onError: 'continue' },
    ],
    output: '{{ nodes.main.output ?? 0 }}',
    tests: [
      { name: 'fails', input: {}, expect: { failure: { node: 'main' } } },
    ],
  }),
  // What the organization has: a runtime this deployment cannot run, a
  // misspelled skill, a connector name it has none by, a catalogued one
  // nobody connected, and a misspelled secret — beside the ones it has.
  'org-state-agent-equipment': flow({
    nodes: [
      {
        id: 'reply',
        type: 'agent',
        model: 'test-model',
        prompt: 'Draft the reply.',
        harness: 'cursor',
        skills: ['reply-style', 'reply-stlye'],
        connectors: ['github', 'gmial', 'gmail'],
        secrets: ['SUPPORT_SIGNATURE', 'SUPPORT_SIGNATUR'],
      },
    ],
    output: '{{ nodes.reply.output.text }}',
  }),
  'org-state-event-unknown': flow({ name: 'stale-event-trigger' }),
};

/** Every code the validator can emit; the corpus must cover each at least
 * once, and only codes from the catalog may appear. */
const VALIDATION_CODES: IssueCode[] = [
  'AUTOMATION_NOT_OBJECT',
  'UNKNOWN_TOP_FIELD',
  'VERSION_UNSUPPORTED',
  'VERSION_MISSING',
  'NAME_INVALID',
  'INPUTS_SCHEMA_INVALID',
  'NODES_MISSING',
  'NODES_TOO_MANY',
  'SECRET_IN_DOCUMENT',
  'TESTS_INVALID',
  'NODE_NOT_OBJECT',
  'NODE_ID_INVALID',
  'NODE_ID_DUPLICATE',
  'UNKNOWN_NODE_TYPE',
  'NODE_UNKNOWN_FIELD',
  'NODE_MISSING_FIELD',
  'NODE_FIELD_TYPE',
  'CODE_SYNTAX',
  'CODE_NO_IO',
  'CODE_NO_RETURN',
  'OUTPUT_SCHEMA_INVALID',
  'ELSEOF_TARGET_INVALID',
  'REPEAT_MAX_INVALID',
  'ONERROR_INVALID',
  'SUBAUTOMATION_REF_INVALID',
  'SUBAUTOMATION_NOT_FOUND',
  'SUBAUTOMATION_HAS_AGENT_NODE',
  'SUBAUTOMATION_HAS_WRITE',
  'EXPR_SYNTAX',
  'REF_UNKNOWN_NODE',
  'REF_SELF',
  'REF_NOT_OUTPUT',
  'REF_BARE',
  'REF_CYCLE',
  'REF_UNSTRUCTURED_PATH',
  'ITEM_WITHOUT_FOREACH',
  'INPUT_KEY_UNKNOWN',
  'TEMPLATE_UNTERMINATED',
  'CONNECTOR_INPUT_INVALID',
  'HTTP_URL_NOT_HTTPS',
  'HTTP_SECRET_IN_URL',
  'HTTP_HEADER_RESERVED',
  'LLM_MODEL_UNAVAILABLE',
  'SKILL_UNKNOWN',
  'CONNECTOR_NOT_CONNECTED',
  'SECRET_UNKNOWN',
  'HARNESS_UNKNOWN',
  'EVENT_UNKNOWN',
  'OUTPUT_MISSING',
  'UNUSED_NODE',
  'EXPR_UNKNOWN_NAME',
  'ITEM_OUT_OF_SCOPE',
  'REF_UNKNOWN_FIELD',
  'TYPE_MISMATCH',
  'TEMPLATE_NULL_INTERPOLATION',
  'FOREACH_NOT_ARRAY',
  'AGENT_ITERATION_UNSUPPORTED',
  'MAYBE_NULL',
  'UNCAUGHT_FAILURE',
  'UNREACHABLE',
  'CONDITION_CONSTANT',
  'REPEAT_NEVER_TRUE',
  'REPEAT_UNTIL_STATIC',
  'OUTPUT_MAYBE_EMPTY',
  'SUBAUTOMATION_INPUT_INVALID',
  'TRIGGER_INPUT_MISMATCH',
  'TRIGGER_INPUT_NOT_TEMPLATED',
  'TESTS_INPUT_INVALID',
  'TESTS_EFFECT_UNKNOWN',
  'TESTS_EXPECT_TYPE',
  'TESTS_TOO_MANY',
  'TESTS_UNKNOWN_FIELD',
  'TESTS_NAME_DUPLICATE',
  'TESTS_MOCK_UNKNOWN_NODE',
  'TESTS_MOCK_CONFLICT',
  'TESTS_MOCK_NOT_LIST',
  'TESTS_MOCK_TYPE',
  'TESTS_EXPECT_NODE_UNKNOWN',
  'TESTS_EXPECT_PATH_IMPOSSIBLE',
  'TESTS_EXPECT_FAILURE_IMPOSSIBLE',
];

// ------------------------------------------------------------------- tests

interface RenderedCase {
  errors: Array<Record<string, unknown>>;
  warnings: Array<Record<string, unknown>>;
}

function renderIssue(issue: Issue): Record<string, unknown> {
  const out: Record<string, unknown> = { code: issue.code };
  if (issue.nodeId !== undefined) out.nodeId = issue.nodeId;
  if (issue.path !== undefined) out.path = issue.path;
  out.message = issue.message;
  if (issue.hint !== undefined) out.hint = issue.hint;
  if (issue.at !== undefined) out.at = issue.at;
  if (issue.params !== undefined) out.params = issue.params;
  if (issue.related !== undefined) out.related = issue.related;
  return out;
}

async function renderCorpus(): Promise<Record<string, RenderedCase>> {
  const rendered: Record<string, RenderedCase> = {};
  for (const [name, doc] of Object.entries(fixtures)) {
    const { errors, warnings } = await validate(doc, { store });
    rendered[name] = {
      errors: errors.map(renderIssue),
      warnings: warnings.map(renderIssue),
    };
  }
  return rendered;
}

it('renders exactly the pinned issue lists', async () => {
  const actual = await renderCorpus();
  if (process.env.GOLDEN_UPDATE === '1') {
    // Single quotes: the style the committed corpus carries, so a regenerate
    // diffs only what changed.
    writeFileSync(
      GOLDEN_PATH,
      HEADER + stringify(actual, { lineWidth: 0, singleQuote: true }),
    );
    return;
  }
  const golden: unknown = parse(readFileSync(GOLDEN_PATH, 'utf8'));
  expect(actual).toEqual(golden);
});

it('covers every validation code at least once', async () => {
  const rendered = await renderCorpus();
  const emitted = new Set<string>();
  for (const { errors, warnings } of Object.values(rendered)) {
    for (const issue of [...errors, ...warnings]) {
      if (typeof issue.code === 'string') emitted.add(issue.code);
    }
  }
  const byName = (a: string, b: string) => a.localeCompare(b);
  expect([...emitted].sort(byName)).toEqual([...VALIDATION_CODES].sort(byName));
});

it('lists every catalog code as a validation code', () => {
  const byName = (a: string, b: string) => a.localeCompare(b);
  expect(Object.keys(CODES).sort(byName)).toEqual(
    [...VALIDATION_CODES].sort(byName),
  );
});

/** Whether `pointer` names a member of `doc`, or — for a missing member —
 * whether its parent exists. */
function locates(doc: unknown, pointer: string, subject?: string): boolean {
  if (subject === 'missing') {
    const parent = parentPointer(pointer);
    return (
      !resolvePointer(doc, pointer).found &&
      parent !== null &&
      resolvePointer(doc, parent).found
    );
  }
  return resolvePointer(doc, pointer).found;
}

it('locates every issue in its document and builds it from catalog params', async () => {
  const problems: string[] = [];
  for (const [name, doc] of Object.entries(fixtures)) {
    const { errors, warnings } = await validate(doc, { store });
    for (const issue of [...errors, ...warnings]) {
      const label = `${name} ${issue.code}`;
      const { at, params } = issue;
      if (at === undefined || params === undefined) {
        problems.push(`${label}: no at/params`);
        continue;
      }
      if (!locates(doc, at.pointer, at.subject)) {
        problems.push(
          `${label}: ${at.pointer} (${at.subject ?? 'value'}) does not resolve`,
        );
      }
      if (at.range !== undefined) {
        const target = resolvePointer(doc, at.pointer);
        const [start, end] = at.range;
        if (
          !target.found ||
          typeof target.value !== 'string' ||
          start < 0 ||
          start > end ||
          end > target.value.length
        ) {
          problems.push(`${label}: range ${start}-${end} outside the string`);
        }
      }
      for (const rel of issue.related ?? []) {
        if (!locates(doc, rel.at.pointer, rel.at.subject)) {
          problems.push(`${label}: related ${rel.at.pointer} does not resolve`);
        }
      }
      // oxlint-disable-next-line typescript/no-unsafe-type-assertion -- every emitted code is a catalog code (the coverage test above)
      const meta = CODE_META[issue.code as IssueCode];
      if (meta.level !== 'varies' && issue.level !== meta.level) {
        problems.push(`${label}: level ${issue.level}, catalog ${meta.level}`);
      }
      const names = new Set(meta.params.map((p) => p.replace(/\?$/, '')));
      const required = meta.params.filter((p) => !p.endsWith('?'));
      for (const key of Object.keys(params)) {
        if (!names.has(key))
          problems.push(`${label}: param ${key} not in catalog`);
      }
      for (const key of required) {
        if (!(key in params)) problems.push(`${label}: param ${key} missing`);
      }
    }
  }
  expect(problems).toEqual([]);
});
