/**
 * Golden corpus for validation error text.
 *
 * Error text is public API: agents parse it behaviorally, so the FULL
 * rendered issue list (code, nodeId, path, message, hint) for a battery of
 * small invalid documents is pinned in golden-errors.yml. A diff here means
 * a message changed — review it like any API change.
 *
 * After an intentional change, regenerate the fixture with:
 *
 *   GOLDEN_UPDATE=1 bunx vitest --run --project server \
 *     lib/engine/core/validate/golden-errors
 *
 * and commit the reviewed golden-errors.yml alongside the change.
 */

import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

import { beforeAll, expect, it } from 'vitest';
import { parse, stringify } from 'yaml';

import { nodeVmRunner } from '../../runners/node-vm';
import { memoryStore } from '../../selftest/memory-store';
import type { IssueCode } from '../errors';
import { registerNodeType, setCodeRunner, setStoreAdapter } from '../slots';
import type { Automation, Issue } from '../types';
import { validate } from './index';

const GOLDEN_PATH = fileURLToPath(
  new URL('golden-errors.yml', import.meta.url),
);

const HEADER = `# Golden corpus of rendered validation issues — generated by
# golden-errors.test.ts, one entry per fixture document.
#
# Error text is public API. Never edit this file by hand: change the
# validator, review the diff, and regenerate with
#   GOLDEN_UPDATE=1 bunx vitest --run --project server lib/engine/core/validate/golden-errors
`;

beforeAll(() => {
  setCodeRunner(nodeVmRunner());

  const store = memoryStore();
  const noop: Automation = {
    version: 1,
    name: 'send-digest',
    nodes: [{ id: 'noop', type: 'transform', code: 'return input;' }],
  };
  store.save('send-digest', noop);
  store.save('send-digest', noop);
  store.save('weekly-report', { ...noop, name: 'weekly-report' });
  setStoreAdapter(store);

  registerNodeType({
    type: 'weather.current',
    kind: 'connector',
    outputKind: 'structured',
    description: 'test connector: current weather',
    allowedFields: ['input'],
    requiredFields: ['input'],
    connector: {
      name: 'weather.current',
      description: 'current weather for a city',
      inputSchema: {
        type: 'object',
        properties: {
          city: { type: 'string' },
          units: { type: 'string', enum: ['metric', 'imperial'] },
          days: { type: 'integer' },
        },
        required: ['city'],
        additionalProperties: false,
      },
      outputSignature: '{ tempC: number }',
      hasEffect: false,
      mock: () => ({ tempC: 21 }),
    },
  });
  registerNodeType({
    type: 'web.fetch_text',
    kind: 'connector',
    outputKind: 'unstructured',
    description: 'test connector: fetch a page as text',
    allowedFields: ['input'],
    requiredFields: ['input'],
    connector: {
      name: 'web.fetch_text',
      description: 'fetch a page as plain text',
      inputSchema: {
        type: 'object',
        properties: { url: { type: 'string' } },
        required: ['url'],
        additionalProperties: false,
      },
      outputSignature: '{ text: string }',
      hasEffect: false,
      mock: () => ({ text: 'page text' }),
    },
  });
});

// ---------------------------------------------------------------- fixtures

/** A minimal valid document; each fixture breaks exactly one aspect. */
function flow(over: Record<string, unknown> = {}): Record<string, unknown> {
  return {
    version: 1,
    name: 'fixture-flow',
    nodes: [{ id: 'main', type: 'transform', code: 'return 1;' }],
    output: '{{ nodes.main.output }}',
    ...over,
  };
}

function chainOf(count: number): Record<string, unknown> {
  const nodes = Array.from({ length: count }, (_, i) => ({
    id: `t${i}`,
    type: 'transform',
    code: i === 0 ? 'return 1;' : `return nodes.t${i - 1}.output;`,
  }));
  return flow({ nodes, output: `{{ nodes.t${count - 1}.output }}` });
}

const fixtures: Record<string, unknown> = {
  'not-an-object': 42,
  'unknown-top-field': flow({ edges: [] }),
  'version-unsupported': flow({ version: 2 }),
  'version-missing': {
    name: 'fixture-flow',
    nodes: [{ id: 'main', type: 'transform', code: 'return 1;' }],
    output: '{{ nodes.main.output }}',
  },
  'name-invalid': flow({ name: 'My Flow' }),
  'inputs-not-an-object': flow({ inputs: 'city' }),
  'inputs-schema-malformed': flow({
    inputs: { type: 'object', properties: ['city'], required: 'city' },
  }),
  'nodes-missing': { version: 1, name: 'fixture-flow', nodes: [] },
  'nodes-too-many': chainOf(41),
  'secret-api-key': flow({
    nodes: [
      {
        id: 'gen',
        type: 'llm',
        model: 'test-model',
        prompt: 'Authorization: sk-00000000000000000000',
      },
    ],
    output: '{{ nodes.gen.output.text }}',
  }),
  'secret-injected-values': flow({
    nodes: [
      {
        id: 'main',
        type: 'transform',
        input: {
          authorization: 'Bearer 00000000000000000000',
          api_key: 'k0000000000000000000',
        },
        code: 'return input;',
      },
    ],
  }),
  'tests-invalid': flow({
    tests: [
      { name: 'missing-input' },
      { name: 'bad-expect', input: {}, expect: { outputs: 1 } },
    ],
  }),
  'node-not-an-object': flow({ nodes: ['main'], output: 'static result' }),
  'node-id-invalid': flow({
    nodes: [{ id: 'Main', type: 'transform', code: 'return 1;' }],
    output: 'static result',
  }),
  'node-id-duplicate': flow({
    nodes: [
      { id: 'main', type: 'transform', code: 'return 1;' },
      { id: 'main', type: 'transform', code: 'return 2;' },
    ],
  }),
  'unknown-node-type': flow({
    nodes: [{ id: 'main', type: 'transfrom', code: 'return 1;' }],
  }),
  'unknown-node-type-keyword': flow({
    nodes: [
      { id: 'fetch', type: 'connector', input: { city: 'Berlin' } },
      { id: 'main', type: 'transform', code: 'return 1;' },
    ],
  }),
  'node-unknown-field': flow({
    nodes: [{ id: 'main', type: 'transform', code: 'return 1;', prompt: 'hi' }],
  }),
  'llm-missing-model': flow({
    nodes: [{ id: 'gen', type: 'llm', prompt: 'Say hi' }],
    output: '{{ nodes.gen.output.text }}',
  }),
  'transform-missing-code': flow({
    nodes: [{ id: 'main', type: 'transform' }],
  }),
  'node-field-types': flow({
    nodes: [
      {
        id: 'main',
        type: 'transform',
        code: 'return 1;',
        when: 5,
        input: ['x'],
        maxRepeats: 3,
      },
    ],
  }),
  'code-syntax': flow({
    nodes: [{ id: 'main', type: 'transform', code: 'return (;' }],
  }),
  'code-no-io': flow({
    nodes: [
      {
        id: 'main',
        type: 'transform',
        code: 'return fetch("https://example.com").json();',
      },
    ],
  }),
  'code-no-return': flow({
    nodes: [{ id: 'main', type: 'transform', code: 'const total = 1;' }],
  }),
  'output-schema-not-an-object': flow({
    nodes: [
      {
        id: 'gen',
        type: 'llm',
        model: 'test-model',
        prompt: 'Say hi',
        outputSchema: 'json',
      },
    ],
    output: '{{ nodes.gen.output.text }}',
  }),
  'output-schema-malformed': flow({
    nodes: [
      {
        id: 'gen',
        type: 'llm',
        model: 'test-model',
        prompt: 'Say hi',
        outputSchema: { type: 'object', properties: ['headline'] },
      },
    ],
    output: '{{ nodes.gen.output.text }}',
  }),
  'elseof-target-invalid': flow({
    nodes: [
      { id: 'plan', type: 'transform', code: 'return 1;' },
      { id: 'main', type: 'transform', code: 'return 2;', elseOf: 'plan' },
    ],
  }),
  'repeat-max-invalid': flow({
    nodes: [
      {
        id: 'main',
        type: 'transform',
        code: 'return 1;',
        repeatUntil: '{{ output }}',
        maxRepeats: 99,
      },
    ],
  }),
  'onerror-invalid': flow({
    nodes: [
      { id: 'main', type: 'transform', code: 'return 1;', onError: 'retry' },
    ],
  }),
  'subautomation-ref-invalid': flow({
    nodes: [
      { id: 'sub', type: 'subautomation', automation: 'Daily Digest@next' },
    ],
    output: '{{ nodes.sub.output }}',
  }),
  'subautomation-not-found': flow({
    nodes: [{ id: 'sub', type: 'subautomation', automation: 'daily-digest' }],
    output: '{{ nodes.sub.output }}',
  }),
  'subautomation-version-not-found': flow({
    nodes: [{ id: 'sub', type: 'subautomation', automation: 'send-digest@9' }],
    output: '{{ nodes.sub.output }}',
  }),
  'expr-syntax-prompt': flow({
    nodes: [
      {
        id: 'gen',
        type: 'llm',
        model: 'test-model',
        prompt: 'Hello {{ input. }}',
      },
    ],
    output: '{{ nodes.gen.output.text }}',
  }),
  'expr-syntax-when': flow({
    nodes: [
      { id: 'main', type: 'transform', code: 'return 1;', when: '{{ (( }}' },
    ],
  }),
  'ref-unknown-node': flow({
    nodes: [
      { id: 'fetch', type: 'transform', code: 'return 1;' },
      {
        id: 'main',
        type: 'transform',
        code: 'return nodes.fetch.output + nodes.fetc.output;',
      },
    ],
  }),
  'ref-self': flow({
    nodes: [
      { id: 'main', type: 'transform', code: 'return nodes.main.output;' },
    ],
  }),
  'ref-not-output': flow({
    nodes: [
      { id: 'fetch', type: 'transform', code: 'return 1;' },
      { id: 'main', type: 'transform', code: 'return nodes.fetch.result;' },
    ],
  }),
  'ref-bare': flow({
    nodes: [
      { id: 'fetch', type: 'transform', code: 'return 1;' },
      {
        id: 'gen',
        type: 'llm',
        model: 'test-model',
        prompt: 'Data: {{ nodes.fetch }}',
      },
    ],
    output: '{{ nodes.gen.output.text }}',
  }),
  'ref-cycle': flow({
    nodes: [
      { id: 'a', type: 'transform', code: 'return nodes.b.output;' },
      { id: 'b', type: 'transform', code: 'return nodes.a.output;' },
    ],
    output: '{{ nodes.b.output }}',
  }),
  'ref-unstructured-path': flow({
    nodes: [
      { id: 'gen', type: 'llm', model: 'test-model', prompt: 'Summarize' },
      {
        id: 'main',
        type: 'transform',
        code: 'return nodes.gen.output.summary;',
      },
    ],
  }),
  'ref-unstructured-path-connector': flow({
    nodes: [
      {
        id: 'page',
        type: 'web.fetch_text',
        input: { url: 'https://example.com' },
      },
      {
        id: 'main',
        type: 'transform',
        code: 'return nodes.page.output.title;',
      },
    ],
  }),
  'item-without-foreach': flow({
    nodes: [
      {
        id: 'gen',
        type: 'llm',
        model: 'test-model',
        prompt: 'Item {{ item.name }}',
      },
    ],
    output: '{{ nodes.gen.output.text }}',
  }),
  'input-key-unknown': flow({
    inputs: { type: 'object', properties: { city: { type: 'string' } } },
    nodes: [
      {
        id: 'gen',
        type: 'llm',
        model: 'test-model',
        prompt: 'Weather for {{ input.citi }}',
      },
    ],
    output: '{{ nodes.gen.output.text }}',
  }),
  'connector-input-invalid': flow({
    nodes: [
      {
        id: 'w',
        type: 'weather.current',
        input: { units: 'kelvin', extra: true },
      },
    ],
    output: '{{ nodes.w.output }}',
  }),
  'output-missing': {
    version: 1,
    name: 'fixture-flow',
    nodes: [{ id: 'main', type: 'transform', code: 'return 1;' }],
  },
  'unused-node': flow({
    nodes: [
      { id: 'stale', type: 'transform', code: 'return 1;' },
      { id: 'main', type: 'transform', code: 'return 2;' },
    ],
  }),
};

/** Every code the validator can emit; the corpus must cover each at least
 * once, and only codes from the catalog may appear. */
const VALIDATION_CODES: IssueCode[] = [
  'AUTOMATION_NOT_OBJECT',
  'UNKNOWN_TOP_FIELD',
  'VERSION_UNSUPPORTED',
  'VERSION_MISSING',
  'NAME_INVALID',
  'INPUTS_SCHEMA_INVALID',
  'NODES_MISSING',
  'NODES_TOO_MANY',
  'SECRET_IN_DOCUMENT',
  'TESTS_INVALID',
  'NODE_NOT_OBJECT',
  'NODE_ID_INVALID',
  'NODE_ID_DUPLICATE',
  'UNKNOWN_NODE_TYPE',
  'NODE_UNKNOWN_FIELD',
  'NODE_MISSING_FIELD',
  'NODE_FIELD_TYPE',
  'CODE_SYNTAX',
  'CODE_NO_IO',
  'CODE_NO_RETURN',
  'OUTPUT_SCHEMA_INVALID',
  'ELSEOF_TARGET_INVALID',
  'REPEAT_MAX_INVALID',
  'ONERROR_INVALID',
  'SUBAUTOMATION_REF_INVALID',
  'SUBAUTOMATION_NOT_FOUND',
  'EXPR_SYNTAX',
  'REF_UNKNOWN_NODE',
  'REF_SELF',
  'REF_NOT_OUTPUT',
  'REF_BARE',
  'REF_CYCLE',
  'REF_UNSTRUCTURED_PATH',
  'ITEM_WITHOUT_FOREACH',
  'INPUT_KEY_UNKNOWN',
  'CONNECTOR_INPUT_INVALID',
  'OUTPUT_MISSING',
  'UNUSED_NODE',
];

// ------------------------------------------------------------------- tests

interface RenderedCase {
  errors: Array<Record<string, unknown>>;
  warnings: Array<Record<string, unknown>>;
}

function renderIssue(issue: Issue): Record<string, unknown> {
  const out: Record<string, unknown> = { code: issue.code };
  if (issue.nodeId !== undefined) out.nodeId = issue.nodeId;
  if (issue.path !== undefined) out.path = issue.path;
  out.message = issue.message;
  if (issue.hint !== undefined) out.hint = issue.hint;
  return out;
}

async function renderCorpus(): Promise<Record<string, RenderedCase>> {
  const rendered: Record<string, RenderedCase> = {};
  for (const [name, doc] of Object.entries(fixtures)) {
    const { errors, warnings } = await validate(doc);
    rendered[name] = {
      errors: errors.map(renderIssue),
      warnings: warnings.map(renderIssue),
    };
  }
  return rendered;
}

it('renders exactly the pinned issue lists', async () => {
  const actual = await renderCorpus();
  if (process.env.GOLDEN_UPDATE === '1') {
    writeFileSync(GOLDEN_PATH, HEADER + stringify(actual, { lineWidth: 0 }));
    return;
  }
  const golden: unknown = parse(readFileSync(GOLDEN_PATH, 'utf8'));
  expect(actual).toEqual(golden);
});

it('covers every validation code at least once', async () => {
  const rendered = await renderCorpus();
  const emitted = new Set<string>();
  for (const { errors, warnings } of Object.values(rendered)) {
    for (const issue of [...errors, ...warnings]) {
      if (typeof issue.code === 'string') emitted.add(issue.code);
    }
  }
  const byName = (a: string, b: string) => a.localeCompare(b);
  expect([...emitted].sort(byName)).toEqual([...VALIDATION_CODES].sort(byName));
});
