/**
 * Responsive image pipeline for marketing rasters.
 *
 * Reads source files under `public/marketing/sources/` (or CLI args), emits
 * AVIF + WebP at width subsets [480, 828, 1200, 1600] plus a ~24px blur
 * preview, and writes `app/generated/image-manifest.ts`.
 *
 * Outputs are committed — no build-step dependency.
 *
 * Usage:
 *   bun run --filter @tale/web optimize-images
 *   bun scripts/optimize-images.ts path/to/source.png
 */
import { mkdir, readdir } from 'node:fs/promises';
import { basename, extname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import sharp from 'sharp';

const ROOT = resolve(fileURLToPath(new URL('..', import.meta.url)));
const SOURCES = join(ROOT, 'public', 'marketing', 'sources');
const OUT_DIR = join(ROOT, 'public', 'marketing', 'optimized');
const MANIFEST = join(ROOT, 'app', 'generated', 'image-manifest.ts');
const WIDTHS = [480, 828, 1200, 1600] as const;

interface ManifestEntry {
  id: string;
  width: number;
  height: number;
  blurDataURL: string;
  variants: {
    avif: Record<number, string>;
    webp: Record<number, string>;
  };
}

async function main(): Promise<void> {
  const args = process.argv.slice(2);
  let sources: string[] = args;
  if (sources.length === 0) {
    try {
      sources = (await readdir(SOURCES))
        .filter((f) => /\.(png|jpe?g|webp|tiff)$/i.test(f))
        .map((f) => join(SOURCES, f));
    } catch {
      console.log(
        `No sources in ${SOURCES}. Pass image paths as CLI args, or add files there.`,
      );
      await writeEmptyManifest();
      return;
    }
  }

  await mkdir(OUT_DIR, { recursive: true });
  await mkdir(join(ROOT, 'app', 'generated'), { recursive: true });

  const entries: ManifestEntry[] = [];
  for (const src of sources) {
    const id = basename(src, extname(src));
    const image = sharp(src);
    const meta = await image.metadata();
    const width = meta.width ?? 0;
    const height = meta.height ?? 0;

    const avif: Record<number, string> = {};
    const webp: Record<number, string> = {};
    for (const w of WIDTHS) {
      if (width && w > width) continue;
      const avifName = `${id}-${w}.avif`;
      const webpName = `${id}-${w}.webp`;
      await image
        .clone()
        .resize({ width: w, withoutEnlargement: true })
        .avif({ quality: 64 })
        .toFile(join(OUT_DIR, avifName));
      await image
        .clone()
        .resize({ width: w, withoutEnlargement: true })
        .webp({ quality: 78 })
        .toFile(join(OUT_DIR, webpName));
      avif[w] = `/marketing/optimized/${avifName}`;
      webp[w] = `/marketing/optimized/${webpName}`;
    }

    const blurBuf = await image
      .clone()
      .resize({ width: 24 })
      .webp({ quality: 40 })
      .toBuffer();
    const blurDataURL = `data:image/webp;base64,${blurBuf.toString('base64')}`;

    entries.push({ id, width, height, blurDataURL, variants: { avif, webp } });
    console.log(`optimized ${id} (${width}×${height})`);
  }

  await writeManifest(entries);
}

async function writeEmptyManifest(): Promise<void> {
  await mkdir(join(ROOT, 'app', 'generated'), { recursive: true });
  await writeManifest([]);
}

async function writeManifest(entries: ManifestEntry[]): Promise<void> {
  const body = `/* Generated by scripts/optimize-images.ts — do not edit by hand. */
export interface ImageManifestEntry {
  id: string;
  width: number;
  height: number;
  blurDataURL: string;
  variants: {
    avif: Record<number, string>;
    webp: Record<number, string>;
  };
}

export const IMAGE_MANIFEST = ${JSON.stringify(entries, null, 2)} as const satisfies readonly ImageManifestEntry[];

export type ImageManifestId = (typeof IMAGE_MANIFEST)[number]['id'];
`;
  await Bun.write(MANIFEST, body);
  // Match house style so `oxfmt --check` stays green when entries are non-empty.
  const { exitCode } = await Bun.$`bunx oxfmt ${MANIFEST}`
    .cwd(resolve(ROOT, '../..'))
    .nothrow();
  if (exitCode !== 0) {
    throw new Error(`oxfmt failed on ${MANIFEST} (exit ${exitCode})`);
  }
  console.log(`wrote ${MANIFEST} (${entries.length} entries)`);
}

await main();
