import { join } from 'node:path';

/**
 * The scaffolded `default/README.md`, generated by the CLI like AGENTS.md /
 * CLAUDE.md (not part of the embedded `builtin-configs/` catalog — that
 * catalog seeds runtime org dirs in the product, where a project-level README
 * would be wrong). `tale init` writes it and records its checksum; `tale
 * update` syncs it under the same modified/unmodified policy as the other
 * scaffold files.
 *
 * Safe at the org root: the platform's config loading is registry-driven and
 * scans only `<org>/<domain>/` subdirectories, and the config watcher drops
 * paths above the domain level — a Markdown file at `default/` is never
 * loaded, watched, or copied into new orgs.
 */

/** Project-relative path the README is written to (native separators). */
export const DEFAULT_README_RELPATH = join('default', 'README.md');

export const DEFAULT_README_CONTENT = `# Your organization's configuration

This directory is your organization's file-based configuration — agents,
automations, connectors, providers, skills, and branding as plain files.
\`tale dev\` bind-mounts it into the running instance and hot-reloads your
edits.

## Catalog vs. active

A file on disk is a catalog entry, not an active install. Agents marked
\`"metadata": { "autoInstall": true }\` and automations marked
\`"autoInstall": true\` in their manifest are live on a new organization;
everything else stays available in the in-app catalog until you install it
there (or set \`autoInstall\` yourself). An automation's workflow lives
inline in its \`automation.json\` — there are no standalone workflow files.

## Editing

These files are yours: edit, add, or delete them freely, and keep the
directory under version control. Two things are machine-managed and
gitignored — \`*.secrets.json\` (encrypted credentials) and \`.history/\`
directories (edit history); don't edit or commit them.

Learn more: https://docs.tale.dev
`;
