/**
 * Build-time helpers for `app/generated/releases-manifest.ts`.
 * Kept separate from the fetch script so unit tests can pin the
 * write → oxfmt contract without hitting GitHub.
 */

import { spawn } from 'node:child_process';
import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import type { Release } from './types';

const REPO_ROOT = resolve(
  dirname(fileURLToPath(import.meta.url)),
  '../../../..',
);

/** Raw TypeScript source before house-style formatting. */
export function renderReleasesManifestSource(
  releases: readonly Release[],
  fetchedAt: string,
): string {
  return `/* AUTO-GENERATED by scripts/fetch-releases.ts — do not edit. */
import type { Release } from '@/lib/releases/types';

export const RELEASES_FETCHED_AT = ${JSON.stringify(fetchedAt)} as const;

export const RELEASES: readonly Release[] = ${JSON.stringify(releases, null, 2)} as const;
`;
}

function runOxfmt(
  path: string,
  args: string[],
  stdio: 'inherit' | 'ignore' = 'inherit',
): Promise<number> {
  return new Promise((resolveExit, reject) => {
    const child = spawn('bunx', ['oxfmt', ...args, path], {
      cwd: REPO_ROOT,
      stdio,
    });
    child.on('error', reject);
    child.on('close', (code) => resolveExit(code ?? 1));
  });
}

/** Run oxfmt on a generated file so `oxfmt --check` stays green after build. */
export async function formatGeneratedFile(path: string): Promise<void> {
  const code = await runOxfmt(path, []);
  if (code !== 0) {
    throw new Error(`oxfmt failed on ${path} (exit ${code})`);
  }
}

/** True when the file already matches house style. */
export async function isOxfmtClean(path: string): Promise<boolean> {
  const code = await runOxfmt(path, ['--check'], 'ignore');
  return code === 0;
}

export interface WriteReleasesManifestOptions {
  /**
   * Run oxfmt on the written file. Default `true` — keeps `oxfmt --check`
   * green when the manifest is regenerated in the repo. Set `false` where no
   * formatter is available and only the content matters (the Docker builder).
   */
  format?: boolean;
}

/** Write the releases manifest and (by default) format it in place. */
export async function writeReleasesManifest(
  outPath: string,
  releases: readonly Release[],
  fetchedAt: string,
  { format = true }: WriteReleasesManifestOptions = {},
): Promise<void> {
  mkdirSync(dirname(outPath), { recursive: true });
  writeFileSync(outPath, renderReleasesManifestSource(releases, fetchedAt));
  if (format) await formatGeneratedFile(outPath);
}
