# Docker Compose Green Deployment Overlay
# This file defines SEPARATE green services that won't conflict with blue
#
# Usage:
#   VERSION=1.0.0 docker compose -f compose.green.yml up -d platform-green rag-green ...
#
# Note: This file is for production deployments only. It pulls pre-built images
# from GHCR and does NOT support local builds. For local development, use compose.yml.
#
# Key difference from previous approach:
# - Services are named platform-green, rag-green, etc. (not platform, rag)
# - This prevents Docker Compose from touching blue services when deploying green

services:
  # ============================================================================
  # Green Platform
  # ============================================================================
  platform-green:
    image: ghcr.io/tale-project/tale/tale-platform:${VERSION:?VERSION is required}

    container_name: tale-platform-green

    # No host port binding - all traffic through proxy
    # ports: []

    volumes:
      - platform-convex-data:/app/convex-data
      - caddy-data:/caddy-data:ro

    env_file:
      - .env

    restart: unless-stopped

    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:3000/api/health']
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 120s

    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '3'

    networks:
      internal:
        aliases:
          - platform-green
          - platform

  # ============================================================================
  # Green RAG
  # ============================================================================
  rag-green:
    image: ghcr.io/tale-project/tale/tale-rag:${VERSION:?VERSION is required}

    container_name: tale-rag-green

    volumes:
      - rag-data:/app/data

    env_file:
      - .env

    restart: unless-stopped

    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:8001/health']
      interval: 5s
      timeout: 3s
      retries: 2
      start_period: 40s

    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '3'

    networks:
      internal:
        aliases:
          - rag-green
          - rag

  # ============================================================================
  # Green Crawler
  # ============================================================================
  crawler-green:
    image: ghcr.io/tale-project/tale/tale-crawler:${VERSION:?VERSION is required}

    container_name: tale-crawler-green

    env_file:
      - .env

    restart: unless-stopped

    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:8002/health']
      interval: 5s
      timeout: 3s
      retries: 2
      start_period: 40s

    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '3'

    networks:
      internal:
        aliases:
          - crawler-green
          - crawler

  # ============================================================================
  # Green Search
  # ============================================================================
  search-green:
    image: ghcr.io/tale-project/tale/tale-search:${VERSION:?VERSION is required}

    container_name: tale-search-green

    env_file:
      - .env

    restart: unless-stopped

    healthcheck:
      test:
        [
          'CMD',
          'wget',
          '--no-verbose',
          '--tries=1',
          '--spider',
          '--header=X-Real-IP: 127.0.0.1',
          'http://localhost:8080/healthz',
        ]
      interval: 5s
      timeout: 3s
      retries: 2
      start_period: 30s

    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '3'

    networks:
      internal:
        aliases:
          - search-green
          - search

# Reference volumes from base compose.yml
volumes:
  platform-convex-data:
    external: true
    name: tale_platform-convex-data
  caddy-data:
    external: true
    name: tale_caddy-data
  rag-data:
    external: true
    name: tale_rag-data

# Reference network from base compose.yml
networks:
  internal:
    external: true
    name: tale_internal
