# Docker Compose Blue Deployment Overlay
# This file defines SEPARATE blue services that won't conflict with green
#
# Usage:
#   docker compose -f compose.blue.yml up -d platform-blue rag-blue ...
#
# For production (pull pre-built images):
#   PULL_POLICY=always VERSION=v1.0.0 docker compose -f compose.blue.yml up -d ...
#
# Key difference from previous approach:
# - Services are named platform-blue, rag-blue, etc. (not platform, rag)
# - This prevents Docker Compose from touching green services when deploying blue

services:
  # ============================================================================
  # Blue Platform
  # ============================================================================
  platform-blue:
    image: ghcr.io/tale-project/tale/tale-platform:${VERSION:-latest}
    pull_policy: ${PULL_POLICY:-build}
    build:
      context: .
      dockerfile: services/platform/Dockerfile
      args:
        VERSION: ${VERSION:-dev}

    container_name: tale-platform-blue

    # No host port binding - all traffic through proxy
    # ports: []

    volumes:
      - platform-convex-data:/app/convex-data
      - caddy-data:/caddy-data:ro

    env_file:
      - .env

    environment:
      # CA cert paths - entrypoint script checks if files exist before using them
      # With Let's Encrypt, these files don't exist and are safely ignored
      - CADDY_CA_CERT_PATH=/caddy-data/caddy/pki/authorities/local/root.crt

    restart: unless-stopped

    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:3000/api/health']
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 120s

    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '3'

    networks:
      internal:
        aliases:
          - platform-blue
          - platform

  # ============================================================================
  # Blue RAG
  # ============================================================================
  rag-blue:
    image: ghcr.io/tale-project/tale/tale-rag:${VERSION:-latest}
    pull_policy: ${PULL_POLICY:-build}
    build:
      context: .
      dockerfile: services/rag/Dockerfile
      args:
        VERSION: ${VERSION:-dev}

    container_name: tale-rag-blue

    volumes:
      - rag-data:/app/data

    env_file:
      - .env

    environment:
      - RAG_CHUNK_SIZE=512
      - RAG_CHUNK_OVERLAP=50
      # Disable cognee multi-user access control mode
      - ENABLE_BACKEND_ACCESS_CONTROL=false

    restart: unless-stopped

    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:8001/health']
      interval: 5s
      timeout: 3s
      retries: 2
      start_period: 40s

    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '3'

    networks:
      internal:
        aliases:
          - rag-blue
          - rag

  # ============================================================================
  # Blue Crawler
  # ============================================================================
  crawler-blue:
    image: ghcr.io/tale-project/tale/tale-crawler:${VERSION:-latest}
    pull_policy: ${PULL_POLICY:-build}
    build:
      context: .
      dockerfile: services/crawler/Dockerfile
      args:
        VERSION: ${VERSION:-dev}

    container_name: tale-crawler-blue

    env_file:
      - .env

    restart: unless-stopped

    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:8002/health']
      interval: 5s
      timeout: 3s
      retries: 2
      start_period: 40s

    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '3'

    networks:
      internal:
        aliases:
          - crawler-blue
          - crawler

  # ============================================================================
  # Blue Search
  # ============================================================================
  search-blue:
    image: ghcr.io/tale-project/tale/tale-search:${VERSION:-latest}
    pull_policy: ${PULL_POLICY:-build}
    build:
      context: .
      dockerfile: services/search/Dockerfile
      args:
        VERSION: ${VERSION:-dev}

    container_name: tale-search-blue

    env_file:
      - .env

    restart: unless-stopped

    healthcheck:
      test:
        [
          'CMD',
          'wget',
          '--no-verbose',
          '--tries=1',
          '--spider',
          '--header=X-Real-IP: 127.0.0.1',
          'http://localhost:8080/healthz',
        ]
      interval: 5s
      timeout: 3s
      retries: 2
      start_period: 30s

    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '3'

    networks:
      internal:
        aliases:
          - search-blue
          - search

# Reference volumes from base compose.yml
volumes:
  platform-convex-data:
    external: true
    name: tale_platform-convex-data
  caddy-data:
    external: true
    name: tale_caddy-data
  rag-data:
    external: true
    name: tale_rag-data

# Reference network from base compose.yml
networks:
  internal:
    external: true
    name: tale_internal
