# Docker Compose Blue Deployment Overlay
# This file is used with compose.yml for blue-green deployments
#
# Usage:
#   docker compose -f compose.yml -f compose.blue.yml up -d
#
# This overlay:
# - Assigns unique container names with "-blue" suffix
# - Creates network aliases for Caddy health checks
# - Removes host port bindings (traffic goes through proxy)

services:
  # ============================================================================
  # Blue Platform
  # ============================================================================
  platform:
    container_name: tale-platform-blue
    # Remove host port binding - all traffic through proxy
    ports: !reset []
    networks:
      internal:
        aliases:
          - platform-blue

  # ============================================================================
  # Blue RAG
  # ============================================================================
  rag:
    container_name: tale-rag-blue
    networks:
      internal:
        aliases:
          - rag-blue

  # ============================================================================
  # Blue Crawler
  # ============================================================================
  crawler:
    container_name: tale-crawler-blue
    networks:
      internal:
        aliases:
          - crawler-blue

  # ============================================================================
  # Blue Search
  # ============================================================================
  search:
    container_name: tale-search-blue
    networks:
      internal:
        aliases:
          - search-blue

  # ============================================================================
  # Blue Graph DB
  # ============================================================================
  graph-db:
    container_name: tale-graph-db-blue
    networks:
      internal:
        aliases:
          - graph-db-blue
