export default {
  ignoreBinaries: ['uv', 'tsx'],
  ignore: ['examples/**'],
  workspaces: {
    'services/platform': {
      entry: [
        'app/main.tsx',
        'app/routes/**/*.tsx',
        'app/hooks/**/*.{ts,tsx}',
        'app/features/**/*.{ts,tsx}',
        'app/components/**/*.{ts,tsx}',
        'lib/utils/client-utils.ts',
        'convex/http.ts',
        'convex/auth.ts',
        'convex/**/*.ts',
        '!convex/_generated/**',
        '!convex/betterAuth/_generated/**',
        'scripts/**/*.{ts,mjs}',
      ],
      project: ['**/*.{ts,tsx,js,jsx,mjs}'],
      ignore: [
        '**/*.test.{ts,tsx}',
        '**/*.spec.{ts,tsx}',
        'convex/_generated/**',
        'convex/betterAuth/**',
        'node_modules/**',
        'dist/**',
        '.output/**',
        '.vinxi/**',
        'storybook-static/**',
        'coverage/**',
        'src/**',
        'public/**',
        '*.gen.ts',
        '*.gen.tsx',
      ],
      ignoreDependencies: ['convex-test', 'yaml'],
    },
    'tools/cli': {
      project: ['**/*.ts'],
      ignore: ['node_modules/**', 'dist/**'],
    },
  },
  exclude: ['duplicates'],
};
