export default {
  ignoreBinaries: ['uv'],
  ignore: ['examples/**'],
  ignoreDependencies: [
    '@ai-sdk/openai',
    '@ai-sdk/provider-utils',
    '@convex-dev/action-cache',
    '@convex-dev/agent',
    '@convex-dev/better-auth',
    '@convex-dev/persistent-text-streaming',
    '@convex-dev/rate-limiter',
    '@convex-dev/workflow',
    '@convex-dev/workpool',
    'ai',
    'base64-arraybuffer',
    'better-auth',
    'convex',
    'convex-helpers',
    'cron-parser',
    'jexl',
    'jose',
    'lodash',
    'mssql',
    'mustache',
    'mysql2',
    'pg',
    'sucrase',
    'xlsx',
    'zod',
  ],
  workspaces: {
    'services/platform': {
      entry: [
        'app/routes/**/*.tsx',
        'app/hooks/**/*.{ts,tsx}',
        'app/features/**/*.{ts,tsx}',
        'app/components/**/*.{ts,tsx}',
        'lib/utils/client-utils.ts',
        'convex/http.ts',
        'convex/auth.ts',
        'convex/**/*.ts',
        '!convex/_generated/**',
        '!convex/betterAuth/_generated/**',
        'scripts/**/*.ts',
        'server.ts',
      ],
      project: ['**/*.{ts,tsx}'],
      ignoreDependencies: ['convex-test'],
    },
    'tools/cli': {
      project: ['**/*.ts'],
    },
  },
  exclude: ['duplicates'],
};
