// GENERATED by `bun run migrations:sync` — DO NOT EDIT.
// Derived from the folder tree under convex/migrations/versions/;
// `bun run migrations:check` regenerates this file in memory and fails on
// any byte drift. The two-dot basename keeps it out of the Convex function
// address space (same bundler rule that excludes migration.test.ts).
//
// V8-safe: node/reference migrations contribute inline meta literals only —
// their handler modules ('use node' / test-only) are never imported here.

import type { ComponentMigration, DbMigration, MigrationMeta } from './types';

/** Every migration’s metadata, ordered by (semver, numericId). */
export const ALL_META: readonly MigrationMeta[] = [
];

const BY_ID: ReadonlyMap<string, MigrationMeta> = new Map(
  ALL_META.map((m) => [m.id, m]),
);

/** Look up a migration's meta by its stable id; throws on an unknown id. */
export function requireMeta(id: string): MigrationMeta {
  const meta = BY_ID.get(id);
  if (!meta) throw new Error(`Unknown migration id: ${id}`);
  return meta;
}

/** Runnable `db` migrations, keyed by meta.id. */
export const DB_MIGRATIONS: Readonly<Record<string, DbMigration>> = {
};

/** Runnable `component` migrations, keyed by meta.id. */
export const COMPONENT_MIGRATIONS: Readonly<
  Record<string, ComponentMigration>
> = {
};
