'use node';

// GENERATED by `bun run migrations:sync` — DO NOT EDIT.
// Derived from the folder tree under convex/migrations/versions/;
// `bun run migrations:check` regenerates this file in memory and fails on
// any byte drift. The two-dot basename keeps it out of the Convex function
// address space (same bundler rule that excludes migration.test.ts).
//
// Node-migration handler registry: 'use node' handler modules composed
// with their derived meta. Only the node runner imports this.

import type { NodeMigration } from './types';

/** Runnable `node` migrations, keyed by meta.id. */
export const NODE_MIGRATIONS: Readonly<Record<string, NodeMigration>> = {
};
