-- SAML AuthnRequest IDs for InResponseTo replay protection.
--
-- node-saml validates a SAMLResponse's InResponseTo against the request IDs
-- the SP actually issued, through its CacheProvider seam — and REMOVES the ID
-- on successful validation, which is what makes an SP-initiated assertion
-- one-time-use. The default provider is in-memory and per-process; with
-- api + worker containers (or scaled replicas) the response can land on a
-- different instance than the one that issued the request, so the cache must
-- be shared. These rows are protocol nonces (the value is node-saml's issue
-- instant), NOT org-owned data — an AuthnRequest ID is a 160-bit random
-- generated by the library, unique across the deployment by construction.
--
-- Rows are short-lived: consumed by the login that answers them, or lazily
-- pruned after the 8-hour request-expiry window (matching node-saml's
-- requestIdExpirationPeriodMs default) on the next save.
--
-- Rolling-deploy safe: the previous image is still serving while this
-- applies — it never reads the table (its SAML lane validated without
-- InResponseTo), and new rows do not affect it.
CREATE TABLE app.saml_request_ids (
  -- The AuthnRequest ID node-saml generated for the redirect to the IdP.
  id text PRIMARY KEY,
  -- Opaque payload node-saml stores alongside the key (the issue instant).
  value text NOT NULL,
  created_at_ms bigint NOT NULL
);

-- The lazy prune deletes by age; keep that delete indexed so it stays cheap
-- even if a deployment accumulates unanswered requests.
CREATE INDEX saml_request_ids_created_at
  ON app.saml_request_ids (created_at_ms);
