'use node';

import {
  createCipheriv,
  createDecipheriv,
  createHash,
  hkdfSync,
  randomBytes,
} from 'node:crypto';

/**
 * Thin AES-256-GCM wrapper for small DB-stored server-side secrets
 * (moderation API keys, project secrets, …).
 *
 * The 32-byte key is derived from `ENCRYPTION_SECRET_HEX` via HKDF-SHA256
 * with a fixed purpose string, so it is domain-separated from anything else
 * sharing the same root secret. The HKDF constants below are a COMPATIBILITY
 * CONTRACT with ciphertexts already stored on running deployments — never
 * change them.
 *
 * Rotating `ENCRYPTION_SECRET_HEX` changes the derived key and invalidates
 * stored ciphertexts by design; `keyFingerprint` lets callers detect that and
 * prompt the admin to re-enter the secret instead of crashing.
 *
 * All output fields are Base64 so they round-trip through Convex `v.string()`
 * and JSON transport. Not intended for large payloads or streams.
 */

const KEY_BYTES = 32;
const NONCE_BYTES = 12;
// Frozen: deployed ciphertexts were derived with exactly these strings.
const HKDF_INFO = 'tale-guardrails-secret-box/v1';
// Fixed salt is safe here: the input keying material is already a
// high-entropy 32-byte secret; the salt provides domain separation only.
const HKDF_SALT = 'tale-guardrails-v1';

function readKey(): Buffer {
  const raw = process.env.ENCRYPTION_SECRET_HEX;
  if (!raw || raw.trim().length === 0) {
    throw new Error(
      'ENCRYPTION_SECRET_HEX environment variable is not set. The secret box ' +
        'derives its encryption key from ENCRYPTION_SECRET_HEX via HKDF; set ' +
        'it in .env (auto-generated by `tale init`).',
    );
  }
  const derived = hkdfSync(
    'sha256',
    raw.trim(),
    HKDF_SALT,
    HKDF_INFO,
    KEY_BYTES,
  );
  return Buffer.from(derived);
}

/**
 * Stable 12-character fingerprint of the current encryption key. Rows written
 * under a different fingerprint cannot decrypt after a key rotation; callers
 * compare fingerprints and surface "re-enter the secret" instead of throwing.
 */
export function keyFingerprint(): string {
  const key = readKey();
  return createHash('sha256').update(key).digest('hex').slice(0, 12);
}

export interface EncryptedSecret {
  ciphertext: string;
  nonce: string;
  authTag: string;
  keyFingerprint: string;
}

export function encryptSecret(plaintext: string): EncryptedSecret {
  const key = readKey();
  const nonce = randomBytes(NONCE_BYTES);
  const cipher = createCipheriv('aes-256-gcm', key, nonce, {
    authTagLength: 16,
  });
  const ciphertext = Buffer.concat([
    cipher.update(plaintext, 'utf-8'),
    cipher.final(),
  ]);
  const authTag = cipher.getAuthTag();
  return {
    ciphertext: ciphertext.toString('base64'),
    nonce: nonce.toString('base64'),
    authTag: authTag.toString('base64'),
    keyFingerprint: createHash('sha256').update(key).digest('hex').slice(0, 12),
  };
}

export function decryptSecret(input: EncryptedSecret): string {
  const key = readKey();
  const fp = createHash('sha256').update(key).digest('hex').slice(0, 12);
  if (fp !== input.keyFingerprint) {
    throw new KeyRotatedError(
      `Secret was encrypted with a different ENCRYPTION_SECRET_HEX ` +
        `(fingerprint ${input.keyFingerprint}, current ${fp}). ` +
        `Re-save the secret in the admin UI.`,
    );
  }
  const decipher = createDecipheriv(
    'aes-256-gcm',
    key,
    Buffer.from(input.nonce, 'base64'),
    // Pin the GCM tag to 128 bits so truncated-tag forgeries are rejected.
    { authTagLength: 16 },
  );
  decipher.setAuthTag(Buffer.from(input.authTag, 'base64'));
  const plaintext = Buffer.concat([
    decipher.update(Buffer.from(input.ciphertext, 'base64')),
    decipher.final(),
  ]);
  return plaintext.toString('utf-8');
}

export class KeyRotatedError extends Error {
  constructor(message: string) {
    super(message);
    this.name = 'KeyRotatedError';
  }
}
