/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ConvexDashboardRouteImport } from './routes/convex-dashboard'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardCreateOrganizationRouteImport } from './routes/dashboard/create-organization'
import { Route as DashboardIdRouteImport } from './routes/dashboard/$id'
import { Route as AuthSignUpRouteImport } from './routes/_auth/sign-up'
import { Route as AuthLogInRouteImport } from './routes/_auth/log-in'
import { Route as DashboardIdIndexRouteImport } from './routes/dashboard/$id/index'
import { Route as DashboardIdSettingsRouteImport } from './routes/dashboard/$id/settings'
import { Route as DashboardIdCustomAgentsRouteImport } from './routes/dashboard/$id/custom-agents'
import { Route as DashboardIdConversationsRouteImport } from './routes/dashboard/$id/conversations'
import { Route as DashboardIdChatRouteImport } from './routes/dashboard/$id/chat'
import { Route as DashboardIdAutomationsRouteImport } from './routes/dashboard/$id/automations'
import { Route as DashboardIdAgentsRouteImport } from './routes/dashboard/$id/agents'
import { Route as DashboardIdKnowledgeRouteImport } from './routes/dashboard/$id/_knowledge'
import { Route as DashboardIdSettingsIndexRouteImport } from './routes/dashboard/$id/settings/index'
import { Route as DashboardIdChatIndexRouteImport } from './routes/dashboard/$id/chat/index'
import { Route as DashboardIdAutomationsIndexRouteImport } from './routes/dashboard/$id/automations/index'
import { Route as DashboardIdAgentsIndexRouteImport } from './routes/dashboard/$id/agents/index'
import { Route as DashboardIdSettingsTeamsRouteImport } from './routes/dashboard/$id/settings/teams'
import { Route as DashboardIdSettingsOrganizationRouteImport } from './routes/dashboard/$id/settings/organization'
import { Route as DashboardIdSettingsLogsRouteImport } from './routes/dashboard/$id/settings/logs'
import { Route as DashboardIdSettingsIntegrationsRouteImport } from './routes/dashboard/$id/settings/integrations'
import { Route as DashboardIdSettingsBrandingRouteImport } from './routes/dashboard/$id/settings/branding'
import { Route as DashboardIdSettingsApiKeysRouteImport } from './routes/dashboard/$id/settings/api-keys'
import { Route as DashboardIdSettingsAgentsRouteImport } from './routes/dashboard/$id/settings/agents'
import { Route as DashboardIdSettingsAccountRouteImport } from './routes/dashboard/$id/settings/account'
import { Route as DashboardIdConversationsStatusRouteImport } from './routes/dashboard/$id/conversations/$status'
import { Route as DashboardIdChatThreadIdRouteImport } from './routes/dashboard/$id/chat/$threadId'
import { Route as DashboardIdAutomationsAmIdRouteImport } from './routes/dashboard/$id/automations/$amId'
import { Route as DashboardIdAgentsAgentIdRouteImport } from './routes/dashboard/$id/agents/$agentId'
import { Route as DashboardIdKnowledgeWebsitesRouteImport } from './routes/dashboard/$id/_knowledge/websites'
import { Route as DashboardIdKnowledgeVendorsRouteImport } from './routes/dashboard/$id/_knowledge/vendors'
import { Route as DashboardIdKnowledgeProductsRouteImport } from './routes/dashboard/$id/_knowledge/products'
import { Route as DashboardIdKnowledgeDocumentsRouteImport } from './routes/dashboard/$id/_knowledge/documents'
import { Route as DashboardIdKnowledgeCustomersRouteImport } from './routes/dashboard/$id/_knowledge/customers'
import { Route as DashboardIdAgentsAgentIdIndexRouteImport } from './routes/dashboard/$id/agents/$agentId/index'
import { Route as DashboardIdAutomationsAmIdTriggersRouteImport } from './routes/dashboard/$id/automations/$amId/triggers'
import { Route as DashboardIdAutomationsAmIdExecutionsRouteImport } from './routes/dashboard/$id/automations/$amId/executions'
import { Route as DashboardIdAutomationsAmIdConfigurationRouteImport } from './routes/dashboard/$id/automations/$amId/configuration'
import { Route as DashboardIdAgentsAgentIdWebhookRouteImport } from './routes/dashboard/$id/agents/$agentId/webhook'
import { Route as DashboardIdAgentsAgentIdToolsRouteImport } from './routes/dashboard/$id/agents/$agentId/tools'
import { Route as DashboardIdAgentsAgentIdKnowledgeRouteImport } from './routes/dashboard/$id/agents/$agentId/knowledge'
import { Route as DashboardIdAgentsAgentIdInstructionsRouteImport } from './routes/dashboard/$id/agents/$agentId/instructions'
import { Route as DashboardIdAgentsAgentIdDelegationRouteImport } from './routes/dashboard/$id/agents/$agentId/delegation'
import { Route as DashboardIdAgentsAgentIdConversationStartersRouteImport } from './routes/dashboard/$id/agents/$agentId/conversation-starters'

const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ConvexDashboardRoute = ConvexDashboardRouteImport.update({
  id: '/convex-dashboard',
  path: '/convex-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCreateOrganizationRoute =
  DashboardCreateOrganizationRouteImport.update({
    id: '/create-organization',
    path: '/create-organization',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardIdRoute = DashboardIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DashboardRoute,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLogInRoute = AuthLogInRouteImport.update({
  id: '/log-in',
  path: '/log-in',
  getParentRoute: () => AuthRoute,
} as any)
const DashboardIdIndexRoute = DashboardIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardIdRoute,
} as any)
const DashboardIdSettingsRoute = DashboardIdSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardIdRoute,
} as any)
const DashboardIdCustomAgentsRoute = DashboardIdCustomAgentsRouteImport.update({
  id: '/custom-agents',
  path: '/custom-agents',
  getParentRoute: () => DashboardIdRoute,
} as any)
const DashboardIdConversationsRoute =
  DashboardIdConversationsRouteImport.update({
    id: '/conversations',
    path: '/conversations',
    getParentRoute: () => DashboardIdRoute,
  } as any)
const DashboardIdChatRoute = DashboardIdChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => DashboardIdRoute,
} as any)
const DashboardIdAutomationsRoute = DashboardIdAutomationsRouteImport.update({
  id: '/automations',
  path: '/automations',
  getParentRoute: () => DashboardIdRoute,
} as any)
const DashboardIdAgentsRoute = DashboardIdAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => DashboardIdRoute,
} as any)
const DashboardIdKnowledgeRoute = DashboardIdKnowledgeRouteImport.update({
  id: '/_knowledge',
  getParentRoute: () => DashboardIdRoute,
} as any)
const DashboardIdSettingsIndexRoute =
  DashboardIdSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardIdSettingsRoute,
  } as any)
const DashboardIdChatIndexRoute = DashboardIdChatIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardIdChatRoute,
} as any)
const DashboardIdAutomationsIndexRoute =
  DashboardIdAutomationsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardIdAutomationsRoute,
  } as any)
const DashboardIdAgentsIndexRoute = DashboardIdAgentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardIdAgentsRoute,
} as any)
const DashboardIdSettingsTeamsRoute =
  DashboardIdSettingsTeamsRouteImport.update({
    id: '/teams',
    path: '/teams',
    getParentRoute: () => DashboardIdSettingsRoute,
  } as any)
const DashboardIdSettingsOrganizationRoute =
  DashboardIdSettingsOrganizationRouteImport.update({
    id: '/organization',
    path: '/organization',
    getParentRoute: () => DashboardIdSettingsRoute,
  } as any)
const DashboardIdSettingsLogsRoute = DashboardIdSettingsLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => DashboardIdSettingsRoute,
} as any)
const DashboardIdSettingsIntegrationsRoute =
  DashboardIdSettingsIntegrationsRouteImport.update({
    id: '/integrations',
    path: '/integrations',
    getParentRoute: () => DashboardIdSettingsRoute,
  } as any)
const DashboardIdSettingsBrandingRoute =
  DashboardIdSettingsBrandingRouteImport.update({
    id: '/branding',
    path: '/branding',
    getParentRoute: () => DashboardIdSettingsRoute,
  } as any)
const DashboardIdSettingsApiKeysRoute =
  DashboardIdSettingsApiKeysRouteImport.update({
    id: '/api-keys',
    path: '/api-keys',
    getParentRoute: () => DashboardIdSettingsRoute,
  } as any)
const DashboardIdSettingsAgentsRoute =
  DashboardIdSettingsAgentsRouteImport.update({
    id: '/agents',
    path: '/agents',
    getParentRoute: () => DashboardIdSettingsRoute,
  } as any)
const DashboardIdSettingsAccountRoute =
  DashboardIdSettingsAccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => DashboardIdSettingsRoute,
  } as any)
const DashboardIdConversationsStatusRoute =
  DashboardIdConversationsStatusRouteImport.update({
    id: '/$status',
    path: '/$status',
    getParentRoute: () => DashboardIdConversationsRoute,
  } as any)
const DashboardIdChatThreadIdRoute = DashboardIdChatThreadIdRouteImport.update({
  id: '/$threadId',
  path: '/$threadId',
  getParentRoute: () => DashboardIdChatRoute,
} as any)
const DashboardIdAutomationsAmIdRoute =
  DashboardIdAutomationsAmIdRouteImport.update({
    id: '/$amId',
    path: '/$amId',
    getParentRoute: () => DashboardIdAutomationsRoute,
  } as any)
const DashboardIdAgentsAgentIdRoute =
  DashboardIdAgentsAgentIdRouteImport.update({
    id: '/$agentId',
    path: '/$agentId',
    getParentRoute: () => DashboardIdAgentsRoute,
  } as any)
const DashboardIdKnowledgeWebsitesRoute =
  DashboardIdKnowledgeWebsitesRouteImport.update({
    id: '/websites',
    path: '/websites',
    getParentRoute: () => DashboardIdKnowledgeRoute,
  } as any)
const DashboardIdKnowledgeVendorsRoute =
  DashboardIdKnowledgeVendorsRouteImport.update({
    id: '/vendors',
    path: '/vendors',
    getParentRoute: () => DashboardIdKnowledgeRoute,
  } as any)
const DashboardIdKnowledgeProductsRoute =
  DashboardIdKnowledgeProductsRouteImport.update({
    id: '/products',
    path: '/products',
    getParentRoute: () => DashboardIdKnowledgeRoute,
  } as any)
const DashboardIdKnowledgeDocumentsRoute =
  DashboardIdKnowledgeDocumentsRouteImport.update({
    id: '/documents',
    path: '/documents',
    getParentRoute: () => DashboardIdKnowledgeRoute,
  } as any)
const DashboardIdKnowledgeCustomersRoute =
  DashboardIdKnowledgeCustomersRouteImport.update({
    id: '/customers',
    path: '/customers',
    getParentRoute: () => DashboardIdKnowledgeRoute,
  } as any)
const DashboardIdAgentsAgentIdIndexRoute =
  DashboardIdAgentsAgentIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardIdAgentsAgentIdRoute,
  } as any)
const DashboardIdAutomationsAmIdTriggersRoute =
  DashboardIdAutomationsAmIdTriggersRouteImport.update({
    id: '/triggers',
    path: '/triggers',
    getParentRoute: () => DashboardIdAutomationsAmIdRoute,
  } as any)
const DashboardIdAutomationsAmIdExecutionsRoute =
  DashboardIdAutomationsAmIdExecutionsRouteImport.update({
    id: '/executions',
    path: '/executions',
    getParentRoute: () => DashboardIdAutomationsAmIdRoute,
  } as any)
const DashboardIdAutomationsAmIdConfigurationRoute =
  DashboardIdAutomationsAmIdConfigurationRouteImport.update({
    id: '/configuration',
    path: '/configuration',
    getParentRoute: () => DashboardIdAutomationsAmIdRoute,
  } as any)
const DashboardIdAgentsAgentIdWebhookRoute =
  DashboardIdAgentsAgentIdWebhookRouteImport.update({
    id: '/webhook',
    path: '/webhook',
    getParentRoute: () => DashboardIdAgentsAgentIdRoute,
  } as any)
const DashboardIdAgentsAgentIdToolsRoute =
  DashboardIdAgentsAgentIdToolsRouteImport.update({
    id: '/tools',
    path: '/tools',
    getParentRoute: () => DashboardIdAgentsAgentIdRoute,
  } as any)
const DashboardIdAgentsAgentIdKnowledgeRoute =
  DashboardIdAgentsAgentIdKnowledgeRouteImport.update({
    id: '/knowledge',
    path: '/knowledge',
    getParentRoute: () => DashboardIdAgentsAgentIdRoute,
  } as any)
const DashboardIdAgentsAgentIdInstructionsRoute =
  DashboardIdAgentsAgentIdInstructionsRouteImport.update({
    id: '/instructions',
    path: '/instructions',
    getParentRoute: () => DashboardIdAgentsAgentIdRoute,
  } as any)
const DashboardIdAgentsAgentIdDelegationRoute =
  DashboardIdAgentsAgentIdDelegationRouteImport.update({
    id: '/delegation',
    path: '/delegation',
    getParentRoute: () => DashboardIdAgentsAgentIdRoute,
  } as any)
const DashboardIdAgentsAgentIdConversationStartersRoute =
  DashboardIdAgentsAgentIdConversationStartersRouteImport.update({
    id: '/conversation-starters',
    path: '/conversation-starters',
    getParentRoute: () => DashboardIdAgentsAgentIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/convex-dashboard': typeof ConvexDashboardRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/docs': typeof DocsRoute
  '/log-in': typeof AuthLogInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/dashboard/$id': typeof DashboardIdKnowledgeRouteWithChildren
  '/dashboard/create-organization': typeof DashboardCreateOrganizationRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/$id/agents': typeof DashboardIdAgentsRouteWithChildren
  '/dashboard/$id/automations': typeof DashboardIdAutomationsRouteWithChildren
  '/dashboard/$id/chat': typeof DashboardIdChatRouteWithChildren
  '/dashboard/$id/conversations': typeof DashboardIdConversationsRouteWithChildren
  '/dashboard/$id/custom-agents': typeof DashboardIdCustomAgentsRoute
  '/dashboard/$id/settings': typeof DashboardIdSettingsRouteWithChildren
  '/dashboard/$id/': typeof DashboardIdIndexRoute
  '/dashboard/$id/customers': typeof DashboardIdKnowledgeCustomersRoute
  '/dashboard/$id/documents': typeof DashboardIdKnowledgeDocumentsRoute
  '/dashboard/$id/products': typeof DashboardIdKnowledgeProductsRoute
  '/dashboard/$id/vendors': typeof DashboardIdKnowledgeVendorsRoute
  '/dashboard/$id/websites': typeof DashboardIdKnowledgeWebsitesRoute
  '/dashboard/$id/agents/$agentId': typeof DashboardIdAgentsAgentIdRouteWithChildren
  '/dashboard/$id/automations/$amId': typeof DashboardIdAutomationsAmIdRouteWithChildren
  '/dashboard/$id/chat/$threadId': typeof DashboardIdChatThreadIdRoute
  '/dashboard/$id/conversations/$status': typeof DashboardIdConversationsStatusRoute
  '/dashboard/$id/settings/account': typeof DashboardIdSettingsAccountRoute
  '/dashboard/$id/settings/agents': typeof DashboardIdSettingsAgentsRoute
  '/dashboard/$id/settings/api-keys': typeof DashboardIdSettingsApiKeysRoute
  '/dashboard/$id/settings/branding': typeof DashboardIdSettingsBrandingRoute
  '/dashboard/$id/settings/integrations': typeof DashboardIdSettingsIntegrationsRoute
  '/dashboard/$id/settings/logs': typeof DashboardIdSettingsLogsRoute
  '/dashboard/$id/settings/organization': typeof DashboardIdSettingsOrganizationRoute
  '/dashboard/$id/settings/teams': typeof DashboardIdSettingsTeamsRoute
  '/dashboard/$id/agents/': typeof DashboardIdAgentsIndexRoute
  '/dashboard/$id/automations/': typeof DashboardIdAutomationsIndexRoute
  '/dashboard/$id/chat/': typeof DashboardIdChatIndexRoute
  '/dashboard/$id/settings/': typeof DashboardIdSettingsIndexRoute
  '/dashboard/$id/agents/$agentId/conversation-starters': typeof DashboardIdAgentsAgentIdConversationStartersRoute
  '/dashboard/$id/agents/$agentId/delegation': typeof DashboardIdAgentsAgentIdDelegationRoute
  '/dashboard/$id/agents/$agentId/instructions': typeof DashboardIdAgentsAgentIdInstructionsRoute
  '/dashboard/$id/agents/$agentId/knowledge': typeof DashboardIdAgentsAgentIdKnowledgeRoute
  '/dashboard/$id/agents/$agentId/tools': typeof DashboardIdAgentsAgentIdToolsRoute
  '/dashboard/$id/agents/$agentId/webhook': typeof DashboardIdAgentsAgentIdWebhookRoute
  '/dashboard/$id/automations/$amId/configuration': typeof DashboardIdAutomationsAmIdConfigurationRoute
  '/dashboard/$id/automations/$amId/executions': typeof DashboardIdAutomationsAmIdExecutionsRoute
  '/dashboard/$id/automations/$amId/triggers': typeof DashboardIdAutomationsAmIdTriggersRoute
  '/dashboard/$id/agents/$agentId/': typeof DashboardIdAgentsAgentIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/convex-dashboard': typeof ConvexDashboardRoute
  '/docs': typeof DocsRoute
  '/log-in': typeof AuthLogInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/dashboard/create-organization': typeof DashboardCreateOrganizationRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/$id': typeof DashboardIdIndexRoute
  '/dashboard/$id/conversations': typeof DashboardIdConversationsRouteWithChildren
  '/dashboard/$id/custom-agents': typeof DashboardIdCustomAgentsRoute
  '/dashboard/$id/customers': typeof DashboardIdKnowledgeCustomersRoute
  '/dashboard/$id/documents': typeof DashboardIdKnowledgeDocumentsRoute
  '/dashboard/$id/products': typeof DashboardIdKnowledgeProductsRoute
  '/dashboard/$id/vendors': typeof DashboardIdKnowledgeVendorsRoute
  '/dashboard/$id/websites': typeof DashboardIdKnowledgeWebsitesRoute
  '/dashboard/$id/automations/$amId': typeof DashboardIdAutomationsAmIdRouteWithChildren
  '/dashboard/$id/chat/$threadId': typeof DashboardIdChatThreadIdRoute
  '/dashboard/$id/conversations/$status': typeof DashboardIdConversationsStatusRoute
  '/dashboard/$id/settings/account': typeof DashboardIdSettingsAccountRoute
  '/dashboard/$id/settings/agents': typeof DashboardIdSettingsAgentsRoute
  '/dashboard/$id/settings/api-keys': typeof DashboardIdSettingsApiKeysRoute
  '/dashboard/$id/settings/branding': typeof DashboardIdSettingsBrandingRoute
  '/dashboard/$id/settings/integrations': typeof DashboardIdSettingsIntegrationsRoute
  '/dashboard/$id/settings/logs': typeof DashboardIdSettingsLogsRoute
  '/dashboard/$id/settings/organization': typeof DashboardIdSettingsOrganizationRoute
  '/dashboard/$id/settings/teams': typeof DashboardIdSettingsTeamsRoute
  '/dashboard/$id/agents': typeof DashboardIdAgentsIndexRoute
  '/dashboard/$id/automations': typeof DashboardIdAutomationsIndexRoute
  '/dashboard/$id/chat': typeof DashboardIdChatIndexRoute
  '/dashboard/$id/settings': typeof DashboardIdSettingsIndexRoute
  '/dashboard/$id/agents/$agentId/conversation-starters': typeof DashboardIdAgentsAgentIdConversationStartersRoute
  '/dashboard/$id/agents/$agentId/delegation': typeof DashboardIdAgentsAgentIdDelegationRoute
  '/dashboard/$id/agents/$agentId/instructions': typeof DashboardIdAgentsAgentIdInstructionsRoute
  '/dashboard/$id/agents/$agentId/knowledge': typeof DashboardIdAgentsAgentIdKnowledgeRoute
  '/dashboard/$id/agents/$agentId/tools': typeof DashboardIdAgentsAgentIdToolsRoute
  '/dashboard/$id/agents/$agentId/webhook': typeof DashboardIdAgentsAgentIdWebhookRoute
  '/dashboard/$id/automations/$amId/configuration': typeof DashboardIdAutomationsAmIdConfigurationRoute
  '/dashboard/$id/automations/$amId/executions': typeof DashboardIdAutomationsAmIdExecutionsRoute
  '/dashboard/$id/automations/$amId/triggers': typeof DashboardIdAutomationsAmIdTriggersRoute
  '/dashboard/$id/agents/$agentId': typeof DashboardIdAgentsAgentIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/convex-dashboard': typeof ConvexDashboardRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/docs': typeof DocsRoute
  '/_auth/log-in': typeof AuthLogInRoute
  '/_auth/sign-up': typeof AuthSignUpRoute
  '/dashboard/$id': typeof DashboardIdRouteWithChildren
  '/dashboard/create-organization': typeof DashboardCreateOrganizationRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/$id/_knowledge': typeof DashboardIdKnowledgeRouteWithChildren
  '/dashboard/$id/agents': typeof DashboardIdAgentsRouteWithChildren
  '/dashboard/$id/automations': typeof DashboardIdAutomationsRouteWithChildren
  '/dashboard/$id/chat': typeof DashboardIdChatRouteWithChildren
  '/dashboard/$id/conversations': typeof DashboardIdConversationsRouteWithChildren
  '/dashboard/$id/custom-agents': typeof DashboardIdCustomAgentsRoute
  '/dashboard/$id/settings': typeof DashboardIdSettingsRouteWithChildren
  '/dashboard/$id/': typeof DashboardIdIndexRoute
  '/dashboard/$id/_knowledge/customers': typeof DashboardIdKnowledgeCustomersRoute
  '/dashboard/$id/_knowledge/documents': typeof DashboardIdKnowledgeDocumentsRoute
  '/dashboard/$id/_knowledge/products': typeof DashboardIdKnowledgeProductsRoute
  '/dashboard/$id/_knowledge/vendors': typeof DashboardIdKnowledgeVendorsRoute
  '/dashboard/$id/_knowledge/websites': typeof DashboardIdKnowledgeWebsitesRoute
  '/dashboard/$id/agents/$agentId': typeof DashboardIdAgentsAgentIdRouteWithChildren
  '/dashboard/$id/automations/$amId': typeof DashboardIdAutomationsAmIdRouteWithChildren
  '/dashboard/$id/chat/$threadId': typeof DashboardIdChatThreadIdRoute
  '/dashboard/$id/conversations/$status': typeof DashboardIdConversationsStatusRoute
  '/dashboard/$id/settings/account': typeof DashboardIdSettingsAccountRoute
  '/dashboard/$id/settings/agents': typeof DashboardIdSettingsAgentsRoute
  '/dashboard/$id/settings/api-keys': typeof DashboardIdSettingsApiKeysRoute
  '/dashboard/$id/settings/branding': typeof DashboardIdSettingsBrandingRoute
  '/dashboard/$id/settings/integrations': typeof DashboardIdSettingsIntegrationsRoute
  '/dashboard/$id/settings/logs': typeof DashboardIdSettingsLogsRoute
  '/dashboard/$id/settings/organization': typeof DashboardIdSettingsOrganizationRoute
  '/dashboard/$id/settings/teams': typeof DashboardIdSettingsTeamsRoute
  '/dashboard/$id/agents/': typeof DashboardIdAgentsIndexRoute
  '/dashboard/$id/automations/': typeof DashboardIdAutomationsIndexRoute
  '/dashboard/$id/chat/': typeof DashboardIdChatIndexRoute
  '/dashboard/$id/settings/': typeof DashboardIdSettingsIndexRoute
  '/dashboard/$id/agents/$agentId/conversation-starters': typeof DashboardIdAgentsAgentIdConversationStartersRoute
  '/dashboard/$id/agents/$agentId/delegation': typeof DashboardIdAgentsAgentIdDelegationRoute
  '/dashboard/$id/agents/$agentId/instructions': typeof DashboardIdAgentsAgentIdInstructionsRoute
  '/dashboard/$id/agents/$agentId/knowledge': typeof DashboardIdAgentsAgentIdKnowledgeRoute
  '/dashboard/$id/agents/$agentId/tools': typeof DashboardIdAgentsAgentIdToolsRoute
  '/dashboard/$id/agents/$agentId/webhook': typeof DashboardIdAgentsAgentIdWebhookRoute
  '/dashboard/$id/automations/$amId/configuration': typeof DashboardIdAutomationsAmIdConfigurationRoute
  '/dashboard/$id/automations/$amId/executions': typeof DashboardIdAutomationsAmIdExecutionsRoute
  '/dashboard/$id/automations/$amId/triggers': typeof DashboardIdAutomationsAmIdTriggersRoute
  '/dashboard/$id/agents/$agentId/': typeof DashboardIdAgentsAgentIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/convex-dashboard'
    | '/dashboard'
    | '/docs'
    | '/log-in'
    | '/sign-up'
    | '/dashboard/$id'
    | '/dashboard/create-organization'
    | '/dashboard/'
    | '/dashboard/$id/agents'
    | '/dashboard/$id/automations'
    | '/dashboard/$id/chat'
    | '/dashboard/$id/conversations'
    | '/dashboard/$id/custom-agents'
    | '/dashboard/$id/settings'
    | '/dashboard/$id/'
    | '/dashboard/$id/customers'
    | '/dashboard/$id/documents'
    | '/dashboard/$id/products'
    | '/dashboard/$id/vendors'
    | '/dashboard/$id/websites'
    | '/dashboard/$id/agents/$agentId'
    | '/dashboard/$id/automations/$amId'
    | '/dashboard/$id/chat/$threadId'
    | '/dashboard/$id/conversations/$status'
    | '/dashboard/$id/settings/account'
    | '/dashboard/$id/settings/agents'
    | '/dashboard/$id/settings/api-keys'
    | '/dashboard/$id/settings/branding'
    | '/dashboard/$id/settings/integrations'
    | '/dashboard/$id/settings/logs'
    | '/dashboard/$id/settings/organization'
    | '/dashboard/$id/settings/teams'
    | '/dashboard/$id/agents/'
    | '/dashboard/$id/automations/'
    | '/dashboard/$id/chat/'
    | '/dashboard/$id/settings/'
    | '/dashboard/$id/agents/$agentId/conversation-starters'
    | '/dashboard/$id/agents/$agentId/delegation'
    | '/dashboard/$id/agents/$agentId/instructions'
    | '/dashboard/$id/agents/$agentId/knowledge'
    | '/dashboard/$id/agents/$agentId/tools'
    | '/dashboard/$id/agents/$agentId/webhook'
    | '/dashboard/$id/automations/$amId/configuration'
    | '/dashboard/$id/automations/$amId/executions'
    | '/dashboard/$id/automations/$amId/triggers'
    | '/dashboard/$id/agents/$agentId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/convex-dashboard'
    | '/docs'
    | '/log-in'
    | '/sign-up'
    | '/dashboard/create-organization'
    | '/dashboard'
    | '/dashboard/$id'
    | '/dashboard/$id/conversations'
    | '/dashboard/$id/custom-agents'
    | '/dashboard/$id/customers'
    | '/dashboard/$id/documents'
    | '/dashboard/$id/products'
    | '/dashboard/$id/vendors'
    | '/dashboard/$id/websites'
    | '/dashboard/$id/automations/$amId'
    | '/dashboard/$id/chat/$threadId'
    | '/dashboard/$id/conversations/$status'
    | '/dashboard/$id/settings/account'
    | '/dashboard/$id/settings/agents'
    | '/dashboard/$id/settings/api-keys'
    | '/dashboard/$id/settings/branding'
    | '/dashboard/$id/settings/integrations'
    | '/dashboard/$id/settings/logs'
    | '/dashboard/$id/settings/organization'
    | '/dashboard/$id/settings/teams'
    | '/dashboard/$id/agents'
    | '/dashboard/$id/automations'
    | '/dashboard/$id/chat'
    | '/dashboard/$id/settings'
    | '/dashboard/$id/agents/$agentId/conversation-starters'
    | '/dashboard/$id/agents/$agentId/delegation'
    | '/dashboard/$id/agents/$agentId/instructions'
    | '/dashboard/$id/agents/$agentId/knowledge'
    | '/dashboard/$id/agents/$agentId/tools'
    | '/dashboard/$id/agents/$agentId/webhook'
    | '/dashboard/$id/automations/$amId/configuration'
    | '/dashboard/$id/automations/$amId/executions'
    | '/dashboard/$id/automations/$amId/triggers'
    | '/dashboard/$id/agents/$agentId'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/convex-dashboard'
    | '/dashboard'
    | '/docs'
    | '/_auth/log-in'
    | '/_auth/sign-up'
    | '/dashboard/$id'
    | '/dashboard/create-organization'
    | '/dashboard/'
    | '/dashboard/$id/_knowledge'
    | '/dashboard/$id/agents'
    | '/dashboard/$id/automations'
    | '/dashboard/$id/chat'
    | '/dashboard/$id/conversations'
    | '/dashboard/$id/custom-agents'
    | '/dashboard/$id/settings'
    | '/dashboard/$id/'
    | '/dashboard/$id/_knowledge/customers'
    | '/dashboard/$id/_knowledge/documents'
    | '/dashboard/$id/_knowledge/products'
    | '/dashboard/$id/_knowledge/vendors'
    | '/dashboard/$id/_knowledge/websites'
    | '/dashboard/$id/agents/$agentId'
    | '/dashboard/$id/automations/$amId'
    | '/dashboard/$id/chat/$threadId'
    | '/dashboard/$id/conversations/$status'
    | '/dashboard/$id/settings/account'
    | '/dashboard/$id/settings/agents'
    | '/dashboard/$id/settings/api-keys'
    | '/dashboard/$id/settings/branding'
    | '/dashboard/$id/settings/integrations'
    | '/dashboard/$id/settings/logs'
    | '/dashboard/$id/settings/organization'
    | '/dashboard/$id/settings/teams'
    | '/dashboard/$id/agents/'
    | '/dashboard/$id/automations/'
    | '/dashboard/$id/chat/'
    | '/dashboard/$id/settings/'
    | '/dashboard/$id/agents/$agentId/conversation-starters'
    | '/dashboard/$id/agents/$agentId/delegation'
    | '/dashboard/$id/agents/$agentId/instructions'
    | '/dashboard/$id/agents/$agentId/knowledge'
    | '/dashboard/$id/agents/$agentId/tools'
    | '/dashboard/$id/agents/$agentId/webhook'
    | '/dashboard/$id/automations/$amId/configuration'
    | '/dashboard/$id/automations/$amId/executions'
    | '/dashboard/$id/automations/$amId/triggers'
    | '/dashboard/$id/agents/$agentId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  ConvexDashboardRoute: typeof ConvexDashboardRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  DocsRoute: typeof DocsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/convex-dashboard': {
      id: '/convex-dashboard'
      path: '/convex-dashboard'
      fullPath: '/convex-dashboard'
      preLoaderRoute: typeof ConvexDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/create-organization': {
      id: '/dashboard/create-organization'
      path: '/create-organization'
      fullPath: '/dashboard/create-organization'
      preLoaderRoute: typeof DashboardCreateOrganizationRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/$id': {
      id: '/dashboard/$id'
      path: '/$id'
      fullPath: '/dashboard/$id'
      preLoaderRoute: typeof DashboardIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_auth/sign-up': {
      id: '/_auth/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/log-in': {
      id: '/_auth/log-in'
      path: '/log-in'
      fullPath: '/log-in'
      preLoaderRoute: typeof AuthLogInRouteImport
      parentRoute: typeof AuthRoute
    }
    '/dashboard/$id/': {
      id: '/dashboard/$id/'
      path: '/'
      fullPath: '/dashboard/$id/'
      preLoaderRoute: typeof DashboardIdIndexRouteImport
      parentRoute: typeof DashboardIdRoute
    }
    '/dashboard/$id/settings': {
      id: '/dashboard/$id/settings'
      path: '/settings'
      fullPath: '/dashboard/$id/settings'
      preLoaderRoute: typeof DashboardIdSettingsRouteImport
      parentRoute: typeof DashboardIdRoute
    }
    '/dashboard/$id/custom-agents': {
      id: '/dashboard/$id/custom-agents'
      path: '/custom-agents'
      fullPath: '/dashboard/$id/custom-agents'
      preLoaderRoute: typeof DashboardIdCustomAgentsRouteImport
      parentRoute: typeof DashboardIdRoute
    }
    '/dashboard/$id/conversations': {
      id: '/dashboard/$id/conversations'
      path: '/conversations'
      fullPath: '/dashboard/$id/conversations'
      preLoaderRoute: typeof DashboardIdConversationsRouteImport
      parentRoute: typeof DashboardIdRoute
    }
    '/dashboard/$id/chat': {
      id: '/dashboard/$id/chat'
      path: '/chat'
      fullPath: '/dashboard/$id/chat'
      preLoaderRoute: typeof DashboardIdChatRouteImport
      parentRoute: typeof DashboardIdRoute
    }
    '/dashboard/$id/automations': {
      id: '/dashboard/$id/automations'
      path: '/automations'
      fullPath: '/dashboard/$id/automations'
      preLoaderRoute: typeof DashboardIdAutomationsRouteImport
      parentRoute: typeof DashboardIdRoute
    }
    '/dashboard/$id/agents': {
      id: '/dashboard/$id/agents'
      path: '/agents'
      fullPath: '/dashboard/$id/agents'
      preLoaderRoute: typeof DashboardIdAgentsRouteImport
      parentRoute: typeof DashboardIdRoute
    }
    '/dashboard/$id/_knowledge': {
      id: '/dashboard/$id/_knowledge'
      path: ''
      fullPath: '/dashboard/$id'
      preLoaderRoute: typeof DashboardIdKnowledgeRouteImport
      parentRoute: typeof DashboardIdRoute
    }
    '/dashboard/$id/settings/': {
      id: '/dashboard/$id/settings/'
      path: '/'
      fullPath: '/dashboard/$id/settings/'
      preLoaderRoute: typeof DashboardIdSettingsIndexRouteImport
      parentRoute: typeof DashboardIdSettingsRoute
    }
    '/dashboard/$id/chat/': {
      id: '/dashboard/$id/chat/'
      path: '/'
      fullPath: '/dashboard/$id/chat/'
      preLoaderRoute: typeof DashboardIdChatIndexRouteImport
      parentRoute: typeof DashboardIdChatRoute
    }
    '/dashboard/$id/automations/': {
      id: '/dashboard/$id/automations/'
      path: '/'
      fullPath: '/dashboard/$id/automations/'
      preLoaderRoute: typeof DashboardIdAutomationsIndexRouteImport
      parentRoute: typeof DashboardIdAutomationsRoute
    }
    '/dashboard/$id/agents/': {
      id: '/dashboard/$id/agents/'
      path: '/'
      fullPath: '/dashboard/$id/agents/'
      preLoaderRoute: typeof DashboardIdAgentsIndexRouteImport
      parentRoute: typeof DashboardIdAgentsRoute
    }
    '/dashboard/$id/settings/teams': {
      id: '/dashboard/$id/settings/teams'
      path: '/teams'
      fullPath: '/dashboard/$id/settings/teams'
      preLoaderRoute: typeof DashboardIdSettingsTeamsRouteImport
      parentRoute: typeof DashboardIdSettingsRoute
    }
    '/dashboard/$id/settings/organization': {
      id: '/dashboard/$id/settings/organization'
      path: '/organization'
      fullPath: '/dashboard/$id/settings/organization'
      preLoaderRoute: typeof DashboardIdSettingsOrganizationRouteImport
      parentRoute: typeof DashboardIdSettingsRoute
    }
    '/dashboard/$id/settings/logs': {
      id: '/dashboard/$id/settings/logs'
      path: '/logs'
      fullPath: '/dashboard/$id/settings/logs'
      preLoaderRoute: typeof DashboardIdSettingsLogsRouteImport
      parentRoute: typeof DashboardIdSettingsRoute
    }
    '/dashboard/$id/settings/integrations': {
      id: '/dashboard/$id/settings/integrations'
      path: '/integrations'
      fullPath: '/dashboard/$id/settings/integrations'
      preLoaderRoute: typeof DashboardIdSettingsIntegrationsRouteImport
      parentRoute: typeof DashboardIdSettingsRoute
    }
    '/dashboard/$id/settings/branding': {
      id: '/dashboard/$id/settings/branding'
      path: '/branding'
      fullPath: '/dashboard/$id/settings/branding'
      preLoaderRoute: typeof DashboardIdSettingsBrandingRouteImport
      parentRoute: typeof DashboardIdSettingsRoute
    }
    '/dashboard/$id/settings/api-keys': {
      id: '/dashboard/$id/settings/api-keys'
      path: '/api-keys'
      fullPath: '/dashboard/$id/settings/api-keys'
      preLoaderRoute: typeof DashboardIdSettingsApiKeysRouteImport
      parentRoute: typeof DashboardIdSettingsRoute
    }
    '/dashboard/$id/settings/agents': {
      id: '/dashboard/$id/settings/agents'
      path: '/agents'
      fullPath: '/dashboard/$id/settings/agents'
      preLoaderRoute: typeof DashboardIdSettingsAgentsRouteImport
      parentRoute: typeof DashboardIdSettingsRoute
    }
    '/dashboard/$id/settings/account': {
      id: '/dashboard/$id/settings/account'
      path: '/account'
      fullPath: '/dashboard/$id/settings/account'
      preLoaderRoute: typeof DashboardIdSettingsAccountRouteImport
      parentRoute: typeof DashboardIdSettingsRoute
    }
    '/dashboard/$id/conversations/$status': {
      id: '/dashboard/$id/conversations/$status'
      path: '/$status'
      fullPath: '/dashboard/$id/conversations/$status'
      preLoaderRoute: typeof DashboardIdConversationsStatusRouteImport
      parentRoute: typeof DashboardIdConversationsRoute
    }
    '/dashboard/$id/chat/$threadId': {
      id: '/dashboard/$id/chat/$threadId'
      path: '/$threadId'
      fullPath: '/dashboard/$id/chat/$threadId'
      preLoaderRoute: typeof DashboardIdChatThreadIdRouteImport
      parentRoute: typeof DashboardIdChatRoute
    }
    '/dashboard/$id/automations/$amId': {
      id: '/dashboard/$id/automations/$amId'
      path: '/$amId'
      fullPath: '/dashboard/$id/automations/$amId'
      preLoaderRoute: typeof DashboardIdAutomationsAmIdRouteImport
      parentRoute: typeof DashboardIdAutomationsRoute
    }
    '/dashboard/$id/agents/$agentId': {
      id: '/dashboard/$id/agents/$agentId'
      path: '/$agentId'
      fullPath: '/dashboard/$id/agents/$agentId'
      preLoaderRoute: typeof DashboardIdAgentsAgentIdRouteImport
      parentRoute: typeof DashboardIdAgentsRoute
    }
    '/dashboard/$id/_knowledge/websites': {
      id: '/dashboard/$id/_knowledge/websites'
      path: '/websites'
      fullPath: '/dashboard/$id/websites'
      preLoaderRoute: typeof DashboardIdKnowledgeWebsitesRouteImport
      parentRoute: typeof DashboardIdKnowledgeRoute
    }
    '/dashboard/$id/_knowledge/vendors': {
      id: '/dashboard/$id/_knowledge/vendors'
      path: '/vendors'
      fullPath: '/dashboard/$id/vendors'
      preLoaderRoute: typeof DashboardIdKnowledgeVendorsRouteImport
      parentRoute: typeof DashboardIdKnowledgeRoute
    }
    '/dashboard/$id/_knowledge/products': {
      id: '/dashboard/$id/_knowledge/products'
      path: '/products'
      fullPath: '/dashboard/$id/products'
      preLoaderRoute: typeof DashboardIdKnowledgeProductsRouteImport
      parentRoute: typeof DashboardIdKnowledgeRoute
    }
    '/dashboard/$id/_knowledge/documents': {
      id: '/dashboard/$id/_knowledge/documents'
      path: '/documents'
      fullPath: '/dashboard/$id/documents'
      preLoaderRoute: typeof DashboardIdKnowledgeDocumentsRouteImport
      parentRoute: typeof DashboardIdKnowledgeRoute
    }
    '/dashboard/$id/_knowledge/customers': {
      id: '/dashboard/$id/_knowledge/customers'
      path: '/customers'
      fullPath: '/dashboard/$id/customers'
      preLoaderRoute: typeof DashboardIdKnowledgeCustomersRouteImport
      parentRoute: typeof DashboardIdKnowledgeRoute
    }
    '/dashboard/$id/agents/$agentId/': {
      id: '/dashboard/$id/agents/$agentId/'
      path: '/'
      fullPath: '/dashboard/$id/agents/$agentId/'
      preLoaderRoute: typeof DashboardIdAgentsAgentIdIndexRouteImport
      parentRoute: typeof DashboardIdAgentsAgentIdRoute
    }
    '/dashboard/$id/automations/$amId/triggers': {
      id: '/dashboard/$id/automations/$amId/triggers'
      path: '/triggers'
      fullPath: '/dashboard/$id/automations/$amId/triggers'
      preLoaderRoute: typeof DashboardIdAutomationsAmIdTriggersRouteImport
      parentRoute: typeof DashboardIdAutomationsAmIdRoute
    }
    '/dashboard/$id/automations/$amId/executions': {
      id: '/dashboard/$id/automations/$amId/executions'
      path: '/executions'
      fullPath: '/dashboard/$id/automations/$amId/executions'
      preLoaderRoute: typeof DashboardIdAutomationsAmIdExecutionsRouteImport
      parentRoute: typeof DashboardIdAutomationsAmIdRoute
    }
    '/dashboard/$id/automations/$amId/configuration': {
      id: '/dashboard/$id/automations/$amId/configuration'
      path: '/configuration'
      fullPath: '/dashboard/$id/automations/$amId/configuration'
      preLoaderRoute: typeof DashboardIdAutomationsAmIdConfigurationRouteImport
      parentRoute: typeof DashboardIdAutomationsAmIdRoute
    }
    '/dashboard/$id/agents/$agentId/webhook': {
      id: '/dashboard/$id/agents/$agentId/webhook'
      path: '/webhook'
      fullPath: '/dashboard/$id/agents/$agentId/webhook'
      preLoaderRoute: typeof DashboardIdAgentsAgentIdWebhookRouteImport
      parentRoute: typeof DashboardIdAgentsAgentIdRoute
    }
    '/dashboard/$id/agents/$agentId/tools': {
      id: '/dashboard/$id/agents/$agentId/tools'
      path: '/tools'
      fullPath: '/dashboard/$id/agents/$agentId/tools'
      preLoaderRoute: typeof DashboardIdAgentsAgentIdToolsRouteImport
      parentRoute: typeof DashboardIdAgentsAgentIdRoute
    }
    '/dashboard/$id/agents/$agentId/knowledge': {
      id: '/dashboard/$id/agents/$agentId/knowledge'
      path: '/knowledge'
      fullPath: '/dashboard/$id/agents/$agentId/knowledge'
      preLoaderRoute: typeof DashboardIdAgentsAgentIdKnowledgeRouteImport
      parentRoute: typeof DashboardIdAgentsAgentIdRoute
    }
    '/dashboard/$id/agents/$agentId/instructions': {
      id: '/dashboard/$id/agents/$agentId/instructions'
      path: '/instructions'
      fullPath: '/dashboard/$id/agents/$agentId/instructions'
      preLoaderRoute: typeof DashboardIdAgentsAgentIdInstructionsRouteImport
      parentRoute: typeof DashboardIdAgentsAgentIdRoute
    }
    '/dashboard/$id/agents/$agentId/delegation': {
      id: '/dashboard/$id/agents/$agentId/delegation'
      path: '/delegation'
      fullPath: '/dashboard/$id/agents/$agentId/delegation'
      preLoaderRoute: typeof DashboardIdAgentsAgentIdDelegationRouteImport
      parentRoute: typeof DashboardIdAgentsAgentIdRoute
    }
    '/dashboard/$id/agents/$agentId/conversation-starters': {
      id: '/dashboard/$id/agents/$agentId/conversation-starters'
      path: '/conversation-starters'
      fullPath: '/dashboard/$id/agents/$agentId/conversation-starters'
      preLoaderRoute: typeof DashboardIdAgentsAgentIdConversationStartersRouteImport
      parentRoute: typeof DashboardIdAgentsAgentIdRoute
    }
  }
}

interface AuthRouteChildren {
  AuthLogInRoute: typeof AuthLogInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLogInRoute: AuthLogInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface DashboardIdKnowledgeRouteChildren {
  DashboardIdKnowledgeCustomersRoute: typeof DashboardIdKnowledgeCustomersRoute
  DashboardIdKnowledgeDocumentsRoute: typeof DashboardIdKnowledgeDocumentsRoute
  DashboardIdKnowledgeProductsRoute: typeof DashboardIdKnowledgeProductsRoute
  DashboardIdKnowledgeVendorsRoute: typeof DashboardIdKnowledgeVendorsRoute
  DashboardIdKnowledgeWebsitesRoute: typeof DashboardIdKnowledgeWebsitesRoute
}

const DashboardIdKnowledgeRouteChildren: DashboardIdKnowledgeRouteChildren = {
  DashboardIdKnowledgeCustomersRoute: DashboardIdKnowledgeCustomersRoute,
  DashboardIdKnowledgeDocumentsRoute: DashboardIdKnowledgeDocumentsRoute,
  DashboardIdKnowledgeProductsRoute: DashboardIdKnowledgeProductsRoute,
  DashboardIdKnowledgeVendorsRoute: DashboardIdKnowledgeVendorsRoute,
  DashboardIdKnowledgeWebsitesRoute: DashboardIdKnowledgeWebsitesRoute,
}

const DashboardIdKnowledgeRouteWithChildren =
  DashboardIdKnowledgeRoute._addFileChildren(DashboardIdKnowledgeRouteChildren)

interface DashboardIdAgentsAgentIdRouteChildren {
  DashboardIdAgentsAgentIdConversationStartersRoute: typeof DashboardIdAgentsAgentIdConversationStartersRoute
  DashboardIdAgentsAgentIdDelegationRoute: typeof DashboardIdAgentsAgentIdDelegationRoute
  DashboardIdAgentsAgentIdInstructionsRoute: typeof DashboardIdAgentsAgentIdInstructionsRoute
  DashboardIdAgentsAgentIdKnowledgeRoute: typeof DashboardIdAgentsAgentIdKnowledgeRoute
  DashboardIdAgentsAgentIdToolsRoute: typeof DashboardIdAgentsAgentIdToolsRoute
  DashboardIdAgentsAgentIdWebhookRoute: typeof DashboardIdAgentsAgentIdWebhookRoute
  DashboardIdAgentsAgentIdIndexRoute: typeof DashboardIdAgentsAgentIdIndexRoute
}

const DashboardIdAgentsAgentIdRouteChildren: DashboardIdAgentsAgentIdRouteChildren =
  {
    DashboardIdAgentsAgentIdConversationStartersRoute:
      DashboardIdAgentsAgentIdConversationStartersRoute,
    DashboardIdAgentsAgentIdDelegationRoute:
      DashboardIdAgentsAgentIdDelegationRoute,
    DashboardIdAgentsAgentIdInstructionsRoute:
      DashboardIdAgentsAgentIdInstructionsRoute,
    DashboardIdAgentsAgentIdKnowledgeRoute:
      DashboardIdAgentsAgentIdKnowledgeRoute,
    DashboardIdAgentsAgentIdToolsRoute: DashboardIdAgentsAgentIdToolsRoute,
    DashboardIdAgentsAgentIdWebhookRoute: DashboardIdAgentsAgentIdWebhookRoute,
    DashboardIdAgentsAgentIdIndexRoute: DashboardIdAgentsAgentIdIndexRoute,
  }

const DashboardIdAgentsAgentIdRouteWithChildren =
  DashboardIdAgentsAgentIdRoute._addFileChildren(
    DashboardIdAgentsAgentIdRouteChildren,
  )

interface DashboardIdAgentsRouteChildren {
  DashboardIdAgentsAgentIdRoute: typeof DashboardIdAgentsAgentIdRouteWithChildren
  DashboardIdAgentsIndexRoute: typeof DashboardIdAgentsIndexRoute
}

const DashboardIdAgentsRouteChildren: DashboardIdAgentsRouteChildren = {
  DashboardIdAgentsAgentIdRoute: DashboardIdAgentsAgentIdRouteWithChildren,
  DashboardIdAgentsIndexRoute: DashboardIdAgentsIndexRoute,
}

const DashboardIdAgentsRouteWithChildren =
  DashboardIdAgentsRoute._addFileChildren(DashboardIdAgentsRouteChildren)

interface DashboardIdAutomationsAmIdRouteChildren {
  DashboardIdAutomationsAmIdConfigurationRoute: typeof DashboardIdAutomationsAmIdConfigurationRoute
  DashboardIdAutomationsAmIdExecutionsRoute: typeof DashboardIdAutomationsAmIdExecutionsRoute
  DashboardIdAutomationsAmIdTriggersRoute: typeof DashboardIdAutomationsAmIdTriggersRoute
}

const DashboardIdAutomationsAmIdRouteChildren: DashboardIdAutomationsAmIdRouteChildren =
  {
    DashboardIdAutomationsAmIdConfigurationRoute:
      DashboardIdAutomationsAmIdConfigurationRoute,
    DashboardIdAutomationsAmIdExecutionsRoute:
      DashboardIdAutomationsAmIdExecutionsRoute,
    DashboardIdAutomationsAmIdTriggersRoute:
      DashboardIdAutomationsAmIdTriggersRoute,
  }

const DashboardIdAutomationsAmIdRouteWithChildren =
  DashboardIdAutomationsAmIdRoute._addFileChildren(
    DashboardIdAutomationsAmIdRouteChildren,
  )

interface DashboardIdAutomationsRouteChildren {
  DashboardIdAutomationsAmIdRoute: typeof DashboardIdAutomationsAmIdRouteWithChildren
  DashboardIdAutomationsIndexRoute: typeof DashboardIdAutomationsIndexRoute
}

const DashboardIdAutomationsRouteChildren: DashboardIdAutomationsRouteChildren =
  {
    DashboardIdAutomationsAmIdRoute:
      DashboardIdAutomationsAmIdRouteWithChildren,
    DashboardIdAutomationsIndexRoute: DashboardIdAutomationsIndexRoute,
  }

const DashboardIdAutomationsRouteWithChildren =
  DashboardIdAutomationsRoute._addFileChildren(
    DashboardIdAutomationsRouteChildren,
  )

interface DashboardIdChatRouteChildren {
  DashboardIdChatThreadIdRoute: typeof DashboardIdChatThreadIdRoute
  DashboardIdChatIndexRoute: typeof DashboardIdChatIndexRoute
}

const DashboardIdChatRouteChildren: DashboardIdChatRouteChildren = {
  DashboardIdChatThreadIdRoute: DashboardIdChatThreadIdRoute,
  DashboardIdChatIndexRoute: DashboardIdChatIndexRoute,
}

const DashboardIdChatRouteWithChildren = DashboardIdChatRoute._addFileChildren(
  DashboardIdChatRouteChildren,
)

interface DashboardIdConversationsRouteChildren {
  DashboardIdConversationsStatusRoute: typeof DashboardIdConversationsStatusRoute
}

const DashboardIdConversationsRouteChildren: DashboardIdConversationsRouteChildren =
  {
    DashboardIdConversationsStatusRoute: DashboardIdConversationsStatusRoute,
  }

const DashboardIdConversationsRouteWithChildren =
  DashboardIdConversationsRoute._addFileChildren(
    DashboardIdConversationsRouteChildren,
  )

interface DashboardIdSettingsRouteChildren {
  DashboardIdSettingsAccountRoute: typeof DashboardIdSettingsAccountRoute
  DashboardIdSettingsAgentsRoute: typeof DashboardIdSettingsAgentsRoute
  DashboardIdSettingsApiKeysRoute: typeof DashboardIdSettingsApiKeysRoute
  DashboardIdSettingsBrandingRoute: typeof DashboardIdSettingsBrandingRoute
  DashboardIdSettingsIntegrationsRoute: typeof DashboardIdSettingsIntegrationsRoute
  DashboardIdSettingsLogsRoute: typeof DashboardIdSettingsLogsRoute
  DashboardIdSettingsOrganizationRoute: typeof DashboardIdSettingsOrganizationRoute
  DashboardIdSettingsTeamsRoute: typeof DashboardIdSettingsTeamsRoute
  DashboardIdSettingsIndexRoute: typeof DashboardIdSettingsIndexRoute
}

const DashboardIdSettingsRouteChildren: DashboardIdSettingsRouteChildren = {
  DashboardIdSettingsAccountRoute: DashboardIdSettingsAccountRoute,
  DashboardIdSettingsAgentsRoute: DashboardIdSettingsAgentsRoute,
  DashboardIdSettingsApiKeysRoute: DashboardIdSettingsApiKeysRoute,
  DashboardIdSettingsBrandingRoute: DashboardIdSettingsBrandingRoute,
  DashboardIdSettingsIntegrationsRoute: DashboardIdSettingsIntegrationsRoute,
  DashboardIdSettingsLogsRoute: DashboardIdSettingsLogsRoute,
  DashboardIdSettingsOrganizationRoute: DashboardIdSettingsOrganizationRoute,
  DashboardIdSettingsTeamsRoute: DashboardIdSettingsTeamsRoute,
  DashboardIdSettingsIndexRoute: DashboardIdSettingsIndexRoute,
}

const DashboardIdSettingsRouteWithChildren =
  DashboardIdSettingsRoute._addFileChildren(DashboardIdSettingsRouteChildren)

interface DashboardIdRouteChildren {
  DashboardIdKnowledgeRoute: typeof DashboardIdKnowledgeRouteWithChildren
  DashboardIdAgentsRoute: typeof DashboardIdAgentsRouteWithChildren
  DashboardIdAutomationsRoute: typeof DashboardIdAutomationsRouteWithChildren
  DashboardIdChatRoute: typeof DashboardIdChatRouteWithChildren
  DashboardIdConversationsRoute: typeof DashboardIdConversationsRouteWithChildren
  DashboardIdCustomAgentsRoute: typeof DashboardIdCustomAgentsRoute
  DashboardIdSettingsRoute: typeof DashboardIdSettingsRouteWithChildren
  DashboardIdIndexRoute: typeof DashboardIdIndexRoute
}

const DashboardIdRouteChildren: DashboardIdRouteChildren = {
  DashboardIdKnowledgeRoute: DashboardIdKnowledgeRouteWithChildren,
  DashboardIdAgentsRoute: DashboardIdAgentsRouteWithChildren,
  DashboardIdAutomationsRoute: DashboardIdAutomationsRouteWithChildren,
  DashboardIdChatRoute: DashboardIdChatRouteWithChildren,
  DashboardIdConversationsRoute: DashboardIdConversationsRouteWithChildren,
  DashboardIdCustomAgentsRoute: DashboardIdCustomAgentsRoute,
  DashboardIdSettingsRoute: DashboardIdSettingsRouteWithChildren,
  DashboardIdIndexRoute: DashboardIdIndexRoute,
}

const DashboardIdRouteWithChildren = DashboardIdRoute._addFileChildren(
  DashboardIdRouteChildren,
)

interface DashboardRouteChildren {
  DashboardIdRoute: typeof DashboardIdRouteWithChildren
  DashboardCreateOrganizationRoute: typeof DashboardCreateOrganizationRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardIdRoute: DashboardIdRouteWithChildren,
  DashboardCreateOrganizationRoute: DashboardCreateOrganizationRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  ConvexDashboardRoute: ConvexDashboardRoute,
  DashboardRoute: DashboardRouteWithChildren,
  DocsRoute: DocsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
