/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ConvexDashboardRouteImport } from './routes/convex-dashboard'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardCreateOrganizationRouteImport } from './routes/dashboard/create-organization'
import { Route as DashboardIdRouteImport } from './routes/dashboard/$id'
import { Route as AuthSignUpRouteImport } from './routes/_auth/sign-up'
import { Route as AuthLogInRouteImport } from './routes/_auth/log-in'
import { Route as DashboardIdIndexRouteImport } from './routes/dashboard/$id/index'
import { Route as DashboardIdSettingsRouteImport } from './routes/dashboard/$id/settings'
import { Route as DashboardIdCustomAgentsRouteImport } from './routes/dashboard/$id/custom-agents'
import { Route as DashboardIdConversationsRouteImport } from './routes/dashboard/$id/conversations'
import { Route as DashboardIdChatRouteImport } from './routes/dashboard/$id/chat'
import { Route as DashboardIdAutomationsRouteImport } from './routes/dashboard/$id/automations'
import { Route as DashboardIdApprovalsRouteImport } from './routes/dashboard/$id/approvals'
import { Route as DashboardIdKnowledgeRouteImport } from './routes/dashboard/$id/_knowledge'
import { Route as DashboardIdSettingsIndexRouteImport } from './routes/dashboard/$id/settings/index'
import { Route as DashboardIdCustomAgentsIndexRouteImport } from './routes/dashboard/$id/custom-agents/index'
import { Route as DashboardIdChatIndexRouteImport } from './routes/dashboard/$id/chat/index'
import { Route as DashboardIdAutomationsIndexRouteImport } from './routes/dashboard/$id/automations/index'
import { Route as DashboardIdSettingsTeamsRouteImport } from './routes/dashboard/$id/settings/teams'
import { Route as DashboardIdSettingsOrganizationRouteImport } from './routes/dashboard/$id/settings/organization'
import { Route as DashboardIdSettingsLogsRouteImport } from './routes/dashboard/$id/settings/logs'
import { Route as DashboardIdSettingsIntegrationsRouteImport } from './routes/dashboard/$id/settings/integrations'
import { Route as DashboardIdSettingsCustomAgentsRouteImport } from './routes/dashboard/$id/settings/custom-agents'
import { Route as DashboardIdSettingsBrandingRouteImport } from './routes/dashboard/$id/settings/branding'
import { Route as DashboardIdSettingsApiKeysRouteImport } from './routes/dashboard/$id/settings/api-keys'
import { Route as DashboardIdSettingsAccountRouteImport } from './routes/dashboard/$id/settings/account'
import { Route as DashboardIdCustomAgentsAgentIdRouteImport } from './routes/dashboard/$id/custom-agents/$agentId'
import { Route as DashboardIdConversationsStatusRouteImport } from './routes/dashboard/$id/conversations/$status'
import { Route as DashboardIdChatThreadIdRouteImport } from './routes/dashboard/$id/chat/$threadId'
import { Route as DashboardIdAutomationsAmIdRouteImport } from './routes/dashboard/$id/automations/$amId'
import { Route as DashboardIdApprovalsStatusRouteImport } from './routes/dashboard/$id/approvals/$status'
import { Route as DashboardIdKnowledgeWebsitesRouteImport } from './routes/dashboard/$id/_knowledge/websites'
import { Route as DashboardIdKnowledgeVendorsRouteImport } from './routes/dashboard/$id/_knowledge/vendors'
import { Route as DashboardIdKnowledgeToneOfVoiceRouteImport } from './routes/dashboard/$id/_knowledge/tone-of-voice'
import { Route as DashboardIdKnowledgeProductsRouteImport } from './routes/dashboard/$id/_knowledge/products'
import { Route as DashboardIdKnowledgeDocumentsRouteImport } from './routes/dashboard/$id/_knowledge/documents'
import { Route as DashboardIdKnowledgeCustomersRouteImport } from './routes/dashboard/$id/_knowledge/customers'
import { Route as DashboardIdCustomAgentsAgentIdIndexRouteImport } from './routes/dashboard/$id/custom-agents/$agentId/index'
import { Route as DashboardIdCustomAgentsAgentIdWebhookRouteImport } from './routes/dashboard/$id/custom-agents/$agentId/webhook'
import { Route as DashboardIdCustomAgentsAgentIdToolsRouteImport } from './routes/dashboard/$id/custom-agents/$agentId/tools'
import { Route as DashboardIdCustomAgentsAgentIdKnowledgeRouteImport } from './routes/dashboard/$id/custom-agents/$agentId/knowledge'
import { Route as DashboardIdCustomAgentsAgentIdInstructionsRouteImport } from './routes/dashboard/$id/custom-agents/$agentId/instructions'
import { Route as DashboardIdAutomationsAmIdTriggersRouteImport } from './routes/dashboard/$id/automations/$amId/triggers'
import { Route as DashboardIdAutomationsAmIdExecutionsRouteImport } from './routes/dashboard/$id/automations/$amId/executions'
import { Route as DashboardIdAutomationsAmIdConfigurationRouteImport } from './routes/dashboard/$id/automations/$amId/configuration'

const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ConvexDashboardRoute = ConvexDashboardRouteImport.update({
  id: '/convex-dashboard',
  path: '/convex-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCreateOrganizationRoute =
  DashboardCreateOrganizationRouteImport.update({
    id: '/create-organization',
    path: '/create-organization',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardIdRoute = DashboardIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DashboardRoute,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLogInRoute = AuthLogInRouteImport.update({
  id: '/log-in',
  path: '/log-in',
  getParentRoute: () => AuthRoute,
} as any)
const DashboardIdIndexRoute = DashboardIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardIdRoute,
} as any)
const DashboardIdSettingsRoute = DashboardIdSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardIdRoute,
} as any)
const DashboardIdCustomAgentsRoute = DashboardIdCustomAgentsRouteImport.update({
  id: '/custom-agents',
  path: '/custom-agents',
  getParentRoute: () => DashboardIdRoute,
} as any)
const DashboardIdConversationsRoute =
  DashboardIdConversationsRouteImport.update({
    id: '/conversations',
    path: '/conversations',
    getParentRoute: () => DashboardIdRoute,
  } as any)
const DashboardIdChatRoute = DashboardIdChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => DashboardIdRoute,
} as any)
const DashboardIdAutomationsRoute = DashboardIdAutomationsRouteImport.update({
  id: '/automations',
  path: '/automations',
  getParentRoute: () => DashboardIdRoute,
} as any)
const DashboardIdApprovalsRoute = DashboardIdApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => DashboardIdRoute,
} as any)
const DashboardIdKnowledgeRoute = DashboardIdKnowledgeRouteImport.update({
  id: '/_knowledge',
  getParentRoute: () => DashboardIdRoute,
} as any)
const DashboardIdSettingsIndexRoute =
  DashboardIdSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardIdSettingsRoute,
  } as any)
const DashboardIdCustomAgentsIndexRoute =
  DashboardIdCustomAgentsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardIdCustomAgentsRoute,
  } as any)
const DashboardIdChatIndexRoute = DashboardIdChatIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardIdChatRoute,
} as any)
const DashboardIdAutomationsIndexRoute =
  DashboardIdAutomationsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardIdAutomationsRoute,
  } as any)
const DashboardIdSettingsTeamsRoute =
  DashboardIdSettingsTeamsRouteImport.update({
    id: '/teams',
    path: '/teams',
    getParentRoute: () => DashboardIdSettingsRoute,
  } as any)
const DashboardIdSettingsOrganizationRoute =
  DashboardIdSettingsOrganizationRouteImport.update({
    id: '/organization',
    path: '/organization',
    getParentRoute: () => DashboardIdSettingsRoute,
  } as any)
const DashboardIdSettingsLogsRoute = DashboardIdSettingsLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => DashboardIdSettingsRoute,
} as any)
const DashboardIdSettingsIntegrationsRoute =
  DashboardIdSettingsIntegrationsRouteImport.update({
    id: '/integrations',
    path: '/integrations',
    getParentRoute: () => DashboardIdSettingsRoute,
  } as any)
const DashboardIdSettingsCustomAgentsRoute =
  DashboardIdSettingsCustomAgentsRouteImport.update({
    id: '/custom-agents',
    path: '/custom-agents',
    getParentRoute: () => DashboardIdSettingsRoute,
  } as any)
const DashboardIdSettingsBrandingRoute =
  DashboardIdSettingsBrandingRouteImport.update({
    id: '/branding',
    path: '/branding',
    getParentRoute: () => DashboardIdSettingsRoute,
  } as any)
const DashboardIdSettingsApiKeysRoute =
  DashboardIdSettingsApiKeysRouteImport.update({
    id: '/api-keys',
    path: '/api-keys',
    getParentRoute: () => DashboardIdSettingsRoute,
  } as any)
const DashboardIdSettingsAccountRoute =
  DashboardIdSettingsAccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => DashboardIdSettingsRoute,
  } as any)
const DashboardIdCustomAgentsAgentIdRoute =
  DashboardIdCustomAgentsAgentIdRouteImport.update({
    id: '/$agentId',
    path: '/$agentId',
    getParentRoute: () => DashboardIdCustomAgentsRoute,
  } as any)
const DashboardIdConversationsStatusRoute =
  DashboardIdConversationsStatusRouteImport.update({
    id: '/$status',
    path: '/$status',
    getParentRoute: () => DashboardIdConversationsRoute,
  } as any)
const DashboardIdChatThreadIdRoute = DashboardIdChatThreadIdRouteImport.update({
  id: '/$threadId',
  path: '/$threadId',
  getParentRoute: () => DashboardIdChatRoute,
} as any)
const DashboardIdAutomationsAmIdRoute =
  DashboardIdAutomationsAmIdRouteImport.update({
    id: '/$amId',
    path: '/$amId',
    getParentRoute: () => DashboardIdAutomationsRoute,
  } as any)
const DashboardIdApprovalsStatusRoute =
  DashboardIdApprovalsStatusRouteImport.update({
    id: '/$status',
    path: '/$status',
    getParentRoute: () => DashboardIdApprovalsRoute,
  } as any)
const DashboardIdKnowledgeWebsitesRoute =
  DashboardIdKnowledgeWebsitesRouteImport.update({
    id: '/websites',
    path: '/websites',
    getParentRoute: () => DashboardIdKnowledgeRoute,
  } as any)
const DashboardIdKnowledgeVendorsRoute =
  DashboardIdKnowledgeVendorsRouteImport.update({
    id: '/vendors',
    path: '/vendors',
    getParentRoute: () => DashboardIdKnowledgeRoute,
  } as any)
const DashboardIdKnowledgeToneOfVoiceRoute =
  DashboardIdKnowledgeToneOfVoiceRouteImport.update({
    id: '/tone-of-voice',
    path: '/tone-of-voice',
    getParentRoute: () => DashboardIdKnowledgeRoute,
  } as any)
const DashboardIdKnowledgeProductsRoute =
  DashboardIdKnowledgeProductsRouteImport.update({
    id: '/products',
    path: '/products',
    getParentRoute: () => DashboardIdKnowledgeRoute,
  } as any)
const DashboardIdKnowledgeDocumentsRoute =
  DashboardIdKnowledgeDocumentsRouteImport.update({
    id: '/documents',
    path: '/documents',
    getParentRoute: () => DashboardIdKnowledgeRoute,
  } as any)
const DashboardIdKnowledgeCustomersRoute =
  DashboardIdKnowledgeCustomersRouteImport.update({
    id: '/customers',
    path: '/customers',
    getParentRoute: () => DashboardIdKnowledgeRoute,
  } as any)
const DashboardIdCustomAgentsAgentIdIndexRoute =
  DashboardIdCustomAgentsAgentIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardIdCustomAgentsAgentIdRoute,
  } as any)
const DashboardIdCustomAgentsAgentIdWebhookRoute =
  DashboardIdCustomAgentsAgentIdWebhookRouteImport.update({
    id: '/webhook',
    path: '/webhook',
    getParentRoute: () => DashboardIdCustomAgentsAgentIdRoute,
  } as any)
const DashboardIdCustomAgentsAgentIdToolsRoute =
  DashboardIdCustomAgentsAgentIdToolsRouteImport.update({
    id: '/tools',
    path: '/tools',
    getParentRoute: () => DashboardIdCustomAgentsAgentIdRoute,
  } as any)
const DashboardIdCustomAgentsAgentIdKnowledgeRoute =
  DashboardIdCustomAgentsAgentIdKnowledgeRouteImport.update({
    id: '/knowledge',
    path: '/knowledge',
    getParentRoute: () => DashboardIdCustomAgentsAgentIdRoute,
  } as any)
const DashboardIdCustomAgentsAgentIdInstructionsRoute =
  DashboardIdCustomAgentsAgentIdInstructionsRouteImport.update({
    id: '/instructions',
    path: '/instructions',
    getParentRoute: () => DashboardIdCustomAgentsAgentIdRoute,
  } as any)
const DashboardIdAutomationsAmIdTriggersRoute =
  DashboardIdAutomationsAmIdTriggersRouteImport.update({
    id: '/triggers',
    path: '/triggers',
    getParentRoute: () => DashboardIdAutomationsAmIdRoute,
  } as any)
const DashboardIdAutomationsAmIdExecutionsRoute =
  DashboardIdAutomationsAmIdExecutionsRouteImport.update({
    id: '/executions',
    path: '/executions',
    getParentRoute: () => DashboardIdAutomationsAmIdRoute,
  } as any)
const DashboardIdAutomationsAmIdConfigurationRoute =
  DashboardIdAutomationsAmIdConfigurationRouteImport.update({
    id: '/configuration',
    path: '/configuration',
    getParentRoute: () => DashboardIdAutomationsAmIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/convex-dashboard': typeof ConvexDashboardRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/docs': typeof DocsRoute
  '/log-in': typeof AuthLogInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/dashboard/$id': typeof DashboardIdKnowledgeRouteWithChildren
  '/dashboard/create-organization': typeof DashboardCreateOrganizationRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/$id/approvals': typeof DashboardIdApprovalsRouteWithChildren
  '/dashboard/$id/automations': typeof DashboardIdAutomationsRouteWithChildren
  '/dashboard/$id/chat': typeof DashboardIdChatRouteWithChildren
  '/dashboard/$id/conversations': typeof DashboardIdConversationsRouteWithChildren
  '/dashboard/$id/custom-agents': typeof DashboardIdCustomAgentsRouteWithChildren
  '/dashboard/$id/settings': typeof DashboardIdSettingsRouteWithChildren
  '/dashboard/$id/': typeof DashboardIdIndexRoute
  '/dashboard/$id/customers': typeof DashboardIdKnowledgeCustomersRoute
  '/dashboard/$id/documents': typeof DashboardIdKnowledgeDocumentsRoute
  '/dashboard/$id/products': typeof DashboardIdKnowledgeProductsRoute
  '/dashboard/$id/tone-of-voice': typeof DashboardIdKnowledgeToneOfVoiceRoute
  '/dashboard/$id/vendors': typeof DashboardIdKnowledgeVendorsRoute
  '/dashboard/$id/websites': typeof DashboardIdKnowledgeWebsitesRoute
  '/dashboard/$id/approvals/$status': typeof DashboardIdApprovalsStatusRoute
  '/dashboard/$id/automations/$amId': typeof DashboardIdAutomationsAmIdRouteWithChildren
  '/dashboard/$id/chat/$threadId': typeof DashboardIdChatThreadIdRoute
  '/dashboard/$id/conversations/$status': typeof DashboardIdConversationsStatusRoute
  '/dashboard/$id/custom-agents/$agentId': typeof DashboardIdCustomAgentsAgentIdRouteWithChildren
  '/dashboard/$id/settings/account': typeof DashboardIdSettingsAccountRoute
  '/dashboard/$id/settings/api-keys': typeof DashboardIdSettingsApiKeysRoute
  '/dashboard/$id/settings/branding': typeof DashboardIdSettingsBrandingRoute
  '/dashboard/$id/settings/custom-agents': typeof DashboardIdSettingsCustomAgentsRoute
  '/dashboard/$id/settings/integrations': typeof DashboardIdSettingsIntegrationsRoute
  '/dashboard/$id/settings/logs': typeof DashboardIdSettingsLogsRoute
  '/dashboard/$id/settings/organization': typeof DashboardIdSettingsOrganizationRoute
  '/dashboard/$id/settings/teams': typeof DashboardIdSettingsTeamsRoute
  '/dashboard/$id/automations/': typeof DashboardIdAutomationsIndexRoute
  '/dashboard/$id/chat/': typeof DashboardIdChatIndexRoute
  '/dashboard/$id/custom-agents/': typeof DashboardIdCustomAgentsIndexRoute
  '/dashboard/$id/settings/': typeof DashboardIdSettingsIndexRoute
  '/dashboard/$id/automations/$amId/configuration': typeof DashboardIdAutomationsAmIdConfigurationRoute
  '/dashboard/$id/automations/$amId/executions': typeof DashboardIdAutomationsAmIdExecutionsRoute
  '/dashboard/$id/automations/$amId/triggers': typeof DashboardIdAutomationsAmIdTriggersRoute
  '/dashboard/$id/custom-agents/$agentId/instructions': typeof DashboardIdCustomAgentsAgentIdInstructionsRoute
  '/dashboard/$id/custom-agents/$agentId/knowledge': typeof DashboardIdCustomAgentsAgentIdKnowledgeRoute
  '/dashboard/$id/custom-agents/$agentId/tools': typeof DashboardIdCustomAgentsAgentIdToolsRoute
  '/dashboard/$id/custom-agents/$agentId/webhook': typeof DashboardIdCustomAgentsAgentIdWebhookRoute
  '/dashboard/$id/custom-agents/$agentId/': typeof DashboardIdCustomAgentsAgentIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/convex-dashboard': typeof ConvexDashboardRoute
  '/docs': typeof DocsRoute
  '/log-in': typeof AuthLogInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/dashboard/create-organization': typeof DashboardCreateOrganizationRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/$id': typeof DashboardIdIndexRoute
  '/dashboard/$id/approvals': typeof DashboardIdApprovalsRouteWithChildren
  '/dashboard/$id/conversations': typeof DashboardIdConversationsRouteWithChildren
  '/dashboard/$id/customers': typeof DashboardIdKnowledgeCustomersRoute
  '/dashboard/$id/documents': typeof DashboardIdKnowledgeDocumentsRoute
  '/dashboard/$id/products': typeof DashboardIdKnowledgeProductsRoute
  '/dashboard/$id/tone-of-voice': typeof DashboardIdKnowledgeToneOfVoiceRoute
  '/dashboard/$id/vendors': typeof DashboardIdKnowledgeVendorsRoute
  '/dashboard/$id/websites': typeof DashboardIdKnowledgeWebsitesRoute
  '/dashboard/$id/approvals/$status': typeof DashboardIdApprovalsStatusRoute
  '/dashboard/$id/automations/$amId': typeof DashboardIdAutomationsAmIdRouteWithChildren
  '/dashboard/$id/chat/$threadId': typeof DashboardIdChatThreadIdRoute
  '/dashboard/$id/conversations/$status': typeof DashboardIdConversationsStatusRoute
  '/dashboard/$id/settings/account': typeof DashboardIdSettingsAccountRoute
  '/dashboard/$id/settings/api-keys': typeof DashboardIdSettingsApiKeysRoute
  '/dashboard/$id/settings/branding': typeof DashboardIdSettingsBrandingRoute
  '/dashboard/$id/settings/custom-agents': typeof DashboardIdSettingsCustomAgentsRoute
  '/dashboard/$id/settings/integrations': typeof DashboardIdSettingsIntegrationsRoute
  '/dashboard/$id/settings/logs': typeof DashboardIdSettingsLogsRoute
  '/dashboard/$id/settings/organization': typeof DashboardIdSettingsOrganizationRoute
  '/dashboard/$id/settings/teams': typeof DashboardIdSettingsTeamsRoute
  '/dashboard/$id/automations': typeof DashboardIdAutomationsIndexRoute
  '/dashboard/$id/chat': typeof DashboardIdChatIndexRoute
  '/dashboard/$id/custom-agents': typeof DashboardIdCustomAgentsIndexRoute
  '/dashboard/$id/settings': typeof DashboardIdSettingsIndexRoute
  '/dashboard/$id/automations/$amId/configuration': typeof DashboardIdAutomationsAmIdConfigurationRoute
  '/dashboard/$id/automations/$amId/executions': typeof DashboardIdAutomationsAmIdExecutionsRoute
  '/dashboard/$id/automations/$amId/triggers': typeof DashboardIdAutomationsAmIdTriggersRoute
  '/dashboard/$id/custom-agents/$agentId/instructions': typeof DashboardIdCustomAgentsAgentIdInstructionsRoute
  '/dashboard/$id/custom-agents/$agentId/knowledge': typeof DashboardIdCustomAgentsAgentIdKnowledgeRoute
  '/dashboard/$id/custom-agents/$agentId/tools': typeof DashboardIdCustomAgentsAgentIdToolsRoute
  '/dashboard/$id/custom-agents/$agentId/webhook': typeof DashboardIdCustomAgentsAgentIdWebhookRoute
  '/dashboard/$id/custom-agents/$agentId': typeof DashboardIdCustomAgentsAgentIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/convex-dashboard': typeof ConvexDashboardRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/docs': typeof DocsRoute
  '/_auth/log-in': typeof AuthLogInRoute
  '/_auth/sign-up': typeof AuthSignUpRoute
  '/dashboard/$id': typeof DashboardIdRouteWithChildren
  '/dashboard/create-organization': typeof DashboardCreateOrganizationRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/$id/_knowledge': typeof DashboardIdKnowledgeRouteWithChildren
  '/dashboard/$id/approvals': typeof DashboardIdApprovalsRouteWithChildren
  '/dashboard/$id/automations': typeof DashboardIdAutomationsRouteWithChildren
  '/dashboard/$id/chat': typeof DashboardIdChatRouteWithChildren
  '/dashboard/$id/conversations': typeof DashboardIdConversationsRouteWithChildren
  '/dashboard/$id/custom-agents': typeof DashboardIdCustomAgentsRouteWithChildren
  '/dashboard/$id/settings': typeof DashboardIdSettingsRouteWithChildren
  '/dashboard/$id/': typeof DashboardIdIndexRoute
  '/dashboard/$id/_knowledge/customers': typeof DashboardIdKnowledgeCustomersRoute
  '/dashboard/$id/_knowledge/documents': typeof DashboardIdKnowledgeDocumentsRoute
  '/dashboard/$id/_knowledge/products': typeof DashboardIdKnowledgeProductsRoute
  '/dashboard/$id/_knowledge/tone-of-voice': typeof DashboardIdKnowledgeToneOfVoiceRoute
  '/dashboard/$id/_knowledge/vendors': typeof DashboardIdKnowledgeVendorsRoute
  '/dashboard/$id/_knowledge/websites': typeof DashboardIdKnowledgeWebsitesRoute
  '/dashboard/$id/approvals/$status': typeof DashboardIdApprovalsStatusRoute
  '/dashboard/$id/automations/$amId': typeof DashboardIdAutomationsAmIdRouteWithChildren
  '/dashboard/$id/chat/$threadId': typeof DashboardIdChatThreadIdRoute
  '/dashboard/$id/conversations/$status': typeof DashboardIdConversationsStatusRoute
  '/dashboard/$id/custom-agents/$agentId': typeof DashboardIdCustomAgentsAgentIdRouteWithChildren
  '/dashboard/$id/settings/account': typeof DashboardIdSettingsAccountRoute
  '/dashboard/$id/settings/api-keys': typeof DashboardIdSettingsApiKeysRoute
  '/dashboard/$id/settings/branding': typeof DashboardIdSettingsBrandingRoute
  '/dashboard/$id/settings/custom-agents': typeof DashboardIdSettingsCustomAgentsRoute
  '/dashboard/$id/settings/integrations': typeof DashboardIdSettingsIntegrationsRoute
  '/dashboard/$id/settings/logs': typeof DashboardIdSettingsLogsRoute
  '/dashboard/$id/settings/organization': typeof DashboardIdSettingsOrganizationRoute
  '/dashboard/$id/settings/teams': typeof DashboardIdSettingsTeamsRoute
  '/dashboard/$id/automations/': typeof DashboardIdAutomationsIndexRoute
  '/dashboard/$id/chat/': typeof DashboardIdChatIndexRoute
  '/dashboard/$id/custom-agents/': typeof DashboardIdCustomAgentsIndexRoute
  '/dashboard/$id/settings/': typeof DashboardIdSettingsIndexRoute
  '/dashboard/$id/automations/$amId/configuration': typeof DashboardIdAutomationsAmIdConfigurationRoute
  '/dashboard/$id/automations/$amId/executions': typeof DashboardIdAutomationsAmIdExecutionsRoute
  '/dashboard/$id/automations/$amId/triggers': typeof DashboardIdAutomationsAmIdTriggersRoute
  '/dashboard/$id/custom-agents/$agentId/instructions': typeof DashboardIdCustomAgentsAgentIdInstructionsRoute
  '/dashboard/$id/custom-agents/$agentId/knowledge': typeof DashboardIdCustomAgentsAgentIdKnowledgeRoute
  '/dashboard/$id/custom-agents/$agentId/tools': typeof DashboardIdCustomAgentsAgentIdToolsRoute
  '/dashboard/$id/custom-agents/$agentId/webhook': typeof DashboardIdCustomAgentsAgentIdWebhookRoute
  '/dashboard/$id/custom-agents/$agentId/': typeof DashboardIdCustomAgentsAgentIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/convex-dashboard'
    | '/dashboard'
    | '/docs'
    | '/log-in'
    | '/sign-up'
    | '/dashboard/$id'
    | '/dashboard/create-organization'
    | '/dashboard/'
    | '/dashboard/$id/approvals'
    | '/dashboard/$id/automations'
    | '/dashboard/$id/chat'
    | '/dashboard/$id/conversations'
    | '/dashboard/$id/custom-agents'
    | '/dashboard/$id/settings'
    | '/dashboard/$id/'
    | '/dashboard/$id/customers'
    | '/dashboard/$id/documents'
    | '/dashboard/$id/products'
    | '/dashboard/$id/tone-of-voice'
    | '/dashboard/$id/vendors'
    | '/dashboard/$id/websites'
    | '/dashboard/$id/approvals/$status'
    | '/dashboard/$id/automations/$amId'
    | '/dashboard/$id/chat/$threadId'
    | '/dashboard/$id/conversations/$status'
    | '/dashboard/$id/custom-agents/$agentId'
    | '/dashboard/$id/settings/account'
    | '/dashboard/$id/settings/api-keys'
    | '/dashboard/$id/settings/branding'
    | '/dashboard/$id/settings/custom-agents'
    | '/dashboard/$id/settings/integrations'
    | '/dashboard/$id/settings/logs'
    | '/dashboard/$id/settings/organization'
    | '/dashboard/$id/settings/teams'
    | '/dashboard/$id/automations/'
    | '/dashboard/$id/chat/'
    | '/dashboard/$id/custom-agents/'
    | '/dashboard/$id/settings/'
    | '/dashboard/$id/automations/$amId/configuration'
    | '/dashboard/$id/automations/$amId/executions'
    | '/dashboard/$id/automations/$amId/triggers'
    | '/dashboard/$id/custom-agents/$agentId/instructions'
    | '/dashboard/$id/custom-agents/$agentId/knowledge'
    | '/dashboard/$id/custom-agents/$agentId/tools'
    | '/dashboard/$id/custom-agents/$agentId/webhook'
    | '/dashboard/$id/custom-agents/$agentId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/convex-dashboard'
    | '/docs'
    | '/log-in'
    | '/sign-up'
    | '/dashboard/create-organization'
    | '/dashboard'
    | '/dashboard/$id'
    | '/dashboard/$id/approvals'
    | '/dashboard/$id/conversations'
    | '/dashboard/$id/customers'
    | '/dashboard/$id/documents'
    | '/dashboard/$id/products'
    | '/dashboard/$id/tone-of-voice'
    | '/dashboard/$id/vendors'
    | '/dashboard/$id/websites'
    | '/dashboard/$id/approvals/$status'
    | '/dashboard/$id/automations/$amId'
    | '/dashboard/$id/chat/$threadId'
    | '/dashboard/$id/conversations/$status'
    | '/dashboard/$id/settings/account'
    | '/dashboard/$id/settings/api-keys'
    | '/dashboard/$id/settings/branding'
    | '/dashboard/$id/settings/custom-agents'
    | '/dashboard/$id/settings/integrations'
    | '/dashboard/$id/settings/logs'
    | '/dashboard/$id/settings/organization'
    | '/dashboard/$id/settings/teams'
    | '/dashboard/$id/automations'
    | '/dashboard/$id/chat'
    | '/dashboard/$id/custom-agents'
    | '/dashboard/$id/settings'
    | '/dashboard/$id/automations/$amId/configuration'
    | '/dashboard/$id/automations/$amId/executions'
    | '/dashboard/$id/automations/$amId/triggers'
    | '/dashboard/$id/custom-agents/$agentId/instructions'
    | '/dashboard/$id/custom-agents/$agentId/knowledge'
    | '/dashboard/$id/custom-agents/$agentId/tools'
    | '/dashboard/$id/custom-agents/$agentId/webhook'
    | '/dashboard/$id/custom-agents/$agentId'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/convex-dashboard'
    | '/dashboard'
    | '/docs'
    | '/_auth/log-in'
    | '/_auth/sign-up'
    | '/dashboard/$id'
    | '/dashboard/create-organization'
    | '/dashboard/'
    | '/dashboard/$id/_knowledge'
    | '/dashboard/$id/approvals'
    | '/dashboard/$id/automations'
    | '/dashboard/$id/chat'
    | '/dashboard/$id/conversations'
    | '/dashboard/$id/custom-agents'
    | '/dashboard/$id/settings'
    | '/dashboard/$id/'
    | '/dashboard/$id/_knowledge/customers'
    | '/dashboard/$id/_knowledge/documents'
    | '/dashboard/$id/_knowledge/products'
    | '/dashboard/$id/_knowledge/tone-of-voice'
    | '/dashboard/$id/_knowledge/vendors'
    | '/dashboard/$id/_knowledge/websites'
    | '/dashboard/$id/approvals/$status'
    | '/dashboard/$id/automations/$amId'
    | '/dashboard/$id/chat/$threadId'
    | '/dashboard/$id/conversations/$status'
    | '/dashboard/$id/custom-agents/$agentId'
    | '/dashboard/$id/settings/account'
    | '/dashboard/$id/settings/api-keys'
    | '/dashboard/$id/settings/branding'
    | '/dashboard/$id/settings/custom-agents'
    | '/dashboard/$id/settings/integrations'
    | '/dashboard/$id/settings/logs'
    | '/dashboard/$id/settings/organization'
    | '/dashboard/$id/settings/teams'
    | '/dashboard/$id/automations/'
    | '/dashboard/$id/chat/'
    | '/dashboard/$id/custom-agents/'
    | '/dashboard/$id/settings/'
    | '/dashboard/$id/automations/$amId/configuration'
    | '/dashboard/$id/automations/$amId/executions'
    | '/dashboard/$id/automations/$amId/triggers'
    | '/dashboard/$id/custom-agents/$agentId/instructions'
    | '/dashboard/$id/custom-agents/$agentId/knowledge'
    | '/dashboard/$id/custom-agents/$agentId/tools'
    | '/dashboard/$id/custom-agents/$agentId/webhook'
    | '/dashboard/$id/custom-agents/$agentId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  ConvexDashboardRoute: typeof ConvexDashboardRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  DocsRoute: typeof DocsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/convex-dashboard': {
      id: '/convex-dashboard'
      path: '/convex-dashboard'
      fullPath: '/convex-dashboard'
      preLoaderRoute: typeof ConvexDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/create-organization': {
      id: '/dashboard/create-organization'
      path: '/create-organization'
      fullPath: '/dashboard/create-organization'
      preLoaderRoute: typeof DashboardCreateOrganizationRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/$id': {
      id: '/dashboard/$id'
      path: '/$id'
      fullPath: '/dashboard/$id'
      preLoaderRoute: typeof DashboardIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_auth/sign-up': {
      id: '/_auth/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/log-in': {
      id: '/_auth/log-in'
      path: '/log-in'
      fullPath: '/log-in'
      preLoaderRoute: typeof AuthLogInRouteImport
      parentRoute: typeof AuthRoute
    }
    '/dashboard/$id/': {
      id: '/dashboard/$id/'
      path: '/'
      fullPath: '/dashboard/$id/'
      preLoaderRoute: typeof DashboardIdIndexRouteImport
      parentRoute: typeof DashboardIdRoute
    }
    '/dashboard/$id/settings': {
      id: '/dashboard/$id/settings'
      path: '/settings'
      fullPath: '/dashboard/$id/settings'
      preLoaderRoute: typeof DashboardIdSettingsRouteImport
      parentRoute: typeof DashboardIdRoute
    }
    '/dashboard/$id/custom-agents': {
      id: '/dashboard/$id/custom-agents'
      path: '/custom-agents'
      fullPath: '/dashboard/$id/custom-agents'
      preLoaderRoute: typeof DashboardIdCustomAgentsRouteImport
      parentRoute: typeof DashboardIdRoute
    }
    '/dashboard/$id/conversations': {
      id: '/dashboard/$id/conversations'
      path: '/conversations'
      fullPath: '/dashboard/$id/conversations'
      preLoaderRoute: typeof DashboardIdConversationsRouteImport
      parentRoute: typeof DashboardIdRoute
    }
    '/dashboard/$id/chat': {
      id: '/dashboard/$id/chat'
      path: '/chat'
      fullPath: '/dashboard/$id/chat'
      preLoaderRoute: typeof DashboardIdChatRouteImport
      parentRoute: typeof DashboardIdRoute
    }
    '/dashboard/$id/automations': {
      id: '/dashboard/$id/automations'
      path: '/automations'
      fullPath: '/dashboard/$id/automations'
      preLoaderRoute: typeof DashboardIdAutomationsRouteImport
      parentRoute: typeof DashboardIdRoute
    }
    '/dashboard/$id/approvals': {
      id: '/dashboard/$id/approvals'
      path: '/approvals'
      fullPath: '/dashboard/$id/approvals'
      preLoaderRoute: typeof DashboardIdApprovalsRouteImport
      parentRoute: typeof DashboardIdRoute
    }
    '/dashboard/$id/_knowledge': {
      id: '/dashboard/$id/_knowledge'
      path: ''
      fullPath: '/dashboard/$id'
      preLoaderRoute: typeof DashboardIdKnowledgeRouteImport
      parentRoute: typeof DashboardIdRoute
    }
    '/dashboard/$id/settings/': {
      id: '/dashboard/$id/settings/'
      path: '/'
      fullPath: '/dashboard/$id/settings/'
      preLoaderRoute: typeof DashboardIdSettingsIndexRouteImport
      parentRoute: typeof DashboardIdSettingsRoute
    }
    '/dashboard/$id/custom-agents/': {
      id: '/dashboard/$id/custom-agents/'
      path: '/'
      fullPath: '/dashboard/$id/custom-agents/'
      preLoaderRoute: typeof DashboardIdCustomAgentsIndexRouteImport
      parentRoute: typeof DashboardIdCustomAgentsRoute
    }
    '/dashboard/$id/chat/': {
      id: '/dashboard/$id/chat/'
      path: '/'
      fullPath: '/dashboard/$id/chat/'
      preLoaderRoute: typeof DashboardIdChatIndexRouteImport
      parentRoute: typeof DashboardIdChatRoute
    }
    '/dashboard/$id/automations/': {
      id: '/dashboard/$id/automations/'
      path: '/'
      fullPath: '/dashboard/$id/automations/'
      preLoaderRoute: typeof DashboardIdAutomationsIndexRouteImport
      parentRoute: typeof DashboardIdAutomationsRoute
    }
    '/dashboard/$id/settings/teams': {
      id: '/dashboard/$id/settings/teams'
      path: '/teams'
      fullPath: '/dashboard/$id/settings/teams'
      preLoaderRoute: typeof DashboardIdSettingsTeamsRouteImport
      parentRoute: typeof DashboardIdSettingsRoute
    }
    '/dashboard/$id/settings/organization': {
      id: '/dashboard/$id/settings/organization'
      path: '/organization'
      fullPath: '/dashboard/$id/settings/organization'
      preLoaderRoute: typeof DashboardIdSettingsOrganizationRouteImport
      parentRoute: typeof DashboardIdSettingsRoute
    }
    '/dashboard/$id/settings/logs': {
      id: '/dashboard/$id/settings/logs'
      path: '/logs'
      fullPath: '/dashboard/$id/settings/logs'
      preLoaderRoute: typeof DashboardIdSettingsLogsRouteImport
      parentRoute: typeof DashboardIdSettingsRoute
    }
    '/dashboard/$id/settings/integrations': {
      id: '/dashboard/$id/settings/integrations'
      path: '/integrations'
      fullPath: '/dashboard/$id/settings/integrations'
      preLoaderRoute: typeof DashboardIdSettingsIntegrationsRouteImport
      parentRoute: typeof DashboardIdSettingsRoute
    }
    '/dashboard/$id/settings/custom-agents': {
      id: '/dashboard/$id/settings/custom-agents'
      path: '/custom-agents'
      fullPath: '/dashboard/$id/settings/custom-agents'
      preLoaderRoute: typeof DashboardIdSettingsCustomAgentsRouteImport
      parentRoute: typeof DashboardIdSettingsRoute
    }
    '/dashboard/$id/settings/branding': {
      id: '/dashboard/$id/settings/branding'
      path: '/branding'
      fullPath: '/dashboard/$id/settings/branding'
      preLoaderRoute: typeof DashboardIdSettingsBrandingRouteImport
      parentRoute: typeof DashboardIdSettingsRoute
    }
    '/dashboard/$id/settings/api-keys': {
      id: '/dashboard/$id/settings/api-keys'
      path: '/api-keys'
      fullPath: '/dashboard/$id/settings/api-keys'
      preLoaderRoute: typeof DashboardIdSettingsApiKeysRouteImport
      parentRoute: typeof DashboardIdSettingsRoute
    }
    '/dashboard/$id/settings/account': {
      id: '/dashboard/$id/settings/account'
      path: '/account'
      fullPath: '/dashboard/$id/settings/account'
      preLoaderRoute: typeof DashboardIdSettingsAccountRouteImport
      parentRoute: typeof DashboardIdSettingsRoute
    }
    '/dashboard/$id/custom-agents/$agentId': {
      id: '/dashboard/$id/custom-agents/$agentId'
      path: '/$agentId'
      fullPath: '/dashboard/$id/custom-agents/$agentId'
      preLoaderRoute: typeof DashboardIdCustomAgentsAgentIdRouteImport
      parentRoute: typeof DashboardIdCustomAgentsRoute
    }
    '/dashboard/$id/conversations/$status': {
      id: '/dashboard/$id/conversations/$status'
      path: '/$status'
      fullPath: '/dashboard/$id/conversations/$status'
      preLoaderRoute: typeof DashboardIdConversationsStatusRouteImport
      parentRoute: typeof DashboardIdConversationsRoute
    }
    '/dashboard/$id/chat/$threadId': {
      id: '/dashboard/$id/chat/$threadId'
      path: '/$threadId'
      fullPath: '/dashboard/$id/chat/$threadId'
      preLoaderRoute: typeof DashboardIdChatThreadIdRouteImport
      parentRoute: typeof DashboardIdChatRoute
    }
    '/dashboard/$id/automations/$amId': {
      id: '/dashboard/$id/automations/$amId'
      path: '/$amId'
      fullPath: '/dashboard/$id/automations/$amId'
      preLoaderRoute: typeof DashboardIdAutomationsAmIdRouteImport
      parentRoute: typeof DashboardIdAutomationsRoute
    }
    '/dashboard/$id/approvals/$status': {
      id: '/dashboard/$id/approvals/$status'
      path: '/$status'
      fullPath: '/dashboard/$id/approvals/$status'
      preLoaderRoute: typeof DashboardIdApprovalsStatusRouteImport
      parentRoute: typeof DashboardIdApprovalsRoute
    }
    '/dashboard/$id/_knowledge/websites': {
      id: '/dashboard/$id/_knowledge/websites'
      path: '/websites'
      fullPath: '/dashboard/$id/websites'
      preLoaderRoute: typeof DashboardIdKnowledgeWebsitesRouteImport
      parentRoute: typeof DashboardIdKnowledgeRoute
    }
    '/dashboard/$id/_knowledge/vendors': {
      id: '/dashboard/$id/_knowledge/vendors'
      path: '/vendors'
      fullPath: '/dashboard/$id/vendors'
      preLoaderRoute: typeof DashboardIdKnowledgeVendorsRouteImport
      parentRoute: typeof DashboardIdKnowledgeRoute
    }
    '/dashboard/$id/_knowledge/tone-of-voice': {
      id: '/dashboard/$id/_knowledge/tone-of-voice'
      path: '/tone-of-voice'
      fullPath: '/dashboard/$id/tone-of-voice'
      preLoaderRoute: typeof DashboardIdKnowledgeToneOfVoiceRouteImport
      parentRoute: typeof DashboardIdKnowledgeRoute
    }
    '/dashboard/$id/_knowledge/products': {
      id: '/dashboard/$id/_knowledge/products'
      path: '/products'
      fullPath: '/dashboard/$id/products'
      preLoaderRoute: typeof DashboardIdKnowledgeProductsRouteImport
      parentRoute: typeof DashboardIdKnowledgeRoute
    }
    '/dashboard/$id/_knowledge/documents': {
      id: '/dashboard/$id/_knowledge/documents'
      path: '/documents'
      fullPath: '/dashboard/$id/documents'
      preLoaderRoute: typeof DashboardIdKnowledgeDocumentsRouteImport
      parentRoute: typeof DashboardIdKnowledgeRoute
    }
    '/dashboard/$id/_knowledge/customers': {
      id: '/dashboard/$id/_knowledge/customers'
      path: '/customers'
      fullPath: '/dashboard/$id/customers'
      preLoaderRoute: typeof DashboardIdKnowledgeCustomersRouteImport
      parentRoute: typeof DashboardIdKnowledgeRoute
    }
    '/dashboard/$id/custom-agents/$agentId/': {
      id: '/dashboard/$id/custom-agents/$agentId/'
      path: '/'
      fullPath: '/dashboard/$id/custom-agents/$agentId/'
      preLoaderRoute: typeof DashboardIdCustomAgentsAgentIdIndexRouteImport
      parentRoute: typeof DashboardIdCustomAgentsAgentIdRoute
    }
    '/dashboard/$id/custom-agents/$agentId/webhook': {
      id: '/dashboard/$id/custom-agents/$agentId/webhook'
      path: '/webhook'
      fullPath: '/dashboard/$id/custom-agents/$agentId/webhook'
      preLoaderRoute: typeof DashboardIdCustomAgentsAgentIdWebhookRouteImport
      parentRoute: typeof DashboardIdCustomAgentsAgentIdRoute
    }
    '/dashboard/$id/custom-agents/$agentId/tools': {
      id: '/dashboard/$id/custom-agents/$agentId/tools'
      path: '/tools'
      fullPath: '/dashboard/$id/custom-agents/$agentId/tools'
      preLoaderRoute: typeof DashboardIdCustomAgentsAgentIdToolsRouteImport
      parentRoute: typeof DashboardIdCustomAgentsAgentIdRoute
    }
    '/dashboard/$id/custom-agents/$agentId/knowledge': {
      id: '/dashboard/$id/custom-agents/$agentId/knowledge'
      path: '/knowledge'
      fullPath: '/dashboard/$id/custom-agents/$agentId/knowledge'
      preLoaderRoute: typeof DashboardIdCustomAgentsAgentIdKnowledgeRouteImport
      parentRoute: typeof DashboardIdCustomAgentsAgentIdRoute
    }
    '/dashboard/$id/custom-agents/$agentId/instructions': {
      id: '/dashboard/$id/custom-agents/$agentId/instructions'
      path: '/instructions'
      fullPath: '/dashboard/$id/custom-agents/$agentId/instructions'
      preLoaderRoute: typeof DashboardIdCustomAgentsAgentIdInstructionsRouteImport
      parentRoute: typeof DashboardIdCustomAgentsAgentIdRoute
    }
    '/dashboard/$id/automations/$amId/triggers': {
      id: '/dashboard/$id/automations/$amId/triggers'
      path: '/triggers'
      fullPath: '/dashboard/$id/automations/$amId/triggers'
      preLoaderRoute: typeof DashboardIdAutomationsAmIdTriggersRouteImport
      parentRoute: typeof DashboardIdAutomationsAmIdRoute
    }
    '/dashboard/$id/automations/$amId/executions': {
      id: '/dashboard/$id/automations/$amId/executions'
      path: '/executions'
      fullPath: '/dashboard/$id/automations/$amId/executions'
      preLoaderRoute: typeof DashboardIdAutomationsAmIdExecutionsRouteImport
      parentRoute: typeof DashboardIdAutomationsAmIdRoute
    }
    '/dashboard/$id/automations/$amId/configuration': {
      id: '/dashboard/$id/automations/$amId/configuration'
      path: '/configuration'
      fullPath: '/dashboard/$id/automations/$amId/configuration'
      preLoaderRoute: typeof DashboardIdAutomationsAmIdConfigurationRouteImport
      parentRoute: typeof DashboardIdAutomationsAmIdRoute
    }
  }
}

interface AuthRouteChildren {
  AuthLogInRoute: typeof AuthLogInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLogInRoute: AuthLogInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface DashboardIdKnowledgeRouteChildren {
  DashboardIdKnowledgeCustomersRoute: typeof DashboardIdKnowledgeCustomersRoute
  DashboardIdKnowledgeDocumentsRoute: typeof DashboardIdKnowledgeDocumentsRoute
  DashboardIdKnowledgeProductsRoute: typeof DashboardIdKnowledgeProductsRoute
  DashboardIdKnowledgeToneOfVoiceRoute: typeof DashboardIdKnowledgeToneOfVoiceRoute
  DashboardIdKnowledgeVendorsRoute: typeof DashboardIdKnowledgeVendorsRoute
  DashboardIdKnowledgeWebsitesRoute: typeof DashboardIdKnowledgeWebsitesRoute
}

const DashboardIdKnowledgeRouteChildren: DashboardIdKnowledgeRouteChildren = {
  DashboardIdKnowledgeCustomersRoute: DashboardIdKnowledgeCustomersRoute,
  DashboardIdKnowledgeDocumentsRoute: DashboardIdKnowledgeDocumentsRoute,
  DashboardIdKnowledgeProductsRoute: DashboardIdKnowledgeProductsRoute,
  DashboardIdKnowledgeToneOfVoiceRoute: DashboardIdKnowledgeToneOfVoiceRoute,
  DashboardIdKnowledgeVendorsRoute: DashboardIdKnowledgeVendorsRoute,
  DashboardIdKnowledgeWebsitesRoute: DashboardIdKnowledgeWebsitesRoute,
}

const DashboardIdKnowledgeRouteWithChildren =
  DashboardIdKnowledgeRoute._addFileChildren(DashboardIdKnowledgeRouteChildren)

interface DashboardIdApprovalsRouteChildren {
  DashboardIdApprovalsStatusRoute: typeof DashboardIdApprovalsStatusRoute
}

const DashboardIdApprovalsRouteChildren: DashboardIdApprovalsRouteChildren = {
  DashboardIdApprovalsStatusRoute: DashboardIdApprovalsStatusRoute,
}

const DashboardIdApprovalsRouteWithChildren =
  DashboardIdApprovalsRoute._addFileChildren(DashboardIdApprovalsRouteChildren)

interface DashboardIdAutomationsAmIdRouteChildren {
  DashboardIdAutomationsAmIdConfigurationRoute: typeof DashboardIdAutomationsAmIdConfigurationRoute
  DashboardIdAutomationsAmIdExecutionsRoute: typeof DashboardIdAutomationsAmIdExecutionsRoute
  DashboardIdAutomationsAmIdTriggersRoute: typeof DashboardIdAutomationsAmIdTriggersRoute
}

const DashboardIdAutomationsAmIdRouteChildren: DashboardIdAutomationsAmIdRouteChildren =
  {
    DashboardIdAutomationsAmIdConfigurationRoute:
      DashboardIdAutomationsAmIdConfigurationRoute,
    DashboardIdAutomationsAmIdExecutionsRoute:
      DashboardIdAutomationsAmIdExecutionsRoute,
    DashboardIdAutomationsAmIdTriggersRoute:
      DashboardIdAutomationsAmIdTriggersRoute,
  }

const DashboardIdAutomationsAmIdRouteWithChildren =
  DashboardIdAutomationsAmIdRoute._addFileChildren(
    DashboardIdAutomationsAmIdRouteChildren,
  )

interface DashboardIdAutomationsRouteChildren {
  DashboardIdAutomationsAmIdRoute: typeof DashboardIdAutomationsAmIdRouteWithChildren
  DashboardIdAutomationsIndexRoute: typeof DashboardIdAutomationsIndexRoute
}

const DashboardIdAutomationsRouteChildren: DashboardIdAutomationsRouteChildren =
  {
    DashboardIdAutomationsAmIdRoute:
      DashboardIdAutomationsAmIdRouteWithChildren,
    DashboardIdAutomationsIndexRoute: DashboardIdAutomationsIndexRoute,
  }

const DashboardIdAutomationsRouteWithChildren =
  DashboardIdAutomationsRoute._addFileChildren(
    DashboardIdAutomationsRouteChildren,
  )

interface DashboardIdChatRouteChildren {
  DashboardIdChatThreadIdRoute: typeof DashboardIdChatThreadIdRoute
  DashboardIdChatIndexRoute: typeof DashboardIdChatIndexRoute
}

const DashboardIdChatRouteChildren: DashboardIdChatRouteChildren = {
  DashboardIdChatThreadIdRoute: DashboardIdChatThreadIdRoute,
  DashboardIdChatIndexRoute: DashboardIdChatIndexRoute,
}

const DashboardIdChatRouteWithChildren = DashboardIdChatRoute._addFileChildren(
  DashboardIdChatRouteChildren,
)

interface DashboardIdConversationsRouteChildren {
  DashboardIdConversationsStatusRoute: typeof DashboardIdConversationsStatusRoute
}

const DashboardIdConversationsRouteChildren: DashboardIdConversationsRouteChildren =
  {
    DashboardIdConversationsStatusRoute: DashboardIdConversationsStatusRoute,
  }

const DashboardIdConversationsRouteWithChildren =
  DashboardIdConversationsRoute._addFileChildren(
    DashboardIdConversationsRouteChildren,
  )

interface DashboardIdCustomAgentsAgentIdRouteChildren {
  DashboardIdCustomAgentsAgentIdInstructionsRoute: typeof DashboardIdCustomAgentsAgentIdInstructionsRoute
  DashboardIdCustomAgentsAgentIdKnowledgeRoute: typeof DashboardIdCustomAgentsAgentIdKnowledgeRoute
  DashboardIdCustomAgentsAgentIdToolsRoute: typeof DashboardIdCustomAgentsAgentIdToolsRoute
  DashboardIdCustomAgentsAgentIdWebhookRoute: typeof DashboardIdCustomAgentsAgentIdWebhookRoute
  DashboardIdCustomAgentsAgentIdIndexRoute: typeof DashboardIdCustomAgentsAgentIdIndexRoute
}

const DashboardIdCustomAgentsAgentIdRouteChildren: DashboardIdCustomAgentsAgentIdRouteChildren =
  {
    DashboardIdCustomAgentsAgentIdInstructionsRoute:
      DashboardIdCustomAgentsAgentIdInstructionsRoute,
    DashboardIdCustomAgentsAgentIdKnowledgeRoute:
      DashboardIdCustomAgentsAgentIdKnowledgeRoute,
    DashboardIdCustomAgentsAgentIdToolsRoute:
      DashboardIdCustomAgentsAgentIdToolsRoute,
    DashboardIdCustomAgentsAgentIdWebhookRoute:
      DashboardIdCustomAgentsAgentIdWebhookRoute,
    DashboardIdCustomAgentsAgentIdIndexRoute:
      DashboardIdCustomAgentsAgentIdIndexRoute,
  }

const DashboardIdCustomAgentsAgentIdRouteWithChildren =
  DashboardIdCustomAgentsAgentIdRoute._addFileChildren(
    DashboardIdCustomAgentsAgentIdRouteChildren,
  )

interface DashboardIdCustomAgentsRouteChildren {
  DashboardIdCustomAgentsAgentIdRoute: typeof DashboardIdCustomAgentsAgentIdRouteWithChildren
  DashboardIdCustomAgentsIndexRoute: typeof DashboardIdCustomAgentsIndexRoute
}

const DashboardIdCustomAgentsRouteChildren: DashboardIdCustomAgentsRouteChildren =
  {
    DashboardIdCustomAgentsAgentIdRoute:
      DashboardIdCustomAgentsAgentIdRouteWithChildren,
    DashboardIdCustomAgentsIndexRoute: DashboardIdCustomAgentsIndexRoute,
  }

const DashboardIdCustomAgentsRouteWithChildren =
  DashboardIdCustomAgentsRoute._addFileChildren(
    DashboardIdCustomAgentsRouteChildren,
  )

interface DashboardIdSettingsRouteChildren {
  DashboardIdSettingsAccountRoute: typeof DashboardIdSettingsAccountRoute
  DashboardIdSettingsApiKeysRoute: typeof DashboardIdSettingsApiKeysRoute
  DashboardIdSettingsBrandingRoute: typeof DashboardIdSettingsBrandingRoute
  DashboardIdSettingsCustomAgentsRoute: typeof DashboardIdSettingsCustomAgentsRoute
  DashboardIdSettingsIntegrationsRoute: typeof DashboardIdSettingsIntegrationsRoute
  DashboardIdSettingsLogsRoute: typeof DashboardIdSettingsLogsRoute
  DashboardIdSettingsOrganizationRoute: typeof DashboardIdSettingsOrganizationRoute
  DashboardIdSettingsTeamsRoute: typeof DashboardIdSettingsTeamsRoute
  DashboardIdSettingsIndexRoute: typeof DashboardIdSettingsIndexRoute
}

const DashboardIdSettingsRouteChildren: DashboardIdSettingsRouteChildren = {
  DashboardIdSettingsAccountRoute: DashboardIdSettingsAccountRoute,
  DashboardIdSettingsApiKeysRoute: DashboardIdSettingsApiKeysRoute,
  DashboardIdSettingsBrandingRoute: DashboardIdSettingsBrandingRoute,
  DashboardIdSettingsCustomAgentsRoute: DashboardIdSettingsCustomAgentsRoute,
  DashboardIdSettingsIntegrationsRoute: DashboardIdSettingsIntegrationsRoute,
  DashboardIdSettingsLogsRoute: DashboardIdSettingsLogsRoute,
  DashboardIdSettingsOrganizationRoute: DashboardIdSettingsOrganizationRoute,
  DashboardIdSettingsTeamsRoute: DashboardIdSettingsTeamsRoute,
  DashboardIdSettingsIndexRoute: DashboardIdSettingsIndexRoute,
}

const DashboardIdSettingsRouteWithChildren =
  DashboardIdSettingsRoute._addFileChildren(DashboardIdSettingsRouteChildren)

interface DashboardIdRouteChildren {
  DashboardIdKnowledgeRoute: typeof DashboardIdKnowledgeRouteWithChildren
  DashboardIdApprovalsRoute: typeof DashboardIdApprovalsRouteWithChildren
  DashboardIdAutomationsRoute: typeof DashboardIdAutomationsRouteWithChildren
  DashboardIdChatRoute: typeof DashboardIdChatRouteWithChildren
  DashboardIdConversationsRoute: typeof DashboardIdConversationsRouteWithChildren
  DashboardIdCustomAgentsRoute: typeof DashboardIdCustomAgentsRouteWithChildren
  DashboardIdSettingsRoute: typeof DashboardIdSettingsRouteWithChildren
  DashboardIdIndexRoute: typeof DashboardIdIndexRoute
}

const DashboardIdRouteChildren: DashboardIdRouteChildren = {
  DashboardIdKnowledgeRoute: DashboardIdKnowledgeRouteWithChildren,
  DashboardIdApprovalsRoute: DashboardIdApprovalsRouteWithChildren,
  DashboardIdAutomationsRoute: DashboardIdAutomationsRouteWithChildren,
  DashboardIdChatRoute: DashboardIdChatRouteWithChildren,
  DashboardIdConversationsRoute: DashboardIdConversationsRouteWithChildren,
  DashboardIdCustomAgentsRoute: DashboardIdCustomAgentsRouteWithChildren,
  DashboardIdSettingsRoute: DashboardIdSettingsRouteWithChildren,
  DashboardIdIndexRoute: DashboardIdIndexRoute,
}

const DashboardIdRouteWithChildren = DashboardIdRoute._addFileChildren(
  DashboardIdRouteChildren,
)

interface DashboardRouteChildren {
  DashboardIdRoute: typeof DashboardIdRouteWithChildren
  DashboardCreateOrganizationRoute: typeof DashboardCreateOrganizationRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardIdRoute: DashboardIdRouteWithChildren,
  DashboardCreateOrganizationRoute: DashboardCreateOrganizationRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  ConvexDashboardRoute: ConvexDashboardRoute,
  DashboardRoute: DashboardRouteWithChildren,
  DocsRoute: DocsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
