/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ConvexDashboardRouteImport } from './routes/convex-dashboard'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardCreateOrganizationRouteImport } from './routes/dashboard/create-organization'
import { Route as DashboardIdRouteImport } from './routes/dashboard/$id'
import { Route as AuthSignUpRouteImport } from './routes/_auth/sign-up'
import { Route as AuthLogInRouteImport } from './routes/_auth/log-in'
import { Route as DashboardIdWebsitesRouteImport } from './routes/dashboard/$id/websites'
import { Route as DashboardIdVendorsRouteImport } from './routes/dashboard/$id/vendors'
import { Route as DashboardIdToneOfVoiceRouteImport } from './routes/dashboard/$id/tone-of-voice'
import { Route as DashboardIdSettingsRouteImport } from './routes/dashboard/$id/settings'
import { Route as DashboardIdProductsRouteImport } from './routes/dashboard/$id/products'
import { Route as DashboardIdDocumentsRouteImport } from './routes/dashboard/$id/documents'
import { Route as DashboardIdCustomersRouteImport } from './routes/dashboard/$id/customers'
import { Route as DashboardIdConversationsRouteImport } from './routes/dashboard/$id/conversations'
import { Route as DashboardIdChatRouteImport } from './routes/dashboard/$id/chat'
import { Route as DashboardIdAutomationsRouteImport } from './routes/dashboard/$id/automations'
import { Route as DashboardIdApprovalsRouteImport } from './routes/dashboard/$id/approvals'
import { Route as DashboardIdSettingsOrganizationRouteImport } from './routes/dashboard/$id/settings/organization'
import { Route as DashboardIdSettingsLogsRouteImport } from './routes/dashboard/$id/settings/logs'
import { Route as DashboardIdSettingsIntegrationsRouteImport } from './routes/dashboard/$id/settings/integrations'
import { Route as DashboardIdSettingsAccountRouteImport } from './routes/dashboard/$id/settings/account'
import { Route as DashboardIdConversationsStatusRouteImport } from './routes/dashboard/$id/conversations/$status'
import { Route as DashboardIdChatThreadIdRouteImport } from './routes/dashboard/$id/chat/$threadId'
import { Route as DashboardIdAutomationsAmIdRouteImport } from './routes/dashboard/$id/automations/$amId'
import { Route as DashboardIdApprovalsStatusRouteImport } from './routes/dashboard/$id/approvals/$status'
import { Route as DashboardIdAutomationsAmIdExecutionsRouteImport } from './routes/dashboard/$id/automations/$amId/executions'
import { Route as DashboardIdAutomationsAmIdConfigurationRouteImport } from './routes/dashboard/$id/automations/$amId/configuration'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ConvexDashboardRoute = ConvexDashboardRouteImport.update({
  id: '/convex-dashboard',
  path: '/convex-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardCreateOrganizationRoute =
  DashboardCreateOrganizationRouteImport.update({
    id: '/create-organization',
    path: '/create-organization',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardIdRoute = DashboardIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DashboardRoute,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLogInRoute = AuthLogInRouteImport.update({
  id: '/log-in',
  path: '/log-in',
  getParentRoute: () => AuthRoute,
} as any)
const DashboardIdWebsitesRoute = DashboardIdWebsitesRouteImport.update({
  id: '/websites',
  path: '/websites',
  getParentRoute: () => DashboardIdRoute,
} as any)
const DashboardIdVendorsRoute = DashboardIdVendorsRouteImport.update({
  id: '/vendors',
  path: '/vendors',
  getParentRoute: () => DashboardIdRoute,
} as any)
const DashboardIdToneOfVoiceRoute = DashboardIdToneOfVoiceRouteImport.update({
  id: '/tone-of-voice',
  path: '/tone-of-voice',
  getParentRoute: () => DashboardIdRoute,
} as any)
const DashboardIdSettingsRoute = DashboardIdSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardIdRoute,
} as any)
const DashboardIdProductsRoute = DashboardIdProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => DashboardIdRoute,
} as any)
const DashboardIdDocumentsRoute = DashboardIdDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => DashboardIdRoute,
} as any)
const DashboardIdCustomersRoute = DashboardIdCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => DashboardIdRoute,
} as any)
const DashboardIdConversationsRoute =
  DashboardIdConversationsRouteImport.update({
    id: '/conversations',
    path: '/conversations',
    getParentRoute: () => DashboardIdRoute,
  } as any)
const DashboardIdChatRoute = DashboardIdChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => DashboardIdRoute,
} as any)
const DashboardIdAutomationsRoute = DashboardIdAutomationsRouteImport.update({
  id: '/automations',
  path: '/automations',
  getParentRoute: () => DashboardIdRoute,
} as any)
const DashboardIdApprovalsRoute = DashboardIdApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => DashboardIdRoute,
} as any)
const DashboardIdSettingsOrganizationRoute =
  DashboardIdSettingsOrganizationRouteImport.update({
    id: '/organization',
    path: '/organization',
    getParentRoute: () => DashboardIdSettingsRoute,
  } as any)
const DashboardIdSettingsLogsRoute = DashboardIdSettingsLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => DashboardIdSettingsRoute,
} as any)
const DashboardIdSettingsIntegrationsRoute =
  DashboardIdSettingsIntegrationsRouteImport.update({
    id: '/integrations',
    path: '/integrations',
    getParentRoute: () => DashboardIdSettingsRoute,
  } as any)
const DashboardIdSettingsAccountRoute =
  DashboardIdSettingsAccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => DashboardIdSettingsRoute,
  } as any)
const DashboardIdConversationsStatusRoute =
  DashboardIdConversationsStatusRouteImport.update({
    id: '/$status',
    path: '/$status',
    getParentRoute: () => DashboardIdConversationsRoute,
  } as any)
const DashboardIdChatThreadIdRoute = DashboardIdChatThreadIdRouteImport.update({
  id: '/$threadId',
  path: '/$threadId',
  getParentRoute: () => DashboardIdChatRoute,
} as any)
const DashboardIdAutomationsAmIdRoute =
  DashboardIdAutomationsAmIdRouteImport.update({
    id: '/$amId',
    path: '/$amId',
    getParentRoute: () => DashboardIdAutomationsRoute,
  } as any)
const DashboardIdApprovalsStatusRoute =
  DashboardIdApprovalsStatusRouteImport.update({
    id: '/$status',
    path: '/$status',
    getParentRoute: () => DashboardIdApprovalsRoute,
  } as any)
const DashboardIdAutomationsAmIdExecutionsRoute =
  DashboardIdAutomationsAmIdExecutionsRouteImport.update({
    id: '/executions',
    path: '/executions',
    getParentRoute: () => DashboardIdAutomationsAmIdRoute,
  } as any)
const DashboardIdAutomationsAmIdConfigurationRoute =
  DashboardIdAutomationsAmIdConfigurationRouteImport.update({
    id: '/configuration',
    path: '/configuration',
    getParentRoute: () => DashboardIdAutomationsAmIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/convex-dashboard': typeof ConvexDashboardRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/log-in': typeof AuthLogInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/dashboard/$id': typeof DashboardIdRouteWithChildren
  '/dashboard/create-organization': typeof DashboardCreateOrganizationRoute
  '/dashboard/$id/approvals': typeof DashboardIdApprovalsRouteWithChildren
  '/dashboard/$id/automations': typeof DashboardIdAutomationsRouteWithChildren
  '/dashboard/$id/chat': typeof DashboardIdChatRouteWithChildren
  '/dashboard/$id/conversations': typeof DashboardIdConversationsRouteWithChildren
  '/dashboard/$id/customers': typeof DashboardIdCustomersRoute
  '/dashboard/$id/documents': typeof DashboardIdDocumentsRoute
  '/dashboard/$id/products': typeof DashboardIdProductsRoute
  '/dashboard/$id/settings': typeof DashboardIdSettingsRouteWithChildren
  '/dashboard/$id/tone-of-voice': typeof DashboardIdToneOfVoiceRoute
  '/dashboard/$id/vendors': typeof DashboardIdVendorsRoute
  '/dashboard/$id/websites': typeof DashboardIdWebsitesRoute
  '/dashboard/$id/approvals/$status': typeof DashboardIdApprovalsStatusRoute
  '/dashboard/$id/automations/$amId': typeof DashboardIdAutomationsAmIdRouteWithChildren
  '/dashboard/$id/chat/$threadId': typeof DashboardIdChatThreadIdRoute
  '/dashboard/$id/conversations/$status': typeof DashboardIdConversationsStatusRoute
  '/dashboard/$id/settings/account': typeof DashboardIdSettingsAccountRoute
  '/dashboard/$id/settings/integrations': typeof DashboardIdSettingsIntegrationsRoute
  '/dashboard/$id/settings/logs': typeof DashboardIdSettingsLogsRoute
  '/dashboard/$id/settings/organization': typeof DashboardIdSettingsOrganizationRoute
  '/dashboard/$id/automations/$amId/configuration': typeof DashboardIdAutomationsAmIdConfigurationRoute
  '/dashboard/$id/automations/$amId/executions': typeof DashboardIdAutomationsAmIdExecutionsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/convex-dashboard': typeof ConvexDashboardRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/log-in': typeof AuthLogInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/dashboard/$id': typeof DashboardIdRouteWithChildren
  '/dashboard/create-organization': typeof DashboardCreateOrganizationRoute
  '/dashboard/$id/approvals': typeof DashboardIdApprovalsRouteWithChildren
  '/dashboard/$id/automations': typeof DashboardIdAutomationsRouteWithChildren
  '/dashboard/$id/chat': typeof DashboardIdChatRouteWithChildren
  '/dashboard/$id/conversations': typeof DashboardIdConversationsRouteWithChildren
  '/dashboard/$id/customers': typeof DashboardIdCustomersRoute
  '/dashboard/$id/documents': typeof DashboardIdDocumentsRoute
  '/dashboard/$id/products': typeof DashboardIdProductsRoute
  '/dashboard/$id/settings': typeof DashboardIdSettingsRouteWithChildren
  '/dashboard/$id/tone-of-voice': typeof DashboardIdToneOfVoiceRoute
  '/dashboard/$id/vendors': typeof DashboardIdVendorsRoute
  '/dashboard/$id/websites': typeof DashboardIdWebsitesRoute
  '/dashboard/$id/approvals/$status': typeof DashboardIdApprovalsStatusRoute
  '/dashboard/$id/automations/$amId': typeof DashboardIdAutomationsAmIdRouteWithChildren
  '/dashboard/$id/chat/$threadId': typeof DashboardIdChatThreadIdRoute
  '/dashboard/$id/conversations/$status': typeof DashboardIdConversationsStatusRoute
  '/dashboard/$id/settings/account': typeof DashboardIdSettingsAccountRoute
  '/dashboard/$id/settings/integrations': typeof DashboardIdSettingsIntegrationsRoute
  '/dashboard/$id/settings/logs': typeof DashboardIdSettingsLogsRoute
  '/dashboard/$id/settings/organization': typeof DashboardIdSettingsOrganizationRoute
  '/dashboard/$id/automations/$amId/configuration': typeof DashboardIdAutomationsAmIdConfigurationRoute
  '/dashboard/$id/automations/$amId/executions': typeof DashboardIdAutomationsAmIdExecutionsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/convex-dashboard': typeof ConvexDashboardRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/_auth/log-in': typeof AuthLogInRoute
  '/_auth/sign-up': typeof AuthSignUpRoute
  '/dashboard/$id': typeof DashboardIdRouteWithChildren
  '/dashboard/create-organization': typeof DashboardCreateOrganizationRoute
  '/dashboard/$id/approvals': typeof DashboardIdApprovalsRouteWithChildren
  '/dashboard/$id/automations': typeof DashboardIdAutomationsRouteWithChildren
  '/dashboard/$id/chat': typeof DashboardIdChatRouteWithChildren
  '/dashboard/$id/conversations': typeof DashboardIdConversationsRouteWithChildren
  '/dashboard/$id/customers': typeof DashboardIdCustomersRoute
  '/dashboard/$id/documents': typeof DashboardIdDocumentsRoute
  '/dashboard/$id/products': typeof DashboardIdProductsRoute
  '/dashboard/$id/settings': typeof DashboardIdSettingsRouteWithChildren
  '/dashboard/$id/tone-of-voice': typeof DashboardIdToneOfVoiceRoute
  '/dashboard/$id/vendors': typeof DashboardIdVendorsRoute
  '/dashboard/$id/websites': typeof DashboardIdWebsitesRoute
  '/dashboard/$id/approvals/$status': typeof DashboardIdApprovalsStatusRoute
  '/dashboard/$id/automations/$amId': typeof DashboardIdAutomationsAmIdRouteWithChildren
  '/dashboard/$id/chat/$threadId': typeof DashboardIdChatThreadIdRoute
  '/dashboard/$id/conversations/$status': typeof DashboardIdConversationsStatusRoute
  '/dashboard/$id/settings/account': typeof DashboardIdSettingsAccountRoute
  '/dashboard/$id/settings/integrations': typeof DashboardIdSettingsIntegrationsRoute
  '/dashboard/$id/settings/logs': typeof DashboardIdSettingsLogsRoute
  '/dashboard/$id/settings/organization': typeof DashboardIdSettingsOrganizationRoute
  '/dashboard/$id/automations/$amId/configuration': typeof DashboardIdAutomationsAmIdConfigurationRoute
  '/dashboard/$id/automations/$amId/executions': typeof DashboardIdAutomationsAmIdExecutionsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/convex-dashboard'
    | '/dashboard'
    | '/log-in'
    | '/sign-up'
    | '/dashboard/$id'
    | '/dashboard/create-organization'
    | '/dashboard/$id/approvals'
    | '/dashboard/$id/automations'
    | '/dashboard/$id/chat'
    | '/dashboard/$id/conversations'
    | '/dashboard/$id/customers'
    | '/dashboard/$id/documents'
    | '/dashboard/$id/products'
    | '/dashboard/$id/settings'
    | '/dashboard/$id/tone-of-voice'
    | '/dashboard/$id/vendors'
    | '/dashboard/$id/websites'
    | '/dashboard/$id/approvals/$status'
    | '/dashboard/$id/automations/$amId'
    | '/dashboard/$id/chat/$threadId'
    | '/dashboard/$id/conversations/$status'
    | '/dashboard/$id/settings/account'
    | '/dashboard/$id/settings/integrations'
    | '/dashboard/$id/settings/logs'
    | '/dashboard/$id/settings/organization'
    | '/dashboard/$id/automations/$amId/configuration'
    | '/dashboard/$id/automations/$amId/executions'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/convex-dashboard'
    | '/dashboard'
    | '/log-in'
    | '/sign-up'
    | '/dashboard/$id'
    | '/dashboard/create-organization'
    | '/dashboard/$id/approvals'
    | '/dashboard/$id/automations'
    | '/dashboard/$id/chat'
    | '/dashboard/$id/conversations'
    | '/dashboard/$id/customers'
    | '/dashboard/$id/documents'
    | '/dashboard/$id/products'
    | '/dashboard/$id/settings'
    | '/dashboard/$id/tone-of-voice'
    | '/dashboard/$id/vendors'
    | '/dashboard/$id/websites'
    | '/dashboard/$id/approvals/$status'
    | '/dashboard/$id/automations/$amId'
    | '/dashboard/$id/chat/$threadId'
    | '/dashboard/$id/conversations/$status'
    | '/dashboard/$id/settings/account'
    | '/dashboard/$id/settings/integrations'
    | '/dashboard/$id/settings/logs'
    | '/dashboard/$id/settings/organization'
    | '/dashboard/$id/automations/$amId/configuration'
    | '/dashboard/$id/automations/$amId/executions'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/convex-dashboard'
    | '/dashboard'
    | '/_auth/log-in'
    | '/_auth/sign-up'
    | '/dashboard/$id'
    | '/dashboard/create-organization'
    | '/dashboard/$id/approvals'
    | '/dashboard/$id/automations'
    | '/dashboard/$id/chat'
    | '/dashboard/$id/conversations'
    | '/dashboard/$id/customers'
    | '/dashboard/$id/documents'
    | '/dashboard/$id/products'
    | '/dashboard/$id/settings'
    | '/dashboard/$id/tone-of-voice'
    | '/dashboard/$id/vendors'
    | '/dashboard/$id/websites'
    | '/dashboard/$id/approvals/$status'
    | '/dashboard/$id/automations/$amId'
    | '/dashboard/$id/chat/$threadId'
    | '/dashboard/$id/conversations/$status'
    | '/dashboard/$id/settings/account'
    | '/dashboard/$id/settings/integrations'
    | '/dashboard/$id/settings/logs'
    | '/dashboard/$id/settings/organization'
    | '/dashboard/$id/automations/$amId/configuration'
    | '/dashboard/$id/automations/$amId/executions'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  ConvexDashboardRoute: typeof ConvexDashboardRoute
  DashboardRoute: typeof DashboardRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/convex-dashboard': {
      id: '/convex-dashboard'
      path: '/convex-dashboard'
      fullPath: '/convex-dashboard'
      preLoaderRoute: typeof ConvexDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/create-organization': {
      id: '/dashboard/create-organization'
      path: '/create-organization'
      fullPath: '/dashboard/create-organization'
      preLoaderRoute: typeof DashboardCreateOrganizationRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/$id': {
      id: '/dashboard/$id'
      path: '/$id'
      fullPath: '/dashboard/$id'
      preLoaderRoute: typeof DashboardIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_auth/sign-up': {
      id: '/_auth/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/log-in': {
      id: '/_auth/log-in'
      path: '/log-in'
      fullPath: '/log-in'
      preLoaderRoute: typeof AuthLogInRouteImport
      parentRoute: typeof AuthRoute
    }
    '/dashboard/$id/websites': {
      id: '/dashboard/$id/websites'
      path: '/websites'
      fullPath: '/dashboard/$id/websites'
      preLoaderRoute: typeof DashboardIdWebsitesRouteImport
      parentRoute: typeof DashboardIdRoute
    }
    '/dashboard/$id/vendors': {
      id: '/dashboard/$id/vendors'
      path: '/vendors'
      fullPath: '/dashboard/$id/vendors'
      preLoaderRoute: typeof DashboardIdVendorsRouteImport
      parentRoute: typeof DashboardIdRoute
    }
    '/dashboard/$id/tone-of-voice': {
      id: '/dashboard/$id/tone-of-voice'
      path: '/tone-of-voice'
      fullPath: '/dashboard/$id/tone-of-voice'
      preLoaderRoute: typeof DashboardIdToneOfVoiceRouteImport
      parentRoute: typeof DashboardIdRoute
    }
    '/dashboard/$id/settings': {
      id: '/dashboard/$id/settings'
      path: '/settings'
      fullPath: '/dashboard/$id/settings'
      preLoaderRoute: typeof DashboardIdSettingsRouteImport
      parentRoute: typeof DashboardIdRoute
    }
    '/dashboard/$id/products': {
      id: '/dashboard/$id/products'
      path: '/products'
      fullPath: '/dashboard/$id/products'
      preLoaderRoute: typeof DashboardIdProductsRouteImport
      parentRoute: typeof DashboardIdRoute
    }
    '/dashboard/$id/documents': {
      id: '/dashboard/$id/documents'
      path: '/documents'
      fullPath: '/dashboard/$id/documents'
      preLoaderRoute: typeof DashboardIdDocumentsRouteImport
      parentRoute: typeof DashboardIdRoute
    }
    '/dashboard/$id/customers': {
      id: '/dashboard/$id/customers'
      path: '/customers'
      fullPath: '/dashboard/$id/customers'
      preLoaderRoute: typeof DashboardIdCustomersRouteImport
      parentRoute: typeof DashboardIdRoute
    }
    '/dashboard/$id/conversations': {
      id: '/dashboard/$id/conversations'
      path: '/conversations'
      fullPath: '/dashboard/$id/conversations'
      preLoaderRoute: typeof DashboardIdConversationsRouteImport
      parentRoute: typeof DashboardIdRoute
    }
    '/dashboard/$id/chat': {
      id: '/dashboard/$id/chat'
      path: '/chat'
      fullPath: '/dashboard/$id/chat'
      preLoaderRoute: typeof DashboardIdChatRouteImport
      parentRoute: typeof DashboardIdRoute
    }
    '/dashboard/$id/automations': {
      id: '/dashboard/$id/automations'
      path: '/automations'
      fullPath: '/dashboard/$id/automations'
      preLoaderRoute: typeof DashboardIdAutomationsRouteImport
      parentRoute: typeof DashboardIdRoute
    }
    '/dashboard/$id/approvals': {
      id: '/dashboard/$id/approvals'
      path: '/approvals'
      fullPath: '/dashboard/$id/approvals'
      preLoaderRoute: typeof DashboardIdApprovalsRouteImport
      parentRoute: typeof DashboardIdRoute
    }
    '/dashboard/$id/settings/organization': {
      id: '/dashboard/$id/settings/organization'
      path: '/organization'
      fullPath: '/dashboard/$id/settings/organization'
      preLoaderRoute: typeof DashboardIdSettingsOrganizationRouteImport
      parentRoute: typeof DashboardIdSettingsRoute
    }
    '/dashboard/$id/settings/logs': {
      id: '/dashboard/$id/settings/logs'
      path: '/logs'
      fullPath: '/dashboard/$id/settings/logs'
      preLoaderRoute: typeof DashboardIdSettingsLogsRouteImport
      parentRoute: typeof DashboardIdSettingsRoute
    }
    '/dashboard/$id/settings/integrations': {
      id: '/dashboard/$id/settings/integrations'
      path: '/integrations'
      fullPath: '/dashboard/$id/settings/integrations'
      preLoaderRoute: typeof DashboardIdSettingsIntegrationsRouteImport
      parentRoute: typeof DashboardIdSettingsRoute
    }
    '/dashboard/$id/settings/account': {
      id: '/dashboard/$id/settings/account'
      path: '/account'
      fullPath: '/dashboard/$id/settings/account'
      preLoaderRoute: typeof DashboardIdSettingsAccountRouteImport
      parentRoute: typeof DashboardIdSettingsRoute
    }
    '/dashboard/$id/conversations/$status': {
      id: '/dashboard/$id/conversations/$status'
      path: '/$status'
      fullPath: '/dashboard/$id/conversations/$status'
      preLoaderRoute: typeof DashboardIdConversationsStatusRouteImport
      parentRoute: typeof DashboardIdConversationsRoute
    }
    '/dashboard/$id/chat/$threadId': {
      id: '/dashboard/$id/chat/$threadId'
      path: '/$threadId'
      fullPath: '/dashboard/$id/chat/$threadId'
      preLoaderRoute: typeof DashboardIdChatThreadIdRouteImport
      parentRoute: typeof DashboardIdChatRoute
    }
    '/dashboard/$id/automations/$amId': {
      id: '/dashboard/$id/automations/$amId'
      path: '/$amId'
      fullPath: '/dashboard/$id/automations/$amId'
      preLoaderRoute: typeof DashboardIdAutomationsAmIdRouteImport
      parentRoute: typeof DashboardIdAutomationsRoute
    }
    '/dashboard/$id/approvals/$status': {
      id: '/dashboard/$id/approvals/$status'
      path: '/$status'
      fullPath: '/dashboard/$id/approvals/$status'
      preLoaderRoute: typeof DashboardIdApprovalsStatusRouteImport
      parentRoute: typeof DashboardIdApprovalsRoute
    }
    '/dashboard/$id/automations/$amId/executions': {
      id: '/dashboard/$id/automations/$amId/executions'
      path: '/executions'
      fullPath: '/dashboard/$id/automations/$amId/executions'
      preLoaderRoute: typeof DashboardIdAutomationsAmIdExecutionsRouteImport
      parentRoute: typeof DashboardIdAutomationsAmIdRoute
    }
    '/dashboard/$id/automations/$amId/configuration': {
      id: '/dashboard/$id/automations/$amId/configuration'
      path: '/configuration'
      fullPath: '/dashboard/$id/automations/$amId/configuration'
      preLoaderRoute: typeof DashboardIdAutomationsAmIdConfigurationRouteImport
      parentRoute: typeof DashboardIdAutomationsAmIdRoute
    }
  }
}

interface AuthRouteChildren {
  AuthLogInRoute: typeof AuthLogInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLogInRoute: AuthLogInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface DashboardIdApprovalsRouteChildren {
  DashboardIdApprovalsStatusRoute: typeof DashboardIdApprovalsStatusRoute
}

const DashboardIdApprovalsRouteChildren: DashboardIdApprovalsRouteChildren = {
  DashboardIdApprovalsStatusRoute: DashboardIdApprovalsStatusRoute,
}

const DashboardIdApprovalsRouteWithChildren =
  DashboardIdApprovalsRoute._addFileChildren(DashboardIdApprovalsRouteChildren)

interface DashboardIdAutomationsAmIdRouteChildren {
  DashboardIdAutomationsAmIdConfigurationRoute: typeof DashboardIdAutomationsAmIdConfigurationRoute
  DashboardIdAutomationsAmIdExecutionsRoute: typeof DashboardIdAutomationsAmIdExecutionsRoute
}

const DashboardIdAutomationsAmIdRouteChildren: DashboardIdAutomationsAmIdRouteChildren =
  {
    DashboardIdAutomationsAmIdConfigurationRoute:
      DashboardIdAutomationsAmIdConfigurationRoute,
    DashboardIdAutomationsAmIdExecutionsRoute:
      DashboardIdAutomationsAmIdExecutionsRoute,
  }

const DashboardIdAutomationsAmIdRouteWithChildren =
  DashboardIdAutomationsAmIdRoute._addFileChildren(
    DashboardIdAutomationsAmIdRouteChildren,
  )

interface DashboardIdAutomationsRouteChildren {
  DashboardIdAutomationsAmIdRoute: typeof DashboardIdAutomationsAmIdRouteWithChildren
}

const DashboardIdAutomationsRouteChildren: DashboardIdAutomationsRouteChildren =
  {
    DashboardIdAutomationsAmIdRoute:
      DashboardIdAutomationsAmIdRouteWithChildren,
  }

const DashboardIdAutomationsRouteWithChildren =
  DashboardIdAutomationsRoute._addFileChildren(
    DashboardIdAutomationsRouteChildren,
  )

interface DashboardIdChatRouteChildren {
  DashboardIdChatThreadIdRoute: typeof DashboardIdChatThreadIdRoute
}

const DashboardIdChatRouteChildren: DashboardIdChatRouteChildren = {
  DashboardIdChatThreadIdRoute: DashboardIdChatThreadIdRoute,
}

const DashboardIdChatRouteWithChildren = DashboardIdChatRoute._addFileChildren(
  DashboardIdChatRouteChildren,
)

interface DashboardIdConversationsRouteChildren {
  DashboardIdConversationsStatusRoute: typeof DashboardIdConversationsStatusRoute
}

const DashboardIdConversationsRouteChildren: DashboardIdConversationsRouteChildren =
  {
    DashboardIdConversationsStatusRoute: DashboardIdConversationsStatusRoute,
  }

const DashboardIdConversationsRouteWithChildren =
  DashboardIdConversationsRoute._addFileChildren(
    DashboardIdConversationsRouteChildren,
  )

interface DashboardIdSettingsRouteChildren {
  DashboardIdSettingsAccountRoute: typeof DashboardIdSettingsAccountRoute
  DashboardIdSettingsIntegrationsRoute: typeof DashboardIdSettingsIntegrationsRoute
  DashboardIdSettingsLogsRoute: typeof DashboardIdSettingsLogsRoute
  DashboardIdSettingsOrganizationRoute: typeof DashboardIdSettingsOrganizationRoute
}

const DashboardIdSettingsRouteChildren: DashboardIdSettingsRouteChildren = {
  DashboardIdSettingsAccountRoute: DashboardIdSettingsAccountRoute,
  DashboardIdSettingsIntegrationsRoute: DashboardIdSettingsIntegrationsRoute,
  DashboardIdSettingsLogsRoute: DashboardIdSettingsLogsRoute,
  DashboardIdSettingsOrganizationRoute: DashboardIdSettingsOrganizationRoute,
}

const DashboardIdSettingsRouteWithChildren =
  DashboardIdSettingsRoute._addFileChildren(DashboardIdSettingsRouteChildren)

interface DashboardIdRouteChildren {
  DashboardIdApprovalsRoute: typeof DashboardIdApprovalsRouteWithChildren
  DashboardIdAutomationsRoute: typeof DashboardIdAutomationsRouteWithChildren
  DashboardIdChatRoute: typeof DashboardIdChatRouteWithChildren
  DashboardIdConversationsRoute: typeof DashboardIdConversationsRouteWithChildren
  DashboardIdCustomersRoute: typeof DashboardIdCustomersRoute
  DashboardIdDocumentsRoute: typeof DashboardIdDocumentsRoute
  DashboardIdProductsRoute: typeof DashboardIdProductsRoute
  DashboardIdSettingsRoute: typeof DashboardIdSettingsRouteWithChildren
  DashboardIdToneOfVoiceRoute: typeof DashboardIdToneOfVoiceRoute
  DashboardIdVendorsRoute: typeof DashboardIdVendorsRoute
  DashboardIdWebsitesRoute: typeof DashboardIdWebsitesRoute
}

const DashboardIdRouteChildren: DashboardIdRouteChildren = {
  DashboardIdApprovalsRoute: DashboardIdApprovalsRouteWithChildren,
  DashboardIdAutomationsRoute: DashboardIdAutomationsRouteWithChildren,
  DashboardIdChatRoute: DashboardIdChatRouteWithChildren,
  DashboardIdConversationsRoute: DashboardIdConversationsRouteWithChildren,
  DashboardIdCustomersRoute: DashboardIdCustomersRoute,
  DashboardIdDocumentsRoute: DashboardIdDocumentsRoute,
  DashboardIdProductsRoute: DashboardIdProductsRoute,
  DashboardIdSettingsRoute: DashboardIdSettingsRouteWithChildren,
  DashboardIdToneOfVoiceRoute: DashboardIdToneOfVoiceRoute,
  DashboardIdVendorsRoute: DashboardIdVendorsRoute,
  DashboardIdWebsitesRoute: DashboardIdWebsitesRoute,
}

const DashboardIdRouteWithChildren = DashboardIdRoute._addFileChildren(
  DashboardIdRouteChildren,
)

interface DashboardRouteChildren {
  DashboardIdRoute: typeof DashboardIdRouteWithChildren
  DashboardCreateOrganizationRoute: typeof DashboardCreateOrganizationRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardIdRoute: DashboardIdRouteWithChildren,
  DashboardCreateOrganizationRoute: DashboardCreateOrganizationRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  ConvexDashboardRoute: ConvexDashboardRoute,
  DashboardRoute: DashboardRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
