/**
 * Registry of all per-locale domain lexicons. The detector unions across every
 * locale, exactly like the reasoning lexicon. `en` is hand-authored; the rest
 * are generated by the `gen-domain-lexicons` workflow.
 *
 * Add a locale by authoring a sibling file (mirroring `en.ts`) and appending it
 * here. Keep the array alphabetical by export name for deterministic ordering.
 */

import type { DomainLexicon } from '../types';
import { AR_LEXICON } from './ar';
import { BG_LEXICON } from './bg';
import { BN_LEXICON } from './bn';
import { CA_LEXICON } from './ca';
import { CS_LEXICON } from './cs';
import { DA_LEXICON } from './da';
import { DE_LEXICON } from './de';
import { EL_LEXICON } from './el';
import { EN_LEXICON } from './en';
import { ES_LEXICON } from './es';
import { ET_LEXICON } from './et';
import { FA_LEXICON } from './fa';
import { FI_LEXICON } from './fi';
import { FR_LEXICON } from './fr';
import { HE_LEXICON } from './he';
import { HI_LEXICON } from './hi';
import { HR_LEXICON } from './hr';
import { HU_LEXICON } from './hu';
import { ID_LEXICON } from './id';
import { IT_LEXICON } from './it';
import { JA_LEXICON } from './ja';
import { KO_LEXICON } from './ko';
import { LT_LEXICON } from './lt';
import { LV_LEXICON } from './lv';
import { MS_LEXICON } from './ms';
import { NB_LEXICON } from './nb';
import { NL_LEXICON } from './nl';
import { PL_LEXICON } from './pl';
import { PT_LEXICON } from './pt';
import { RO_LEXICON } from './ro';
import { RU_LEXICON } from './ru';
import { SK_LEXICON } from './sk';
import { SL_LEXICON } from './sl';
import { SR_LEXICON } from './sr';
import { SV_LEXICON } from './sv';
import { TH_LEXICON } from './th';
import { TL_LEXICON } from './tl';
import { TR_LEXICON } from './tr';
import { UK_LEXICON } from './uk';
import { UR_LEXICON } from './ur';
import { VI_LEXICON } from './vi';
import { ZH_HANS_LEXICON } from './zh_hans';
import { ZH_HANT_LEXICON } from './zh_hant';

export const ALL_DOMAIN_LEXICONS: DomainLexicon[] = [
  AR_LEXICON,
  BG_LEXICON,
  BN_LEXICON,
  CA_LEXICON,
  CS_LEXICON,
  DA_LEXICON,
  DE_LEXICON,
  EL_LEXICON,
  EN_LEXICON,
  ES_LEXICON,
  ET_LEXICON,
  FA_LEXICON,
  FI_LEXICON,
  FR_LEXICON,
  HE_LEXICON,
  HI_LEXICON,
  HR_LEXICON,
  HU_LEXICON,
  ID_LEXICON,
  IT_LEXICON,
  JA_LEXICON,
  KO_LEXICON,
  LT_LEXICON,
  LV_LEXICON,
  MS_LEXICON,
  NB_LEXICON,
  NL_LEXICON,
  PL_LEXICON,
  PT_LEXICON,
  RO_LEXICON,
  RU_LEXICON,
  SK_LEXICON,
  SL_LEXICON,
  SR_LEXICON,
  SV_LEXICON,
  TH_LEXICON,
  TL_LEXICON,
  TR_LEXICON,
  UK_LEXICON,
  UR_LEXICON,
  VI_LEXICON,
  ZH_HANS_LEXICON,
  ZH_HANT_LEXICON,
];
