/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root';
import { Route as RequestDemoRouteImport } from './routes/request-demo';
import { Route as PricingRouteImport } from './routes/pricing';
import { Route as HardwarePricingRouteImport } from './routes/hardware-pricing';
import { Route as ContactRouteImport } from './routes/contact';
import { Route as ChangelogRouteImport } from './routes/changelog';
import { Route as AboutRouteImport } from './routes/about';
import { Route as LangRouteImport } from './routes/$lang';
import { Route as IndexRouteImport } from './routes/index';
import { Route as PlatformIndexRouteImport } from './routes/platform/index';
import { Route as LangIndexRouteImport } from './routes/$lang/index';
import { Route as PlatformProjectsRouteImport } from './routes/platform/projects';
import { Route as PlatformKnowledgeRouteImport } from './routes/platform/knowledge';
import { Route as PlatformGovernanceRouteImport } from './routes/platform/governance';
import { Route as PlatformChatRouteImport } from './routes/platform/chat';
import { Route as PlatformAutomationsRouteImport } from './routes/platform/automations';
import { Route as PlatformAgentsRouteImport } from './routes/platform/agents';
import { Route as LegalSlugRouteImport } from './routes/legal/$slug';
import { Route as LangRequestDemoRouteImport } from './routes/$lang/request-demo';
import { Route as LangPricingRouteImport } from './routes/$lang/pricing';
import { Route as LangHardwarePricingRouteImport } from './routes/$lang/hardware-pricing';
import { Route as LangContactRouteImport } from './routes/$lang/contact';
import { Route as LangChangelogRouteImport } from './routes/$lang/changelog';
import { Route as LangAboutRouteImport } from './routes/$lang/about';
import { Route as LangPlatformIndexRouteImport } from './routes/$lang/platform/index';
import { Route as LangPlatformProjectsRouteImport } from './routes/$lang/platform/projects';
import { Route as LangPlatformKnowledgeRouteImport } from './routes/$lang/platform/knowledge';
import { Route as LangPlatformGovernanceRouteImport } from './routes/$lang/platform/governance';
import { Route as LangPlatformChatRouteImport } from './routes/$lang/platform/chat';
import { Route as LangPlatformAutomationsRouteImport } from './routes/$lang/platform/automations';
import { Route as LangPlatformAgentsRouteImport } from './routes/$lang/platform/agents';
import { Route as LangLegalSlugRouteImport } from './routes/$lang/legal/$slug';

const RequestDemoRoute = RequestDemoRouteImport.update({
  id: '/request-demo',
  path: '/request-demo',
  getParentRoute: () => rootRouteImport,
} as any);
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any);
const HardwarePricingRoute = HardwarePricingRouteImport.update({
  id: '/hardware-pricing',
  path: '/hardware-pricing',
  getParentRoute: () => rootRouteImport,
} as any);
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any);
const ChangelogRoute = ChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => rootRouteImport,
} as any);
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any);
const LangRoute = LangRouteImport.update({
  id: '/$lang',
  path: '/$lang',
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any);
const PlatformIndexRoute = PlatformIndexRouteImport.update({
  id: '/platform/',
  path: '/platform/',
  getParentRoute: () => rootRouteImport,
} as any);
const LangIndexRoute = LangIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LangRoute,
} as any);
const PlatformProjectsRoute = PlatformProjectsRouteImport.update({
  id: '/platform/projects',
  path: '/platform/projects',
  getParentRoute: () => rootRouteImport,
} as any);
const PlatformKnowledgeRoute = PlatformKnowledgeRouteImport.update({
  id: '/platform/knowledge',
  path: '/platform/knowledge',
  getParentRoute: () => rootRouteImport,
} as any);
const PlatformGovernanceRoute = PlatformGovernanceRouteImport.update({
  id: '/platform/governance',
  path: '/platform/governance',
  getParentRoute: () => rootRouteImport,
} as any);
const PlatformChatRoute = PlatformChatRouteImport.update({
  id: '/platform/chat',
  path: '/platform/chat',
  getParentRoute: () => rootRouteImport,
} as any);
const PlatformAutomationsRoute = PlatformAutomationsRouteImport.update({
  id: '/platform/automations',
  path: '/platform/automations',
  getParentRoute: () => rootRouteImport,
} as any);
const PlatformAgentsRoute = PlatformAgentsRouteImport.update({
  id: '/platform/agents',
  path: '/platform/agents',
  getParentRoute: () => rootRouteImport,
} as any);
const LegalSlugRoute = LegalSlugRouteImport.update({
  id: '/legal/$slug',
  path: '/legal/$slug',
  getParentRoute: () => rootRouteImport,
} as any);
const LangRequestDemoRoute = LangRequestDemoRouteImport.update({
  id: '/request-demo',
  path: '/request-demo',
  getParentRoute: () => LangRoute,
} as any);
const LangPricingRoute = LangPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => LangRoute,
} as any);
const LangHardwarePricingRoute = LangHardwarePricingRouteImport.update({
  id: '/hardware-pricing',
  path: '/hardware-pricing',
  getParentRoute: () => LangRoute,
} as any);
const LangContactRoute = LangContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => LangRoute,
} as any);
const LangChangelogRoute = LangChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => LangRoute,
} as any);
const LangAboutRoute = LangAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => LangRoute,
} as any);
const LangPlatformIndexRoute = LangPlatformIndexRouteImport.update({
  id: '/platform/',
  path: '/platform/',
  getParentRoute: () => LangRoute,
} as any);
const LangPlatformProjectsRoute = LangPlatformProjectsRouteImport.update({
  id: '/platform/projects',
  path: '/platform/projects',
  getParentRoute: () => LangRoute,
} as any);
const LangPlatformKnowledgeRoute = LangPlatformKnowledgeRouteImport.update({
  id: '/platform/knowledge',
  path: '/platform/knowledge',
  getParentRoute: () => LangRoute,
} as any);
const LangPlatformGovernanceRoute = LangPlatformGovernanceRouteImport.update({
  id: '/platform/governance',
  path: '/platform/governance',
  getParentRoute: () => LangRoute,
} as any);
const LangPlatformChatRoute = LangPlatformChatRouteImport.update({
  id: '/platform/chat',
  path: '/platform/chat',
  getParentRoute: () => LangRoute,
} as any);
const LangPlatformAutomationsRoute = LangPlatformAutomationsRouteImport.update({
  id: '/platform/automations',
  path: '/platform/automations',
  getParentRoute: () => LangRoute,
} as any);
const LangPlatformAgentsRoute = LangPlatformAgentsRouteImport.update({
  id: '/platform/agents',
  path: '/platform/agents',
  getParentRoute: () => LangRoute,
} as any);
const LangLegalSlugRoute = LangLegalSlugRouteImport.update({
  id: '/legal/$slug',
  path: '/legal/$slug',
  getParentRoute: () => LangRoute,
} as any);

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute;
  '/$lang': typeof LangRouteWithChildren;
  '/about': typeof AboutRoute;
  '/changelog': typeof ChangelogRoute;
  '/contact': typeof ContactRoute;
  '/hardware-pricing': typeof HardwarePricingRoute;
  '/pricing': typeof PricingRoute;
  '/request-demo': typeof RequestDemoRoute;
  '/$lang/about': typeof LangAboutRoute;
  '/$lang/changelog': typeof LangChangelogRoute;
  '/$lang/contact': typeof LangContactRoute;
  '/$lang/hardware-pricing': typeof LangHardwarePricingRoute;
  '/$lang/pricing': typeof LangPricingRoute;
  '/$lang/request-demo': typeof LangRequestDemoRoute;
  '/legal/$slug': typeof LegalSlugRoute;
  '/platform/agents': typeof PlatformAgentsRoute;
  '/platform/automations': typeof PlatformAutomationsRoute;
  '/platform/chat': typeof PlatformChatRoute;
  '/platform/governance': typeof PlatformGovernanceRoute;
  '/platform/knowledge': typeof PlatformKnowledgeRoute;
  '/platform/projects': typeof PlatformProjectsRoute;
  '/$lang/': typeof LangIndexRoute;
  '/platform/': typeof PlatformIndexRoute;
  '/$lang/legal/$slug': typeof LangLegalSlugRoute;
  '/$lang/platform/agents': typeof LangPlatformAgentsRoute;
  '/$lang/platform/automations': typeof LangPlatformAutomationsRoute;
  '/$lang/platform/chat': typeof LangPlatformChatRoute;
  '/$lang/platform/governance': typeof LangPlatformGovernanceRoute;
  '/$lang/platform/knowledge': typeof LangPlatformKnowledgeRoute;
  '/$lang/platform/projects': typeof LangPlatformProjectsRoute;
  '/$lang/platform/': typeof LangPlatformIndexRoute;
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute;
  '/about': typeof AboutRoute;
  '/changelog': typeof ChangelogRoute;
  '/contact': typeof ContactRoute;
  '/hardware-pricing': typeof HardwarePricingRoute;
  '/pricing': typeof PricingRoute;
  '/request-demo': typeof RequestDemoRoute;
  '/$lang/about': typeof LangAboutRoute;
  '/$lang/changelog': typeof LangChangelogRoute;
  '/$lang/contact': typeof LangContactRoute;
  '/$lang/hardware-pricing': typeof LangHardwarePricingRoute;
  '/$lang/pricing': typeof LangPricingRoute;
  '/$lang/request-demo': typeof LangRequestDemoRoute;
  '/legal/$slug': typeof LegalSlugRoute;
  '/platform/agents': typeof PlatformAgentsRoute;
  '/platform/automations': typeof PlatformAutomationsRoute;
  '/platform/chat': typeof PlatformChatRoute;
  '/platform/governance': typeof PlatformGovernanceRoute;
  '/platform/knowledge': typeof PlatformKnowledgeRoute;
  '/platform/projects': typeof PlatformProjectsRoute;
  '/$lang': typeof LangIndexRoute;
  '/platform': typeof PlatformIndexRoute;
  '/$lang/legal/$slug': typeof LangLegalSlugRoute;
  '/$lang/platform/agents': typeof LangPlatformAgentsRoute;
  '/$lang/platform/automations': typeof LangPlatformAutomationsRoute;
  '/$lang/platform/chat': typeof LangPlatformChatRoute;
  '/$lang/platform/governance': typeof LangPlatformGovernanceRoute;
  '/$lang/platform/knowledge': typeof LangPlatformKnowledgeRoute;
  '/$lang/platform/projects': typeof LangPlatformProjectsRoute;
  '/$lang/platform': typeof LangPlatformIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  '/': typeof IndexRoute;
  '/$lang': typeof LangRouteWithChildren;
  '/about': typeof AboutRoute;
  '/changelog': typeof ChangelogRoute;
  '/contact': typeof ContactRoute;
  '/hardware-pricing': typeof HardwarePricingRoute;
  '/pricing': typeof PricingRoute;
  '/request-demo': typeof RequestDemoRoute;
  '/$lang/about': typeof LangAboutRoute;
  '/$lang/changelog': typeof LangChangelogRoute;
  '/$lang/contact': typeof LangContactRoute;
  '/$lang/hardware-pricing': typeof LangHardwarePricingRoute;
  '/$lang/pricing': typeof LangPricingRoute;
  '/$lang/request-demo': typeof LangRequestDemoRoute;
  '/legal/$slug': typeof LegalSlugRoute;
  '/platform/agents': typeof PlatformAgentsRoute;
  '/platform/automations': typeof PlatformAutomationsRoute;
  '/platform/chat': typeof PlatformChatRoute;
  '/platform/governance': typeof PlatformGovernanceRoute;
  '/platform/knowledge': typeof PlatformKnowledgeRoute;
  '/platform/projects': typeof PlatformProjectsRoute;
  '/$lang/': typeof LangIndexRoute;
  '/platform/': typeof PlatformIndexRoute;
  '/$lang/legal/$slug': typeof LangLegalSlugRoute;
  '/$lang/platform/agents': typeof LangPlatformAgentsRoute;
  '/$lang/platform/automations': typeof LangPlatformAutomationsRoute;
  '/$lang/platform/chat': typeof LangPlatformChatRoute;
  '/$lang/platform/governance': typeof LangPlatformGovernanceRoute;
  '/$lang/platform/knowledge': typeof LangPlatformKnowledgeRoute;
  '/$lang/platform/projects': typeof LangPlatformProjectsRoute;
  '/$lang/platform/': typeof LangPlatformIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | '/'
    | '/$lang'
    | '/about'
    | '/changelog'
    | '/contact'
    | '/hardware-pricing'
    | '/pricing'
    | '/request-demo'
    | '/$lang/about'
    | '/$lang/changelog'
    | '/$lang/contact'
    | '/$lang/hardware-pricing'
    | '/$lang/pricing'
    | '/$lang/request-demo'
    | '/legal/$slug'
    | '/platform/agents'
    | '/platform/automations'
    | '/platform/chat'
    | '/platform/governance'
    | '/platform/knowledge'
    | '/platform/projects'
    | '/$lang/'
    | '/platform/'
    | '/$lang/legal/$slug'
    | '/$lang/platform/agents'
    | '/$lang/platform/automations'
    | '/$lang/platform/chat'
    | '/$lang/platform/governance'
    | '/$lang/platform/knowledge'
    | '/$lang/platform/projects'
    | '/$lang/platform/';
  fileRoutesByTo: FileRoutesByTo;
  to:
    | '/'
    | '/about'
    | '/changelog'
    | '/contact'
    | '/hardware-pricing'
    | '/pricing'
    | '/request-demo'
    | '/$lang/about'
    | '/$lang/changelog'
    | '/$lang/contact'
    | '/$lang/hardware-pricing'
    | '/$lang/pricing'
    | '/$lang/request-demo'
    | '/legal/$slug'
    | '/platform/agents'
    | '/platform/automations'
    | '/platform/chat'
    | '/platform/governance'
    | '/platform/knowledge'
    | '/platform/projects'
    | '/$lang'
    | '/platform'
    | '/$lang/legal/$slug'
    | '/$lang/platform/agents'
    | '/$lang/platform/automations'
    | '/$lang/platform/chat'
    | '/$lang/platform/governance'
    | '/$lang/platform/knowledge'
    | '/$lang/platform/projects'
    | '/$lang/platform';
  id:
    | '__root__'
    | '/'
    | '/$lang'
    | '/about'
    | '/changelog'
    | '/contact'
    | '/hardware-pricing'
    | '/pricing'
    | '/request-demo'
    | '/$lang/about'
    | '/$lang/changelog'
    | '/$lang/contact'
    | '/$lang/hardware-pricing'
    | '/$lang/pricing'
    | '/$lang/request-demo'
    | '/legal/$slug'
    | '/platform/agents'
    | '/platform/automations'
    | '/platform/chat'
    | '/platform/governance'
    | '/platform/knowledge'
    | '/platform/projects'
    | '/$lang/'
    | '/platform/'
    | '/$lang/legal/$slug'
    | '/$lang/platform/agents'
    | '/$lang/platform/automations'
    | '/$lang/platform/chat'
    | '/$lang/platform/governance'
    | '/$lang/platform/knowledge'
    | '/$lang/platform/projects'
    | '/$lang/platform/';
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  LangRoute: typeof LangRouteWithChildren;
  AboutRoute: typeof AboutRoute;
  ChangelogRoute: typeof ChangelogRoute;
  ContactRoute: typeof ContactRoute;
  HardwarePricingRoute: typeof HardwarePricingRoute;
  PricingRoute: typeof PricingRoute;
  RequestDemoRoute: typeof RequestDemoRoute;
  LegalSlugRoute: typeof LegalSlugRoute;
  PlatformAgentsRoute: typeof PlatformAgentsRoute;
  PlatformAutomationsRoute: typeof PlatformAutomationsRoute;
  PlatformChatRoute: typeof PlatformChatRoute;
  PlatformGovernanceRoute: typeof PlatformGovernanceRoute;
  PlatformKnowledgeRoute: typeof PlatformKnowledgeRoute;
  PlatformProjectsRoute: typeof PlatformProjectsRoute;
  PlatformIndexRoute: typeof PlatformIndexRoute;
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/request-demo': {
      id: '/request-demo';
      path: '/request-demo';
      fullPath: '/request-demo';
      preLoaderRoute: typeof RequestDemoRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/pricing': {
      id: '/pricing';
      path: '/pricing';
      fullPath: '/pricing';
      preLoaderRoute: typeof PricingRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/hardware-pricing': {
      id: '/hardware-pricing';
      path: '/hardware-pricing';
      fullPath: '/hardware-pricing';
      preLoaderRoute: typeof HardwarePricingRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/contact': {
      id: '/contact';
      path: '/contact';
      fullPath: '/contact';
      preLoaderRoute: typeof ContactRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/changelog': {
      id: '/changelog';
      path: '/changelog';
      fullPath: '/changelog';
      preLoaderRoute: typeof ChangelogRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/about': {
      id: '/about';
      path: '/about';
      fullPath: '/about';
      preLoaderRoute: typeof AboutRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/$lang': {
      id: '/$lang';
      path: '/$lang';
      fullPath: '/$lang';
      preLoaderRoute: typeof LangRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/': {
      id: '/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/platform/': {
      id: '/platform/';
      path: '/platform';
      fullPath: '/platform/';
      preLoaderRoute: typeof PlatformIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/$lang/': {
      id: '/$lang/';
      path: '/';
      fullPath: '/$lang/';
      preLoaderRoute: typeof LangIndexRouteImport;
      parentRoute: typeof LangRoute;
    };
    '/platform/projects': {
      id: '/platform/projects';
      path: '/platform/projects';
      fullPath: '/platform/projects';
      preLoaderRoute: typeof PlatformProjectsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/platform/knowledge': {
      id: '/platform/knowledge';
      path: '/platform/knowledge';
      fullPath: '/platform/knowledge';
      preLoaderRoute: typeof PlatformKnowledgeRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/platform/governance': {
      id: '/platform/governance';
      path: '/platform/governance';
      fullPath: '/platform/governance';
      preLoaderRoute: typeof PlatformGovernanceRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/platform/chat': {
      id: '/platform/chat';
      path: '/platform/chat';
      fullPath: '/platform/chat';
      preLoaderRoute: typeof PlatformChatRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/platform/automations': {
      id: '/platform/automations';
      path: '/platform/automations';
      fullPath: '/platform/automations';
      preLoaderRoute: typeof PlatformAutomationsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/platform/agents': {
      id: '/platform/agents';
      path: '/platform/agents';
      fullPath: '/platform/agents';
      preLoaderRoute: typeof PlatformAgentsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/legal/$slug': {
      id: '/legal/$slug';
      path: '/legal/$slug';
      fullPath: '/legal/$slug';
      preLoaderRoute: typeof LegalSlugRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/$lang/request-demo': {
      id: '/$lang/request-demo';
      path: '/request-demo';
      fullPath: '/$lang/request-demo';
      preLoaderRoute: typeof LangRequestDemoRouteImport;
      parentRoute: typeof LangRoute;
    };
    '/$lang/pricing': {
      id: '/$lang/pricing';
      path: '/pricing';
      fullPath: '/$lang/pricing';
      preLoaderRoute: typeof LangPricingRouteImport;
      parentRoute: typeof LangRoute;
    };
    '/$lang/hardware-pricing': {
      id: '/$lang/hardware-pricing';
      path: '/hardware-pricing';
      fullPath: '/$lang/hardware-pricing';
      preLoaderRoute: typeof LangHardwarePricingRouteImport;
      parentRoute: typeof LangRoute;
    };
    '/$lang/contact': {
      id: '/$lang/contact';
      path: '/contact';
      fullPath: '/$lang/contact';
      preLoaderRoute: typeof LangContactRouteImport;
      parentRoute: typeof LangRoute;
    };
    '/$lang/changelog': {
      id: '/$lang/changelog';
      path: '/changelog';
      fullPath: '/$lang/changelog';
      preLoaderRoute: typeof LangChangelogRouteImport;
      parentRoute: typeof LangRoute;
    };
    '/$lang/about': {
      id: '/$lang/about';
      path: '/about';
      fullPath: '/$lang/about';
      preLoaderRoute: typeof LangAboutRouteImport;
      parentRoute: typeof LangRoute;
    };
    '/$lang/platform/': {
      id: '/$lang/platform/';
      path: '/platform';
      fullPath: '/$lang/platform/';
      preLoaderRoute: typeof LangPlatformIndexRouteImport;
      parentRoute: typeof LangRoute;
    };
    '/$lang/platform/projects': {
      id: '/$lang/platform/projects';
      path: '/platform/projects';
      fullPath: '/$lang/platform/projects';
      preLoaderRoute: typeof LangPlatformProjectsRouteImport;
      parentRoute: typeof LangRoute;
    };
    '/$lang/platform/knowledge': {
      id: '/$lang/platform/knowledge';
      path: '/platform/knowledge';
      fullPath: '/$lang/platform/knowledge';
      preLoaderRoute: typeof LangPlatformKnowledgeRouteImport;
      parentRoute: typeof LangRoute;
    };
    '/$lang/platform/governance': {
      id: '/$lang/platform/governance';
      path: '/platform/governance';
      fullPath: '/$lang/platform/governance';
      preLoaderRoute: typeof LangPlatformGovernanceRouteImport;
      parentRoute: typeof LangRoute;
    };
    '/$lang/platform/chat': {
      id: '/$lang/platform/chat';
      path: '/platform/chat';
      fullPath: '/$lang/platform/chat';
      preLoaderRoute: typeof LangPlatformChatRouteImport;
      parentRoute: typeof LangRoute;
    };
    '/$lang/platform/automations': {
      id: '/$lang/platform/automations';
      path: '/platform/automations';
      fullPath: '/$lang/platform/automations';
      preLoaderRoute: typeof LangPlatformAutomationsRouteImport;
      parentRoute: typeof LangRoute;
    };
    '/$lang/platform/agents': {
      id: '/$lang/platform/agents';
      path: '/platform/agents';
      fullPath: '/$lang/platform/agents';
      preLoaderRoute: typeof LangPlatformAgentsRouteImport;
      parentRoute: typeof LangRoute;
    };
    '/$lang/legal/$slug': {
      id: '/$lang/legal/$slug';
      path: '/legal/$slug';
      fullPath: '/$lang/legal/$slug';
      preLoaderRoute: typeof LangLegalSlugRouteImport;
      parentRoute: typeof LangRoute;
    };
  }
}

interface LangRouteChildren {
  LangAboutRoute: typeof LangAboutRoute;
  LangChangelogRoute: typeof LangChangelogRoute;
  LangContactRoute: typeof LangContactRoute;
  LangHardwarePricingRoute: typeof LangHardwarePricingRoute;
  LangPricingRoute: typeof LangPricingRoute;
  LangRequestDemoRoute: typeof LangRequestDemoRoute;
  LangIndexRoute: typeof LangIndexRoute;
  LangLegalSlugRoute: typeof LangLegalSlugRoute;
  LangPlatformAgentsRoute: typeof LangPlatformAgentsRoute;
  LangPlatformAutomationsRoute: typeof LangPlatformAutomationsRoute;
  LangPlatformChatRoute: typeof LangPlatformChatRoute;
  LangPlatformGovernanceRoute: typeof LangPlatformGovernanceRoute;
  LangPlatformKnowledgeRoute: typeof LangPlatformKnowledgeRoute;
  LangPlatformProjectsRoute: typeof LangPlatformProjectsRoute;
  LangPlatformIndexRoute: typeof LangPlatformIndexRoute;
}

const LangRouteChildren: LangRouteChildren = {
  LangAboutRoute: LangAboutRoute,
  LangChangelogRoute: LangChangelogRoute,
  LangContactRoute: LangContactRoute,
  LangHardwarePricingRoute: LangHardwarePricingRoute,
  LangPricingRoute: LangPricingRoute,
  LangRequestDemoRoute: LangRequestDemoRoute,
  LangIndexRoute: LangIndexRoute,
  LangLegalSlugRoute: LangLegalSlugRoute,
  LangPlatformAgentsRoute: LangPlatformAgentsRoute,
  LangPlatformAutomationsRoute: LangPlatformAutomationsRoute,
  LangPlatformChatRoute: LangPlatformChatRoute,
  LangPlatformGovernanceRoute: LangPlatformGovernanceRoute,
  LangPlatformKnowledgeRoute: LangPlatformKnowledgeRoute,
  LangPlatformProjectsRoute: LangPlatformProjectsRoute,
  LangPlatformIndexRoute: LangPlatformIndexRoute,
};

const LangRouteWithChildren = LangRoute._addFileChildren(LangRouteChildren);

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LangRoute: LangRouteWithChildren,
  AboutRoute: AboutRoute,
  ChangelogRoute: ChangelogRoute,
  ContactRoute: ContactRoute,
  HardwarePricingRoute: HardwarePricingRoute,
  PricingRoute: PricingRoute,
  RequestDemoRoute: RequestDemoRoute,
  LegalSlugRoute: LegalSlugRoute,
  PlatformAgentsRoute: PlatformAgentsRoute,
  PlatformAutomationsRoute: PlatformAutomationsRoute,
  PlatformChatRoute: PlatformChatRoute,
  PlatformGovernanceRoute: PlatformGovernanceRoute,
  PlatformKnowledgeRoute: PlatformKnowledgeRoute,
  PlatformProjectsRoute: PlatformProjectsRoute,
  PlatformIndexRoute: PlatformIndexRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
