/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root';
import { Route as RequestDemoRouteImport } from './routes/request-demo';
import { Route as PricingRouteImport } from './routes/pricing';
import { Route as ContactRouteImport } from './routes/contact';
import { Route as IndexRouteImport } from './routes/index';

const RequestDemoRoute = RequestDemoRouteImport.update({
  id: '/request-demo',
  path: '/request-demo',
  getParentRoute: () => rootRouteImport,
} as any);
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any);
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute;
  '/contact': typeof ContactRoute;
  '/pricing': typeof PricingRoute;
  '/request-demo': typeof RequestDemoRoute;
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute;
  '/contact': typeof ContactRoute;
  '/pricing': typeof PricingRoute;
  '/request-demo': typeof RequestDemoRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  '/': typeof IndexRoute;
  '/contact': typeof ContactRoute;
  '/pricing': typeof PricingRoute;
  '/request-demo': typeof RequestDemoRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: '/' | '/contact' | '/pricing' | '/request-demo';
  fileRoutesByTo: FileRoutesByTo;
  to: '/' | '/contact' | '/pricing' | '/request-demo';
  id: '__root__' | '/' | '/contact' | '/pricing' | '/request-demo';
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  ContactRoute: typeof ContactRoute;
  PricingRoute: typeof PricingRoute;
  RequestDemoRoute: typeof RequestDemoRoute;
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/request-demo': {
      id: '/request-demo';
      path: '/request-demo';
      fullPath: '/request-demo';
      preLoaderRoute: typeof RequestDemoRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/pricing': {
      id: '/pricing';
      path: '/pricing';
      fullPath: '/pricing';
      preLoaderRoute: typeof PricingRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/contact': {
      id: '/contact';
      path: '/contact';
      fullPath: '/contact';
      preLoaderRoute: typeof ContactRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/': {
      id: '/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  PricingRoute: PricingRoute,
  RequestDemoRoute: RequestDemoRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
