'use node';

/**
 * Video-link ingest orchestrator. Single owner of the videoLinkJobs row
 * lifecycle: queued → fetching_metadata → (fetching_captions → indexing →
 * completed) OR (extracting_audio → transcribing_handoff → completed-via-
 * reactive-join).
 *
 * Design (after 30 + 15 sub-agent reviews):
 *   - Top-level `try { ... } finally { rm jobDir }` guarantees /tmp/vlink-
 *     <uuid>/ cleanup even on action timeout / OOM / kill -9.
 *   - Phase-boundary status re-check: cancel mutations flip `status` to
 *     `'skipped'`, this action's `assertNotCancelled()` peeks the row
 *     between expensive operations and bails out gracefully (mirrors
 *     transcribe_audio.ts:317-337).
 *   - 4h duration cap rejects videos AFTER cheap metadata fetch but
 *     BEFORE any audio download (R14: pre-spend abuse guard).
 *   - Caption language precedence: fidelity-first hybrid (R5):
 *       1. Manual subs in original language
 *       2. Manual subs in UI locale (non-translated)
 *       3. Manual subs in en (LLM's strongest translation pivot)
 *       4. Manual subs in ANY language
 *       5. Auto-gen ASR in original language (if non-translated)
 *       6. Auto-gen translation into UI locale (last caption resort)
 *       7. Fall through to Whisper-audio path
 *   - Error classification: stderr from ytdlp.ts is already classified;
 *     retry [30s, 60s, 120s] aligned with TRANSCRIBE_RETRY_DELAYS_MS;
 *     bot_detection/rate_limited bypass short-retry (long-jitter or fail).
 */

import { promises as fs } from 'node:fs';

import { v } from 'convex/values';

import { CHAT_AUDIO_MAX_DURATION_SEC } from '../../lib/shared/file-types';
import { internal } from '../_generated/api';
import type { Id } from '../_generated/dataModel';
import type { ActionCtx } from '../_generated/server';
import { internalAction } from '../_generated/server';
import {
  joinSegmentsWithParagraphs,
  CAPTION_PROFILE,
} from '../file_metadata/paragraphize';
import {
  captionsToParagraphSegments,
  parseVtt,
  rollingWindowDedup,
} from './captions_parser';
import { assertSafeUrl, UrlSafetyError } from './url_safety';
import {
  YtDlpError,
  createJobDir,
  ytdlpExtractAudio,
  ytdlpJson,
  ytdlpWriteSubs,
  type YtDlpMetadata,
} from './ytdlp';

const INGEST_RETRY_DELAYS_MS = [30_000, 60_000, 120_000];
const MAX_ATTEMPTS = INGEST_RETRY_DELAYS_MS.length + 1;

const NEVER_RETRY: ReadonlySet<string> = new Set([
  'private_or_age_gated',
  'geoblocked',
  'unsupported',
  'unavailable',
  'live_stream',
  'premiere',
  'member_only',
  'js_runtime_missing',
  'binary_not_installed',
  'output_validation_failed',
  // bot_detection + rate_limited would benefit from a long-jitter retry
  // but short retries make YouTube's rate-limit worse. Treat as
  // never-retry for v1; user can manually retry after waiting.
  'bot_detection',
  'rate_limited',
]);

interface CaptionSelection {
  /** yt-dlp `--sub-langs` value (e.g. `en` or `zh-Hans`). */
  lang: string;
  /** Whether yt-dlp's `--write-auto-subs` flag must be added. */
  includeAutoGenerated: boolean;
  /** Reported back into the job row for debugging + chip tooltip. */
  trackKind: 'manual' | 'asr' | 'auto-translated';
}

function selectCaptionLanguage(
  meta: YtDlpMetadata,
  userLocale: string | undefined,
): CaptionSelection | null {
  const uiBase = userLocale?.split('-')[0]?.toLowerCase();
  const original = meta.language?.toLowerCase();
  const manualLangs = Object.keys(meta.subtitles ?? {}).map((l) =>
    l.toLowerCase(),
  );
  const autoLangs = Object.keys(meta.automatic_captions ?? {}).map((l) =>
    l.toLowerCase(),
  );

  // 1. Manual subs in original language
  if (original) {
    const hit = manualLangs.find(
      (l) => l === original || l.split('-')[0] === original,
    );
    if (hit)
      return { lang: hit, includeAutoGenerated: false, trackKind: 'manual' };
  }
  // 2. Manual subs in UI locale (non-translated)
  if (uiBase) {
    const hit = manualLangs.find(
      (l) => l === userLocale?.toLowerCase() || l.split('-')[0] === uiBase,
    );
    if (hit)
      return { lang: hit, includeAutoGenerated: false, trackKind: 'manual' };
  }
  // 3. Manual English (LLM's strongest pivot)
  {
    const hit = manualLangs.find((l) => l === 'en' || l.startsWith('en-'));
    if (hit)
      return { lang: hit, includeAutoGenerated: false, trackKind: 'manual' };
  }
  // 4. ANY manual subtitle
  if (manualLangs.length > 0) {
    return {
      lang: manualLangs[0],
      includeAutoGenerated: false,
      trackKind: 'manual',
    };
  }
  // 5. Auto-gen ASR in original language
  if (original) {
    const hit = autoLangs.find(
      (l) => l === original || l.split('-')[0] === original,
    );
    if (hit) return { lang: hit, includeAutoGenerated: true, trackKind: 'asr' };
  }
  // 6. Auto-gen in UI locale (machine-translated by YouTube — last resort)
  if (uiBase) {
    const hit = autoLangs.find((l) => l.split('-')[0] === uiBase);
    if (hit)
      return {
        lang: hit,
        includeAutoGenerated: true,
        trackKind: 'auto-translated',
      };
  }
  // 7. Auto-gen en
  {
    const hit = autoLangs.find((l) => l === 'en' || l.startsWith('en-'));
    if (hit) return { lang: hit, includeAutoGenerated: true, trackKind: 'asr' };
  }

  return null;
}

export const ingestVideoLink = internalAction({
  args: {
    jobId: v.id('videoLinkJobs'),
    userLocale: v.optional(v.string()),
  },
  async handler(ctx, args) {
    const job = await ctx.runQuery(
      internal.video_links.internal_queries.getJobById,
      {
        jobId: args.jobId,
      },
    );
    if (!job) return;
    if (job.status === 'skipped' || job.status === 'failed') {
      // Cancelled before this action started. Nothing to do.
      return;
    }

    /** Re-read the job and bail if it's been cancelled mid-flight. */
    const assertNotCancelled = async (): Promise<boolean> => {
      const fresh = await ctx.runQuery(
        internal.video_links.internal_queries.getJobById,
        {
          jobId: args.jobId,
        },
      );
      return !fresh || fresh.status !== 'skipped';
    };

    const { jobDir, cleanup } = await createJobDir();

    const fail = async (reasonCode: string, message: string): Promise<void> => {
      console.error(
        JSON.stringify({
          event: 'video_link.failed',
          jobId: args.jobId,
          orgId: job.organizationId,
          threadId: job.threadId,
          sourceUrlHash: job.sourceUrlHash,
          sourcePlatform: job.sourcePlatform,
          reason: reasonCode,
          message,
        }),
      );
      await ctx.runMutation(internal.video_links.internal_mutations.updateJob, {
        jobId: args.jobId,
        status: 'failed',
        errorReasonCode: reasonCode,
        errorMessage: message.slice(0, 500),
        progress: undefined,
      });
    };

    try {
      // -----------------------------------------------------------------
      // Phase A: yt-dlp -j metadata
      // -----------------------------------------------------------------
      try {
        await assertSafeUrl(job.sourceUrl);
      } catch (err) {
        if (err instanceof UrlSafetyError) {
          await fail(err.kind, err.message);
          return;
        }
        throw err;
      }

      await ctx.runMutation(internal.video_links.internal_mutations.updateJob, {
        jobId: args.jobId,
        status: 'fetching_metadata',
      });
      if (!(await assertNotCancelled())) return;

      let metadata: YtDlpMetadata;
      try {
        metadata = await ytdlpJson(job.sourceUrl, jobDir);
      } catch (err) {
        await handleYtDlpError(ctx, args.jobId, job, err, fail);
        return;
      }

      // Reject live / upcoming / oversized BEFORE any download.
      if (metadata.is_live || metadata.live_status === 'is_live') {
        await fail('live_stream', 'Live streams are not supported');
        return;
      }
      if (metadata.live_status === 'is_upcoming') {
        await fail('premiere', 'Premiere/upcoming video not yet available');
        return;
      }
      if (
        typeof metadata.duration === 'number' &&
        metadata.duration > CHAT_AUDIO_MAX_DURATION_SEC
      ) {
        await fail(
          'videoTooLong',
          `Video duration ${Math.round(metadata.duration)}s exceeds ${CHAT_AUDIO_MAX_DURATION_SEC}s limit`,
        );
        return;
      }

      const chapters =
        metadata.chapters?.map((c) => ({
          startSec: c.start_time,
          endSec: c.end_time,
          title: c.title,
        })) ?? [];

      await ctx.runMutation(internal.video_links.internal_mutations.updateJob, {
        jobId: args.jobId,
        videoTitle: metadata.title ?? undefined,
        videoUploader: metadata.uploader ?? metadata.channel ?? undefined,
        videoDurationSec: metadata.duration,
        videoLanguage: metadata.language ?? undefined,
        ...(chapters.length > 0 ? { videoChapters: chapters } : {}),
      });

      console.log(
        JSON.stringify({
          event: 'video_link.metadata_fetched',
          jobId: args.jobId,
          orgId: job.organizationId,
          duration: metadata.duration,
          sourcePlatform: job.sourcePlatform,
          availableManualLangs: Object.keys(metadata.subtitles ?? {}).length,
          availableAutoLangs: Object.keys(metadata.automatic_captions ?? {})
            .length,
        }),
      );

      // -----------------------------------------------------------------
      // Phase B: caption selection + fetch
      // -----------------------------------------------------------------
      const selection = selectCaptionLanguage(metadata, args.userLocale);

      if (selection) {
        await ctx.runMutation(
          internal.video_links.internal_mutations.updateJob,
          {
            jobId: args.jobId,
            status: 'fetching_captions',
            captionLang: selection.lang,
            captionTrackKind: selection.trackKind,
          },
        );
        if (!(await assertNotCancelled())) return;

        let vttPath: string | null = null;
        try {
          vttPath = await ytdlpWriteSubs(
            job.sourceUrl,
            selection.lang,
            jobDir,
            {
              includeAutoGenerated: selection.includeAutoGenerated,
            },
          );
        } catch (err) {
          // Caption fetch failure ≠ feature failure — fall through to
          // Whisper. Log + continue.
          console.warn(
            JSON.stringify({
              event: 'video_link.captions_miss',
              jobId: args.jobId,
              reason: err instanceof YtDlpError ? err.reason : 'parse_failed',
            }),
          );
          vttPath = null;
        }

        if (vttPath) {
          const buf = await fs.readFile(vttPath);
          const segments = rollingWindowDedup(parseVtt(buf));
          if (segments.length > 0) {
            const transcriptBody = joinSegmentsWithParagraphs(
              captionsToParagraphSegments(segments),
              '',
              { profile: CAPTION_PROFILE, addTimestamps: true },
            );

            if (transcriptBody.length > 0) {
              await ctx.runMutation(
                internal.video_links.internal_mutations.updateJob,
                { jobId: args.jobId, status: 'indexing' },
              );
              if (!(await assertNotCancelled())) return;

              // Prepend chapter TOC when chapters are present — agent
              // can cite "Chapter 3: …" in summaries.
              const chapterToc =
                chapters.length > 0
                  ? 'Chapters:\n' +
                    chapters
                      .map((c) => `  ${formatHms(c.startSec)} ${c.title}`)
                      .join('\n') +
                    '\n\n'
                  : '';
              const fullTranscript = chapterToc + transcriptBody;

              const blob = new Blob([fullTranscript], {
                type: 'text/plain; charset=utf-8',
              });
              const storageId = await ctx.storage.store(blob);

              await ctx.runMutation(
                internal.video_links.internal_mutations
                  .insertSyntheticFileMetadata,
                {
                  jobId: args.jobId,
                  storageId,
                  transcript: fullTranscript,
                  fileSize: blob.size,
                  videoTitle: metadata.title ?? 'Untitled video',
                  videoUploader:
                    metadata.uploader ?? metadata.channel ?? undefined,
                  videoDurationSec: metadata.duration ?? 0,
                  sourceUrl: job.sourceUrl,
                  sourcePlatform: job.sourcePlatform,
                  transcriptSource:
                    selection.trackKind === 'manual'
                      ? 'captions_human'
                      : 'captions_auto',
                  captionLang: selection.lang,
                  threadId: job.threadId,
                  organizationId: job.organizationId,
                  uploadedBy: job.uploadedBy,
                },
              );

              console.log(
                JSON.stringify({
                  event: 'video_link.completed',
                  jobId: args.jobId,
                  orgId: job.organizationId,
                  source: 'captions',
                  trackKind: selection.trackKind,
                  lang: selection.lang,
                }),
              );
              return;
            }
          }
        }
      }

      // -----------------------------------------------------------------
      // Phase C: captions missed → Whisper fallback via audio extract
      // -----------------------------------------------------------------
      await ctx.runMutation(internal.video_links.internal_mutations.updateJob, {
        jobId: args.jobId,
        status: 'extracting_audio',
      });
      if (!(await assertNotCancelled())) return;

      let audioPath: string;
      try {
        audioPath = await ytdlpExtractAudio(job.sourceUrl, jobDir);
      } catch (err) {
        await handleYtDlpError(ctx, args.jobId, job, err, fail);
        return;
      }

      if (!(await assertNotCancelled())) return;

      const audioBuf = await fs.readFile(audioPath);
      const audioBlob = new Blob([audioBuf], { type: 'audio/ogg' });
      const audioStorageId = await ctx.storage.store(audioBlob);

      // Internal variant (not the public `api.file_metadata.mutations.*`).
      // Scheduled actions run with no user context — the public mutation
      // calls `authComponent.getAuthUser(ctx)` which throws Unauthenticated.
      // The internal variant accepts uploadedBy + threadId as explicit args
      // and handles the same insert + transcribe_audio scheduling.
      // Capture the returned fileMetadataId — without it, the chip's
      // reactive join in queries.ts:projectJob can't read through to
      // transcriptionStatus/transcriptionProgress, so the chip would
      // stay stuck at the literal "Transcribing…" i18n string with no
      // progress and no failure surfacing.
      const fileMetadataId = await ctx.runMutation(
        internal.file_metadata.internal_mutations.saveFileMetadata,
        {
          organizationId: job.organizationId,
          storageId: audioStorageId,
          fileName: `${metadata.title ?? 'video'}.ogg`,
          contentType: 'audio/ogg',
          size: audioBlob.size,
          source: 'user',
          uploadedBy: job.uploadedBy,
          ...(job.threadId !== undefined && { threadId: job.threadId }),
          sourceUrl: job.sourceUrl,
          sourcePlatform: job.sourcePlatform,
          ...(metadata.title ? { videoTitle: metadata.title } : {}),
          ...(metadata.uploader || metadata.channel
            ? { videoUploader: metadata.uploader ?? metadata.channel }
            : {}),
          ...(typeof metadata.duration === 'number'
            ? { videoDurationSec: metadata.duration }
            : {}),
        },
      );

      await ctx.runMutation(internal.video_links.internal_mutations.updateJob, {
        jobId: args.jobId,
        status: 'transcribing_handoff',
        storageId: audioStorageId,
        fileMetadataId,
        transcriptSource: 'whisper',
      });

      console.log(
        JSON.stringify({
          event: 'video_link.transcribing_handoff',
          jobId: args.jobId,
          orgId: job.organizationId,
          audioStorageId,
          audioBytes: audioBlob.size,
        }),
      );

      // From here on, the chip's reactive query joins fileMetadata's
      // transcriptionStatus and projects it as displayStatus. We don't
      // wait for Whisper to complete — when transcribe_audio.ts finishes,
      // the chip flips to 'completed' purely through Convex reactivity.
    } finally {
      await cleanup();
    }
  },
});

async function handleYtDlpError(
  ctx: ActionCtx,
  jobId: Id<'videoLinkJobs'>,
  job: { attempts?: number },
  err: unknown,
  fail: (reasonCode: string, message: string) => Promise<void>,
): Promise<void> {
  if (err instanceof YtDlpError) {
    const attempts = (job.attempts ?? 0) + 1;
    if (NEVER_RETRY.has(err.reason) || attempts >= MAX_ATTEMPTS) {
      await fail(err.reason, err.sanitizedStderr || err.message);
      return;
    }
    // Schedule retry with backoff
    const delayMs =
      INGEST_RETRY_DELAYS_MS[
        Math.min(attempts - 1, INGEST_RETRY_DELAYS_MS.length - 1)
      ];
    await ctx.runMutation(internal.video_links.internal_mutations.updateJob, {
      jobId,
      status: 'queued',
      errorReasonCode: err.reason,
      errorMessage: err.sanitizedStderr.slice(0, 500),
    });
    await ctx.scheduler.runAfter(
      delayMs,
      internal.video_links.ingest_video_link.ingestVideoLink,
      { jobId, userLocale: undefined },
    );
    console.warn(
      JSON.stringify({
        event: 'video_link.retrying',
        jobId,
        attempts,
        delayMs,
        reason: err.reason,
      }),
    );
    return;
  }
  const message = err instanceof Error ? err.message : String(err);
  await fail('transient', message);
}

function formatHms(totalSec: number): string {
  const s = Math.max(0, Math.floor(totalSec));
  const hh = Math.floor(s / 3600);
  const mm = Math.floor((s % 3600) / 60);
  const ss = s % 60;
  return (
    String(hh).padStart(2, '0') +
    ':' +
    String(mm).padStart(2, '0') +
    ':' +
    String(ss).padStart(2, '0')
  );
}
