/**
 * LIVE multi-link transcript extraction — proves the shipped ingest transcript
 * path yields a real, de-duplicated transcript across DIFFERENT link SHAPES and
 * content types, not just the single video `ytdlp_live.test.ts` covers.
 *
 * Runs the ACTUAL `yt-dlp` binary and the SHIPPED parser (`parseVtt` +
 * `rollingWindowDedup`) — the same code the video-link ingest pipeline runs —
 * for a full `watch?v=` link, a `youtu.be/` short link, and a separate
 * spoken-word video. No LLM / external paid API is involved; whether the model
 * then answers correctly from a transcript is the RAG retrieval pipeline's
 * concern, proved hermetically in `tests/external-db-retrieval`.
 *
 * Gated behind `YOUTUBE_LIVE_TEST=1` (same as `ytdlp_live.test.ts`): the
 * toolchain provisioning + network calls never fire in the ordinary suite.
 * Audio-only YouTube content is covered here via its auto-captions (the common
 * path); the no-captions Whisper path needs an audio transcription provider and
 * is out of scope for this test.
 */
import { mkdtemp, readFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';

import { beforeAll, describe, expect, it } from 'vitest';

import { parseVtt, rollingWindowDedup } from './captions_parser';
import { ytdlpJson, ytdlpWriteSubs, type YtDlpMetadata } from './ytdlp';
import { ensureVideoToolchain } from './ytdlp_toolchain';

const LIVE = process.env.YOUTUBE_LIVE_TEST === '1';

async function withRetries<T>(fn: () => Promise<T>, attempts = 3): Promise<T> {
  let lastErr: unknown;
  for (let i = 0; i < attempts; i++) {
    try {
      return await fn();
    } catch (err) {
      lastErr = err;
      await new Promise((r) => setTimeout(r, 2000 * (i + 1)));
    }
  }
  throw lastErr;
}

function captionLangs(meta: YtDlpMetadata): string[] {
  return [
    ...Object.keys(meta.automatic_captions ?? {}),
    ...Object.keys(meta.subtitles ?? {}),
  ];
}

/** The real ingest transcript path: metadata → pick lang → write subs → parse
 *  the VTT with the shipped parser → rolling-window dedup → joined plain text. */
async function transcriptOf(url: string): Promise<string> {
  const jobDir = await mkdtemp(join(tmpdir(), 'ytmulti-'));
  const meta = await withRetries(() => ytdlpJson(url, jobDir, 90_000));
  const langs = captionLangs(meta);
  const lang =
    langs.find((l) => l === 'en') ??
    langs.find((l) => l.startsWith('en')) ??
    langs[0];
  expect(lang, `no caption track for ${url}`).toBeTruthy();
  const vttPath = await withRetries(() =>
    ytdlpWriteSubs(url, lang, jobDir, {
      includeAutoGenerated: true,
      timeoutMs: 90_000,
    }),
  );
  const vtt = await readFile(vttPath as string, 'utf8');
  const segments = rollingWindowDedup(parseVtt(vtt));
  return segments
    .map((s) => s.text)
    .join(' ')
    .replace(/\s+/g, ' ')
    .trim();
}

const RICK_WATCH = 'https://www.youtube.com/watch?v=dQw4w9WgXcQ';
const RICK_SHORT = 'https://youtu.be/dQw4w9WgXcQ';
// "Me at the zoo" — the first YouTube video: 19s, spoken word, stable
// auto-captions about elephants and their long trunks.
const ZOO_WATCH = 'https://www.youtube.com/watch?v=jNQXAC9IVRw';

describe.skipIf(!LIVE)('yt-dlp live multi-link transcript extraction', () => {
  beforeAll(async () => {
    const tc = await ensureVideoToolchain();
    process.env.VIDEO_INGEST_BIN_DIR = tc.binDir;
    process.env.VIDEO_INGEST_FFMPEG_LOCATION = tc.ffmpegLocation;
    process.env.VIDEO_INGEST_YTDLP_PLUGIN_DIRS ||= tc.pluginDir;
  }, 600_000);

  it('extracts a real transcript from a full watch?v= link (music/audio video)', async () => {
    const t = await transcriptOf(RICK_WATCH);
    expect(t.split(/\s+/).length).toBeGreaterThan(50);
    expect(t.toLowerCase()).toContain('give you up');
  }, 180_000);

  it('extracts the same transcript from a youtu.be short link', async () => {
    const t = await transcriptOf(RICK_SHORT);
    expect(t.toLowerCase()).toContain('give you up');
  }, 180_000);

  it('extracts a real transcript from a different, spoken-word video', async () => {
    const t = await transcriptOf(ZOO_WATCH);
    expect(t.split(/\s+/).length).toBeGreaterThan(10);
    expect(t.toLowerCase()).toMatch(/elephant|trunk/);
  }, 180_000);
});
