/**
 * LIVE YouTube-ingestion test — proves the real anti-bot path end to end by
 * running the ACTUAL `yt-dlp` binary against a real video with the shipped
 * `buildAntiBotFlags` config (via `ytdlpJson` / `ytdlpWriteSubs`). It asserts
 * we get past YouTube's bot wall and pull a non-empty transcript.
 *
 * Gated behind `YOUTUBE_LIVE_TEST=1` so it is SKIPPED in the ordinary unit
 * suite and RUN only where the toolchain + a suitable egress exist: the `Unit`
 * job in `.github/workflows/test.yml` (which sets the flag + a bgutil PO-token
 * provider) and any developer who opts in locally. GitHub runners are DATACENTER
 * IPs — the exact environment where YouTube's "confirm you're not a bot" wall
 * appears — so a green CI run is the real proof that ingestion works from a
 * server, not just from a residential laptop.
 *
 * SELF-PROVISIONING: `yt-dlp`, `deno` (JS-challenge solver), `ffmpeg` (subtitle
 * conversion), and the bgutil PO-token plugin are NO LONGER installed by a
 * workflow step. The `beforeAll` below calls `ensureVideoToolchain()` to
 * download/resolve them into a per-user cache and points `ytdlp.ts` at them via
 * `VIDEO_INGEST_BIN_DIR` / `VIDEO_INGEST_FFMPEG_LOCATION` /
 * `VIDEO_INGEST_YTDLP_PLUGIN_DIRS` — so the very same test runs on a bare CI
 * runner and on a laptop. It stays gated behind `YOUTUBE_LIVE_TEST=1`; the
 * provisioning + network calls never fire in the normal suite.
 */
import { readFile } from 'node:fs/promises';
import { mkdtemp } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';

import { beforeAll, describe, expect, it } from 'vitest';

import { ytdlpJson, ytdlpWriteSubs, type YtDlpMetadata } from './ytdlp';
import { ensureVideoToolchain } from './ytdlp_toolchain';

const LIVE = process.env.YOUTUBE_LIVE_TEST === '1';

// Rick Astley — "Never Gonna Give You Up". Chosen for extreme longevity and
// stable English auto-captions; unlikely to be removed or age-gated.
const VIDEO_URL = 'https://www.youtube.com/watch?v=dQw4w9WgXcQ';

/** Retry a flaky network step a couple of times before failing the run. */
async function withRetries<T>(fn: () => Promise<T>, attempts = 3): Promise<T> {
  let lastErr: unknown;
  for (let i = 0; i < attempts; i++) {
    try {
      return await fn();
    } catch (err) {
      lastErr = err;
      // Short backoff; yt-dlp also retries internally.
      await new Promise((r) => setTimeout(r, 2000 * (i + 1)));
    }
  }
  throw lastErr;
}

function captionLangs(meta: YtDlpMetadata): string[] {
  return [
    ...Object.keys(meta.automatic_captions ?? {}),
    ...Object.keys(meta.subtitles ?? {}),
  ];
}

describe.skipIf(!LIVE)(
  'yt-dlp live YouTube ingestion (datacenter-IP anti-bot)',
  () => {
    // Download/resolve the yt-dlp + deno + ffmpeg + bgutil toolchain and point
    // `ytdlp.ts` at it. Lives inside the gated `describe` so it NEVER runs (nor
    // touches the network) in the ordinary suite. Generous timeout: a cold cache
    // downloads two binaries and may `brew install ffmpeg` on a fresh laptop.
    beforeAll(async () => {
      const tc = await ensureVideoToolchain();
      process.env.VIDEO_INGEST_BIN_DIR = tc.binDir;
      process.env.VIDEO_INGEST_FFMPEG_LOCATION = tc.ffmpegLocation;
      // `||=`: honour an explicit plugin dir (e.g. the CI baked path) if set.
      process.env.VIDEO_INGEST_YTDLP_PLUGIN_DIRS ||= tc.pluginDir;
    }, 600_000);

    it('fetches video metadata past the bot wall', async () => {
      const jobDir = await mkdtemp(join(tmpdir(), 'ytlive-meta-'));
      const meta = await withRetries(() =>
        ytdlpJson(VIDEO_URL, jobDir, 90_000),
      );

      expect(meta.id).toBeTruthy();
      expect(meta.title).toBeTruthy();
      // A caption/transcript track must be advertised — proves we reached the
      // player API, not just a bot-wall interstitial.
      expect(captionLangs(meta).length).toBeGreaterThan(0);
    }, 150_000);

    it('pulls a non-empty English transcript', async () => {
      const jobDir = await mkdtemp(join(tmpdir(), 'ytlive-subs-'));
      const meta = await withRetries(() =>
        ytdlpJson(VIDEO_URL, jobDir, 90_000),
      );

      // Prefer a plain `en` track; else the first advertised caption language.
      const langs = captionLangs(meta);
      const lang =
        langs.find((l) => l === 'en') ??
        langs.find((l) => l.startsWith('en')) ??
        langs[0];
      expect(lang).toBeTruthy();

      const vttPath = await withRetries(() =>
        ytdlpWriteSubs(VIDEO_URL, lang, jobDir, {
          includeAutoGenerated: true,
          timeoutMs: 90_000,
        }),
      );
      expect(vttPath).toBeTruthy();

      const vtt = await readFile(vttPath as string, 'utf8');
      // Strip the WEBVTT header, cue timings, and markup; assert real words
      // remain — a genuine transcript, not an empty or header-only file.
      const words = vtt
        .replace(/WEBVTT|Kind:[^\n]*|Language:[^\n]*/g, '')
        .replace(/\d{2}:\d{2}:\d{2}\.\d{3}\s*-->.*$/gm, '')
        .replace(/<[^>]*>/g, '')
        .replace(/[^A-Za-z]+/g, ' ')
        .trim();
      expect(words.length).toBeGreaterThan(50);
    }, 180_000);
  },
);
