/**
 * LIVE YouTube-ingestion test — proves the real anti-bot path end to end by
 * running the ACTUAL `yt-dlp` binary against a real video with the shipped
 * `buildAntiBotFlags` config (via `ytdlpJson` / `ytdlpWriteSubs`). It asserts
 * we get past YouTube's bot wall and pull a non-empty transcript.
 *
 * Gated behind `YOUTUBE_LIVE_TEST=1` so it is SKIPPED in the ordinary unit
 * suite (which has no `yt-dlp`) and RUN only by the dedicated
 * `.github/workflows/youtube-ingest.yml` job. That job runs on GitHub's
 * datacenter IPs — i.e. the exact environment where YouTube's "confirm you're
 * not a bot" wall appears — so a green run there is the real proof that
 * ingestion works from a server, not just from a residential laptop.
 *
 * Requires `yt-dlp`, `deno` (JS-challenge solver), and `ffmpeg` (subtitle
 * conversion) on PATH — the workflow installs them.
 */
import { readFile } from 'node:fs/promises';
import { mkdtemp } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';

import { describe, expect, it } from 'vitest';

import { ytdlpJson, ytdlpWriteSubs, type YtDlpMetadata } from './ytdlp';

const LIVE = process.env.YOUTUBE_LIVE_TEST === '1';

// Rick Astley — "Never Gonna Give You Up". Chosen for extreme longevity and
// stable English auto-captions; unlikely to be removed or age-gated.
const VIDEO_URL = 'https://www.youtube.com/watch?v=dQw4w9WgXcQ';

/** Retry a flaky network step a couple of times before failing the run. */
async function withRetries<T>(fn: () => Promise<T>, attempts = 3): Promise<T> {
  let lastErr: unknown;
  for (let i = 0; i < attempts; i++) {
    try {
      return await fn();
    } catch (err) {
      lastErr = err;
      // Short backoff; yt-dlp also retries internally.
      await new Promise((r) => setTimeout(r, 2000 * (i + 1)));
    }
  }
  throw lastErr;
}

function captionLangs(meta: YtDlpMetadata): string[] {
  return [
    ...Object.keys(meta.automatic_captions ?? {}),
    ...Object.keys(meta.subtitles ?? {}),
  ];
}

describe.skipIf(!LIVE)(
  'yt-dlp live YouTube ingestion (datacenter-IP anti-bot)',
  () => {
    it('fetches video metadata past the bot wall', async () => {
      const jobDir = await mkdtemp(join(tmpdir(), 'ytlive-meta-'));
      const meta = await withRetries(() =>
        ytdlpJson(VIDEO_URL, jobDir, 90_000),
      );

      expect(meta.id).toBeTruthy();
      expect(meta.title).toBeTruthy();
      // A caption/transcript track must be advertised — proves we reached the
      // player API, not just a bot-wall interstitial.
      expect(captionLangs(meta).length).toBeGreaterThan(0);
    }, 150_000);

    it('pulls a non-empty English transcript', async () => {
      const jobDir = await mkdtemp(join(tmpdir(), 'ytlive-subs-'));
      const meta = await withRetries(() =>
        ytdlpJson(VIDEO_URL, jobDir, 90_000),
      );

      // Prefer a plain `en` track; else the first advertised caption language.
      const langs = captionLangs(meta);
      const lang =
        langs.find((l) => l === 'en') ??
        langs.find((l) => l.startsWith('en')) ??
        langs[0];
      expect(lang).toBeTruthy();

      const vttPath = await withRetries(() =>
        ytdlpWriteSubs(VIDEO_URL, lang, jobDir, {
          includeAutoGenerated: true,
          timeoutMs: 90_000,
        }),
      );
      expect(vttPath).toBeTruthy();

      const vtt = await readFile(vttPath as string, 'utf8');
      // Strip the WEBVTT header, cue timings, and markup; assert real words
      // remain — a genuine transcript, not an empty or header-only file.
      const words = vtt
        .replace(/WEBVTT|Kind:[^\n]*|Language:[^\n]*/g, '')
        .replace(/\d{2}:\d{2}:\d{2}\.\d{3}\s*-->.*$/gm, '')
        .replace(/<[^>]*>/g, '')
        .replace(/[^A-Za-z]+/g, ' ')
        .trim();
      expect(words.length).toBeGreaterThan(50);
    }, 180_000);
  },
);
