// @vitest-environment node

/**
 * The caption ladder is fidelity-first: the video's own language beats the
 * reader's, a human track beats an ASR one, and a machine translation is the
 * last thing it should ever reach for. It had never been tested, and the
 * source-language rungs were dead — they compared a track folded to its base
 * language against an UNFOLDED `meta.language`, so `en-US` never matched the
 * `en` track YouTube actually serves.
 *
 * What that cost, observed on a real job: an English video, a reader whose UI
 * is Chinese, and the ingest fetched the Chinese MACHINE TRANSLATION — from
 * the one caption endpoint YouTube rate-limits hard, while the English ASR
 * track sat one rung up and downloads instantly.
 */

import { describe, expect, it } from 'vitest';

import { selectCaptionLanguage } from './ingest_video_link';
import type { YtDlpMetadata } from './ytdlp';

function meta(fields: {
  language?: string;
  subtitles?: string[];
  automatic_captions?: string[];
}): YtDlpMetadata {
  const asTracks = (langs: string[] | undefined): Record<string, unknown> =>
    Object.fromEntries((langs ?? []).map((l) => [l, []]));
  return {
    ...(fields.language !== undefined && { language: fields.language }),
    subtitles: asTracks(fields.subtitles),
    automatic_captions: asTracks(fields.automatic_captions),
  } as unknown as YtDlpMetadata;
}

describe('selectCaptionLanguage', () => {
  it('takes the source-language track when the video reports a region subtag', () => {
    // Verbatim shape of https://www.youtube.com/watch?v=RfvJh4LQ0DM: language
    // `en-US`, no manual tracks, 157 auto tracks including a native `en`.
    const video = meta({
      language: 'en-US',
      automatic_captions: ['en', 'zh-Hans', 'zh-Hant', 'de', 'fr'],
    });

    // Whoever is reading, the English original wins. Before the fix each of
    // these fell to the reader's own language as a machine translation.
    for (const locale of [undefined, 'zh-CN', 'de-DE', 'en-US']) {
      expect(selectCaptionLanguage(video, locale)).toEqual({
        lang: 'en',
        includeAutoGenerated: true,
        trackKind: 'asr',
      });
    }
  });

  it('holds for a non-English source too', () => {
    const video = meta({
      language: 'pt-BR',
      automatic_captions: ['pt', 'en', 'es'],
    });
    expect(selectCaptionLanguage(video, 'en-US')).toEqual({
      lang: 'pt',
      includeAutoGenerated: true,
      trackKind: 'asr',
    });
  });

  it('prefers the exact tag over a sibling in the same language', () => {
    const video = meta({
      language: 'en',
      subtitles: ['en-gb', 'en'],
    });
    expect(selectCaptionLanguage(video, undefined)?.lang).toBe('en');
  });

  it('takes a human track over the source-language ASR one', () => {
    const video = meta({
      language: 'en-US',
      subtitles: ['en'],
      automatic_captions: ['en'],
    });
    expect(selectCaptionLanguage(video, undefined)).toEqual({
      lang: 'en',
      includeAutoGenerated: false,
      trackKind: 'manual',
    });
  });

  it('accepts the vendor-suffixed track shape Vimeo serves', () => {
    // `player.vimeo.com` advertises its ASR track as `en-x-autogen`, which
    // must fold to `en` like any other regional tag.
    const video = meta({ language: 'en', subtitles: ['en-x-autogen'] });
    expect(selectCaptionLanguage(video, undefined)).toEqual({
      lang: 'en-x-autogen',
      includeAutoGenerated: false,
      trackKind: 'manual',
    });
  });

  it("still reaches the reader's language when the source has no track", () => {
    // The machine translation is a real rung — just the LAST one before
    // English, not the first one past a source track that exists.
    const video = meta({
      language: 'ja',
      automatic_captions: ['zh-Hans', 'en'],
    });
    expect(selectCaptionLanguage(video, 'zh-CN')).toEqual({
      lang: 'zh-hans',
      includeAutoGenerated: true,
      trackKind: 'auto-translated',
    });
  });

  it('returns null when the video carries no captions at all', () => {
    expect(selectCaptionLanguage(meta({ language: 'en' }), 'en')).toBeNull();
  });
});
