// @vitest-environment node

/**
 * The structural diff on every automation document the repository ships
 * (`selftest/corpus.ts`): each document against a copy with one change of
 * each kind — a template, a code body, a condition, a data field, a node
 * added, removed, renamed or retyped, the run input's schema, the output, the
 * description, the tests, and two changes the diff must not see (`ui`, the
 * order of the nodes).
 *
 *  1. every change summary is the reviewed one in corpus.snapshot.yml;
 *  2. the diff stays within its budget: under 5 ms per pair, the largest
 *     shipped document included (the median of repeated runs, so a busy
 *     machine's one slow sample does not decide).
 *
 * After an intentional change, regenerate the snapshot with
 *
 *   DIFF_CORPUS_UPDATE=1 bunx vitest run lib/engine/core/diff/corpus
 *
 * and review the diff.
 */

import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

import { describe, expect, it } from 'vitest';
import { parse, stringify } from 'yaml';

import { shippedDocuments } from '../../selftest/corpus';
import { diffAutomationDocuments } from './automation';
import { changeSummaryOf } from './changes';

type Doc = Record<string, unknown>;
type Node = Record<string, unknown>;

const SNAPSHOT_PATH = fileURLToPath(
  new URL('corpus.snapshot.yml', import.meta.url),
);

const HEADER = `# The change summary of every shipped automation document against a copy
# with one change of each kind — generated by corpus.test.ts. "n/a": the
# document has nothing that change applies to.
#
# Never edit this file by hand: change the diff or the documents, review the
# diff, and regenerate with
#   DIFF_CORPUS_UPDATE=1 bunx vitest run lib/engine/core/diff/corpus
`;

/** The budget per pair of documents. */
const BUDGET_MS = 5;

function nodesOf(doc: Doc): Node[] {
  return Array.isArray(doc.nodes) ? (doc.nodes as Node[]) : [];
}

/** Every string of `value` passed through `fn`. */
function mapStrings(value: unknown, fn: (text: string) => string): unknown {
  if (typeof value === 'string') return fn(value);
  if (Array.isArray(value)) return value.map((each) => mapStrings(each, fn));
  if (value !== null && typeof value === 'object') {
    return Object.fromEntries(
      Object.entries(value).map(([key, each]) => [key, mapStrings(each, fn)]),
    );
  }
  return value;
}

/** `doc` with node `from` called `to`, every template reference following —
 * the oracle a test may write with a pattern; the diff never does. */
function renameNode(doc: Doc, from: string, to: string): Doc {
  const pattern = new RegExp(`\\bnodes\\.${from}\\b`, 'g');
  const renamed = mapStrings(doc, (text) =>
    text.includes('{{') || text.includes('nodes.')
      ? text.replace(pattern, `nodes.${to}`)
      : text,
  ) as Doc;
  for (const node of nodesOf(renamed)) {
    if (node.id === from) node.id = to;
    if (node.elseOf === from) node.elseOf = to;
  }
  return renamed;
}

/** The first node `pick` accepts, in a copy of `doc`. */
function withNode(
  doc: Doc,
  pick: (node: Node) => boolean,
  edit: (node: Node, copy: Doc) => void,
): Doc | null {
  const copy = structuredClone(doc);
  const node = nodesOf(copy).find(pick);
  if (node === undefined) return null;
  edit(node, copy);
  return copy;
}

const MUTATIONS: ReadonlyArray<readonly [string, (doc: Doc) => Doc | null]> = [
  [
    'template',
    (doc) =>
      withNode(
        doc,
        (node) => typeof node.prompt === 'string',
        (node) => {
          node.prompt = `${String(node.prompt)}\nBe brief.`;
        },
      ),
  ],
  [
    'code',
    (doc) =>
      withNode(
        doc,
        (node) => typeof node.code === 'string',
        (node) => {
          node.code = `// reviewed\n${String(node.code)}`;
        },
      ),
  ],
  [
    'condition',
    (doc) => {
      const last = nodesOf(doc).at(-1)?.id;
      return withNode(
        doc,
        (node) => node.id === last,
        (node) => {
          node.when = '{{ input.enabled !== false }}';
        },
      );
    },
  ],
  [
    'data',
    (doc) =>
      withNode(
        doc,
        (node) => node.input !== null && typeof node.input === 'object',
        (node) => {
          node.input = { ...(node.input as Doc), reviewed: true };
        },
      ),
  ],
  [
    'add node',
    (doc) => {
      const copy = structuredClone(doc);
      nodesOf(copy).push({ id: 'audit', type: 'transform', code: 'return 1;' });
      return copy;
    },
  ],
  [
    'remove node',
    (doc) => {
      const copy = structuredClone(doc);
      nodesOf(copy).pop();
      return copy;
    },
  ],
  [
    'rename node',
    (doc) => {
      // The node others read most, so the rename has readers to fold.
      const nodes = nodesOf(doc);
      const text = JSON.stringify(doc);
      const target = nodes
        .map((node) => String(node.id))
        .toSorted(
          (a, b) =>
            text.split(`nodes.${b}`).length - text.split(`nodes.${a}`).length,
        )[0];
      return target === undefined
        ? null
        : renameNode(doc, target, `${target}_v2`);
    },
  ],
  [
    'retype node',
    (doc) =>
      withNode(
        doc,
        (node) => node.type !== 'transform',
        (node) => {
          node.type = 'transform';
        },
      ),
  ],
  [
    'inputs',
    (doc) => {
      const copy = structuredClone(doc);
      const inputs = (copy.inputs ?? { type: 'object' }) as Doc;
      inputs.properties = {
        ...(inputs.properties as Doc | undefined),
        reviewer: { type: 'string', description: 'Who reviews the result' },
      };
      copy.inputs = inputs;
      return copy;
    },
  ],
  [
    'output',
    (doc) => {
      const copy = structuredClone(doc);
      copy.output = { result: copy.output ?? null, reviewed: true };
      return copy;
    },
  ],
  [
    'description',
    (doc) => {
      const copy = structuredClone(doc);
      const text = typeof copy.description === 'string' ? copy.description : '';
      copy.description = `${text} Reviewed.`.trim();
      return copy;
    },
  ],
  [
    'tests',
    (doc) => {
      const copy = structuredClone(doc);
      copy.tests = [
        ...((copy.tests as unknown[] | undefined) ?? []),
        { name: 'reviewed', input: {} },
      ];
      return copy;
    },
  ],
  [
    'ui only',
    (doc) => {
      const copy = structuredClone(doc);
      copy.ui = { positions: { moved: { x: 10, y: 20 } } };
      return copy;
    },
  ],
  [
    'node order',
    (doc) => {
      const copy = structuredClone(doc);
      copy.nodes = nodesOf(copy).toReversed();
      return copy;
    },
  ],
];

const documents = shippedDocuments();

const pairs = documents.flatMap(({ label, document }) =>
  MUTATIONS.map(([mutation, mutate]) => ({
    label,
    mutation,
    before: document,
    after: mutate(document),
  })),
);

function summaries(): Record<string, Record<string, string>> {
  const out: Record<string, Record<string, string>> = {};
  for (const { label, mutation, before, after } of pairs) {
    out[label] ??= {};
    // One line of JSON per pair keeps the reviewed file short to read.
    out[label][mutation] =
      after === null
        ? 'n/a'
        : JSON.stringify(
            changeSummaryOf(diffAutomationDocuments(before, after)),
          );
  }
  return out;
}

function medianMs(run: () => void, samples: number): number {
  const times: number[] = [];
  for (let at = 0; at < samples; at += 1) {
    const started = performance.now();
    run();
    times.push(performance.now() - started);
  }
  times.sort((a, b) => a - b);
  return times[Math.floor(times.length / 2)] ?? 0;
}

describe('the structural diff on the shipped corpus', () => {
  it('covers every kind of shipped document', () => {
    const labels = documents.map(({ label }) => label);
    expect(labels.filter((label) => label.startsWith('pack ')).length).toBe(10);
    expect(labels).toContain('get_docs example');
    expect(labels).toContain('blank wizard scaffold');
    expect(labels.some((label) => label.startsWith('docs '))).toBe(true);
  });

  it('summarizes every change as reviewed', () => {
    const actual = summaries();
    if (process.env.DIFF_CORPUS_UPDATE === '1') {
      writeFileSync(
        SNAPSHOT_PATH,
        HEADER + stringify(actual, { lineWidth: 0, singleQuote: true }),
      );
      return;
    }
    const snapshot: unknown = parse(readFileSync(SNAPSHOT_PATH, 'utf8'));
    expect(actual).toEqual(snapshot);
  });

  it('reads no change where only ui or the node order differ', () => {
    for (const { mutation, before, after } of pairs) {
      if (after === null) continue;
      if (mutation !== 'ui only' && mutation !== 'node order') continue;
      expect(diffAutomationDocuments(before, after).identical).toBe(true);
    }
  });

  it(`diffs each pair in under ${BUDGET_MS} ms`, () => {
    const timed = pairs.flatMap(({ label, mutation, before, after }) =>
      after === null ? [] : [{ label, mutation, before, after }],
    );
    // The first runs warm up the parser and the JIT.
    for (const { before, after } of timed)
      diffAutomationDocuments(before, after);
    const slow = timed
      .map(({ label, mutation, before, after }) => ({
        pair: `${label} / ${mutation}`,
        ms: medianMs(() => diffAutomationDocuments(before, after), 9),
      }))
      .filter(({ ms }) => ms >= BUDGET_MS);
    expect(slow).toEqual([]);
  });
});
