#!/usr/bin/env bun
/**
 * Vendor the Opengrep registry packs into a single pinned ruleset so the
 * blocking SAST gate is reproducible -- no scan-time registry fetch that could
 * drift and fail an unrelated PR. Re-run to refresh the snapshot:
 *
 *   bun tools/opengrep/vendor-rules.ts
 *
 * Output: tools/opengrep/rules/registry-pinned.yml (consumed by run.sh).
 * Only ERROR/WARNING rules are kept (the severities the gate enforces), deduped
 * by id across packs. The file is ASCII-only because the bundled opengrep
 * Python wrapper reads configs with the ascii codec and crashes on non-ASCII:
 * human fields (message/metadata) are transliterated to ASCII; the rare rule
 * whose *patterns* contain non-ASCII is dropped intact rather than corrupted.
 */
import { mkdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

import { parse, stringify } from 'yaml';

const PACKS = [
  'typescript',
  'react',
  'javascript',
  'nodejs',
  'jwt',
  'secrets',
  'gitleaks',
  'security-audit',
  'owasp-top-ten',
  'cwe-top-25',
  'xss',
  'sql-injection',
  'command-injection',
  'insecure-transport',
  'python',
  'fastapi',
  'dockerfile',
  'github-actions',
  'ci',
  'trailofbits',
];

const GATED_SEVERITIES = new Set(['ERROR', 'WARNING']);
const outFile = join(import.meta.dir, 'rules', 'registry-pinned.yml');

// Map common typographic code points to ASCII; drop any other non-ASCII byte.
// Numeric code points keep this source ASCII-only and unambiguous.
const ASCII_MAP = new Map<number, string>([
  [0x2018, "'"],
  [0x2019, "'"],
  [0x201a, "'"],
  [0x201b, "'"],
  [0x201c, '"'],
  [0x201d, '"'],
  [0x201e, '"'],
  [0x201f, '"'],
  [0x2013, '-'],
  [0x2014, '-'],
  [0x2015, '-'],
  [0x2026, '...'],
  [0x00a0, ' '],
]);

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === 'object' && value !== null;
}

function asciiClean(text: string): string {
  let out = '';
  for (const ch of text) {
    const code = ch.codePointAt(0) ?? 0;
    if (code < 0x80) {
      out += ch;
    } else {
      out += ASCII_MAP.get(code) ?? '';
    }
  }
  return out;
}

function hasNonAscii(text: string): boolean {
  for (const ch of text) {
    if ((ch.codePointAt(0) ?? 0) >= 0x80) return true;
  }
  return false;
}

// Transliterate strings ONLY in human-readable subtrees (message/metadata),
// never in pattern fields where a substitution could change matching.
function cleanHuman(value: unknown): unknown {
  if (typeof value === 'string') return asciiClean(value);
  if (Array.isArray(value)) return value.map(cleanHuman);
  if (isRecord(value)) {
    const out: Record<string, unknown> = {};
    for (const [k, v] of Object.entries(value)) out[k] = cleanHuman(v);
    return out;
  }
  return value;
}

const byId = new Map<string, Record<string, unknown>>();
let fetched = 0;
let dropped = 0;

for (const pack of PACKS) {
  const res = await fetch(`https://semgrep.dev/c/p/${pack}`, {
    headers: { Accept: 'application/yaml' },
  });
  if (!res.ok) {
    throw new Error(`pack p/${pack} fetch failed: ${res.status}`);
  }
  const doc: unknown = parse(await res.text());
  if (!isRecord(doc) || !Array.isArray(doc.rules)) {
    throw new Error(`pack p/${pack} has no rules array`);
  }
  for (const rule of doc.rules) {
    if (!isRecord(rule) || typeof rule.id !== 'string') continue;
    const severity = typeof rule.severity === 'string' ? rule.severity : '';
    if (!GATED_SEVERITIES.has(severity)) continue;
    if (byId.has(rule.id)) continue;

    if (typeof rule.message === 'string')
      rule.message = asciiClean(rule.message);
    if ('metadata' in rule) rule.metadata = cleanHuman(rule.metadata);

    // Any residual non-ASCII is in a pattern field — drop the rule whole rather
    // than alter what it matches.
    if (hasNonAscii(stringify({ rules: [rule] }))) {
      dropped++;
      continue;
    }
    byId.set(rule.id, rule);
  }
  fetched++;
}

const rules = [...byId.values()];
const stamp = new Date().toISOString().slice(0, 10);
const header = [
  '# GENERATED by tools/opengrep/vendor-rules.ts -- do not hand-edit.',
  `# Pinned snapshot of ${fetched} Opengrep registry packs (ERROR/WARNING rules`,
  '# only, deduped by id). Refresh with: bun tools/opengrep/vendor-rules.ts',
  `# Snapshot date: ${stamp} | rules: ${rules.length} | dropped (non-ASCII patterns): ${dropped}`,
  `# Packs: ${PACKS.map((p) => `p/${p}`).join(', ')}`,
  '',
  '',
].join('\n');

mkdirSync(join(import.meta.dir, 'rules'), { recursive: true });
writeFileSync(outFile, header + stringify({ rules }));

console.log(
  `vendored ${rules.length} rules from ${fetched} packs (${dropped} dropped for non-ASCII patterns) -> ${outFile}`,
);
