/**
 * Cross-harness adapter generator. A `.claude/skills/<name>/SKILL.md` is the
 * single source of truth for a coding-guide skill; other tools read generated
 * pointers to it:
 *
 *   - Cursor   -> .cursor/rules/<name>.mdc                     (every skill)
 *   - Codex    -> .codex/skills/<name>.md                      (every skill)
 *   - Copilot  -> .github/instructions/<name>.instructions.md  (glob-scoped skills only —
 *                 Copilot's `applyTo` needs a file glob, so activity-scoped skills get none)
 *
 * Globs come from `.claude/skill-globs.json` (`[]` = activity-scoped). The
 * non-skill `.cursor/rules/tale.mdc` (an always-on rule routing to AGENTS.md) is
 * hand-maintained and preserved untouched.
 *
 * This mirrors the skill-copy sync: deterministic render → byte-diff vs disk →
 * write/delete. The engine in sync.ts composes both.
 */

import { existsSync, readdirSync, readFileSync, rmSync } from 'node:fs';
import { join } from 'node:path';

import { diffTrees, type FileTree, type TreeDiff } from './tree';

/** Banner injected into every generated adapter so a reader edits the source, not the copy. */
const ADAPTER_COMMENT =
  '<!-- Generated by `bun run skills:sync` (tools/skills) from the skill SKILL.md + .claude/skill-globs.json — do not edit by hand. -->';

/**
 * Adapter files that are NOT generated from a skill and must be preserved.
 * `tale.mdc` is the always-on root rule (alwaysApply: true) routing to AGENTS.md.
 */
const ADAPTER_WHITELIST: ReadonlySet<string> = new Set([
  '.cursor/rules/tale.mdc',
]);

// --- frontmatter --------------------------------------------------------------

interface Frontmatter {
  readonly name: string;
  readonly description: string;
}

/** Parse the `name` + `description` from a SKILL.md's leading `--- … ---` block. */
function parseFrontmatter(md: string, skill: string): Frontmatter {
  if (!md.startsWith('---')) {
    throw new Error(
      `.claude/skills/${skill}/SKILL.md has no leading frontmatter`,
    );
  }
  const end = md.indexOf('\n---', 3);
  if (end === -1) {
    throw new Error(
      `.claude/skills/${skill}/SKILL.md frontmatter is not terminated`,
    );
  }
  let name = '';
  let description = '';
  for (const line of md.slice(3, end).split('\n')) {
    const match = /^([A-Za-z][\w-]*):\s?(.*)$/.exec(line);
    if (!match) continue;
    let value = match[2].trim();
    if (
      (value.startsWith("'") && value.endsWith("'")) ||
      (value.startsWith('"') && value.endsWith('"'))
    ) {
      value = value.slice(1, -1);
    }
    if (match[1] === 'name') name = value;
    else if (match[1] === 'description') description = value;
  }
  if (description === '') {
    throw new Error(
      `.claude/skills/${skill}/SKILL.md frontmatter has no description`,
    );
  }
  return { name, description };
}

/** The first sentence of a description — what Cursor/Copilot surface. */
function firstSentence(description: string): string {
  const idx = description.indexOf('. ');
  return idx === -1 ? description : description.slice(0, idx + 1);
}

// --- rendering ----------------------------------------------------------------

function renderCursorAdapter(
  name: string,
  description: string,
  globs: readonly string[],
): string {
  const lines = ['---', `description: ${firstSentence(description)}`];
  if (globs.length > 0) lines.push(`globs: ${globs.join(',')}`);
  lines.push(
    'alwaysApply: false',
    '---',
    '',
    `# ${name}`,
    '',
    ADAPTER_COMMENT,
    '',
  );
  lines.push(
    globs.length > 0
      ? `When working on matching code, read the [\`${name}\` skill](../../.claude/skills/${name}/SKILL.md) in full and follow it — it is the canonical guide. This file only routes Cursor to it.`
      : `When this guide applies (Cursor surfaces this rule by its description above), read the [\`${name}\` skill](../../.claude/skills/${name}/SKILL.md) in full and follow it — it is the canonical guide. This file only routes Cursor to it.`,
    '',
  );
  return lines.join('\n');
}

function renderCopilotAdapter(name: string, globs: readonly string[]): string {
  return [
    '---',
    `applyTo: '${globs.join(',')}'`,
    '---',
    '',
    ADAPTER_COMMENT,
    '',
    `When editing these files, read the [\`${name}\` skill](../../.claude/skills/${name}/SKILL.md) in full and follow it — it is the canonical guide. This file only routes Copilot to it.`,
    '',
  ].join('\n');
}

function renderCodexAdapter(name: string, description: string): string {
  return [
    `# ${name}`,
    '',
    ADAPTER_COMMENT,
    '',
    firstSentence(description),
    '',
    `Read the [\`${name}\` skill](../../.claude/skills/${name}/SKILL.md) in full and follow it — it is the canonical guide. This file only routes Codex to it.`,
    '',
  ].join('\n');
}

// --- discovery ----------------------------------------------------------------

function safeReaddir(dir: string): string[] {
  try {
    return readdirSync(dir);
  } catch (err) {
    if ((err as { code?: string }).code === 'ENOENT') return [];
    throw err;
  }
}

/** Names of every coding-guide skill under `.claude/skills/` (dirs with a SKILL.md). */
function discoverClaudeSkills(repoRoot: string): string[] {
  const dir = join(repoRoot, '.claude/skills');
  return safeReaddir(dir)
    .filter((name) => existsSync(join(dir, name, 'SKILL.md')))
    .sort();
}

/**
 * Load the globs source, or `null` when the file is absent. A `null` marks the
 * adapters as "not managed here" (e.g. a skill-copy unit-test fixture root) so
 * planAdapters no-ops rather than treating every committed adapter as stale.
 */
function loadSkillGlobs(repoRoot: string): Map<string, string[]> | null {
  const path = join(repoRoot, '.claude/skill-globs.json');
  if (!existsSync(path)) return null;
  const raw = JSON.parse(readFileSync(path, 'utf8')) as Record<
    string,
    string[]
  >;
  return new Map(Object.entries(raw));
}

// --- plan / apply -------------------------------------------------------------

/** The expected adapter tree (repo-relative path -> bytes) plus any source errors. */
export function expectedAdapterTree(
  repoRoot: string,
  globsByName: Map<string, string[]>,
): {
  tree: FileTree;
  errors: string[];
} {
  const skills = discoverClaudeSkills(repoRoot);
  const tree: FileTree = new Map();
  const errors: string[] = [];
  const enc = new TextEncoder();

  for (const name of skills) {
    const fm = parseFrontmatter(
      readFileSync(join(repoRoot, '.claude/skills', name, 'SKILL.md'), 'utf8'),
      name,
    );
    if (fm.name !== name) {
      errors.push(
        `.claude/skills/${name}/SKILL.md frontmatter name is "${fm.name}", expected "${name}"`,
      );
    }
    const globs = globsByName.get(name);
    if (globs === undefined) {
      errors.push(
        `skill "${name}" has no .claude/skill-globs.json entry (use [] for activity-scoped)`,
      );
      continue;
    }
    tree.set(
      `.cursor/rules/${name}.mdc`,
      enc.encode(renderCursorAdapter(name, fm.description, globs)),
    );
    tree.set(
      `.codex/skills/${name}.md`,
      enc.encode(renderCodexAdapter(name, fm.description)),
    );
    if (globs.length > 0) {
      tree.set(
        `.github/instructions/${name}.instructions.md`,
        enc.encode(renderCopilotAdapter(name, globs)),
      );
    }
  }

  for (const name of globsByName.keys()) {
    if (!skills.includes(name)) {
      errors.push(
        `.claude/skill-globs.json has entry "${name}" with no matching .claude/skills/${name}/`,
      );
    }
  }

  return { tree, errors };
}

/** Read the on-disk adapter files (excluding the hand-maintained whitelist). */
function readAdapterTree(repoRoot: string): FileTree {
  const tree: FileTree = new Map();
  const cursorDir = join(repoRoot, '.cursor/rules');
  for (const name of safeReaddir(cursorDir)) {
    if (!name.endsWith('.mdc')) continue;
    const rel = `.cursor/rules/${name}`;
    if (ADAPTER_WHITELIST.has(rel)) continue;
    tree.set(rel, readFileSync(join(cursorDir, name)));
  }
  const copilotDir = join(repoRoot, '.github/instructions');
  for (const name of safeReaddir(copilotDir)) {
    if (!name.endsWith('.instructions.md')) continue;
    tree.set(
      `.github/instructions/${name}`,
      readFileSync(join(copilotDir, name)),
    );
  }
  const codexDir = join(repoRoot, '.codex/skills');
  for (const name of safeReaddir(codexDir)) {
    if (!name.endsWith('.md')) continue;
    tree.set(`.codex/skills/${name}`, readFileSync(join(codexDir, name)));
  }
  return tree;
}

interface AdapterPlan {
  readonly expected: FileTree;
  readonly diff: TreeDiff;
  readonly errors: readonly string[];
}

/** Resolve the expected adapter set + its drift against disk. Pure read. */
export function planAdapters(repoRoot: string): AdapterPlan {
  const globsByName = loadSkillGlobs(repoRoot);
  if (globsByName === null) {
    // No adapter source committed -> adapters are unmanaged here (e.g. a
    // skill-copy unit-test fixture root). Nothing to generate, diff, or delete.
    const empty: FileTree = new Map();
    return { expected: empty, diff: diffTrees(empty, empty), errors: [] };
  }
  const { tree: expected, errors } = expectedAdapterTree(repoRoot, globsByName);
  return {
    expected,
    diff: diffTrees(expected, readAdapterTree(repoRoot)),
    errors,
  };
}

/** Write changed/missing adapters and delete stale ones. */
export async function applyAdapters(
  repoRoot: string,
  plan: AdapterPlan,
): Promise<void> {
  const writes: Promise<number>[] = [];
  for (const rel of [...plan.diff.missing, ...plan.diff.changed]) {
    const bytes = plan.expected.get(rel);
    if (bytes !== undefined) writes.push(Bun.write(join(repoRoot, rel), bytes));
  }
  for (const rel of plan.diff.extra) {
    rmSync(join(repoRoot, rel), { force: true });
  }
  await Promise.all(writes);
}
