// @vitest-environment node

/**
 * The analysis on every automation document the repository ships: the
 * packs under configs/platform/custom/automations, the worked example of
 * get_docs, the end-to-end probe pack and the complete documents of the
 * English docs.
 *
 *  1. none of them has an error — a new rule that refuses a shipped
 *     document is a regression, never a finding;
 *  2. their warnings (code, node, pointer) are exactly the reviewed list in
 *     corpus.snapshot.yml — every new warning on a shipped document is a
 *     reviewed diff;
 *  3. every node can run and the paths are enumerated;
 *  4. the flow model predicts real runs: each document's acceptance tests
 *     run in mock mode, the conditions and failures the trace shows are fed
 *     to `simulate`, and it must name exactly the nodes the run ran and
 *     skipped, with the trace's reasons.
 *
 * After an intentional change, regenerate the snapshot with:
 *
 *   CORPUS_UPDATE=1 bunx vitest --run --project server \
 *     lib/engine/core/analysis/corpus
 *
 * and review the diff. Follow-up: the blank-automation scaffold joins the
 * corpus once it lives in a module of its own.
 */

import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import { beforeAll, describe, expect, it } from 'vitest';
import { parse, parseDocument, stringify } from 'yaml';

import { loadConnectors } from '../../../connectors/registry';
import { isRecord } from '../../../utils/type-utils';
import { DOC_EXAMPLE } from '../../api/docs';
import { nodeVmRunner } from '../../runners/node-vm';
import { memoryStore } from '../../selftest/memory-store';
import { execute } from '../execute';
import { setCodeRunner } from '../runner';
import type { Automation, NodeTrace } from '../types';
import { validate } from '../validate';
import { flowModel, simulate, type SkipReason } from './flow';

const REPO = path.resolve(
  path.dirname(fileURLToPath(import.meta.url)),
  '../../../../../..',
);
const PLATFORM = path.join(REPO, 'services/platform');
const SNAPSHOT_PATH = fileURLToPath(
  new URL('corpus.snapshot.yml', import.meta.url),
);

const HEADER = `# The reviewed warnings of every automation document the repository ships —
# generated by corpus.test.ts, one entry per document. A shipped document
# never has an error.
#
# Never edit this file by hand: change the analysis or the document, review
# the diff, and regenerate with
#   CORPUS_UPDATE=1 bunx vitest --run --project server lib/engine/core/analysis/corpus
`;

function dirs(dir: string): string[] {
  return readdirSync(dir, { withFileTypes: true })
    .filter((e) => e.isDirectory())
    .map((e) => e.name)
    .sort();
}

function markdownFiles(dir: string): string[] {
  const out: string[] = [];
  for (const e of readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, e.name);
    if (e.isDirectory()) out.push(...markdownFiles(full));
    else if (e.name.endsWith('.md')) out.push(full);
  }
  return out.sort();
}

function asAutomation(v: unknown): Automation | null {
  if (!isRecord(v) || typeof v.name !== 'string' || !Array.isArray(v.nodes)) {
    return null;
  }
  // oxlint-disable-next-line typescript/no-unsafe-type-assertion -- a named document with nodes; validate() below judges every field
  return v as unknown as Automation;
}

function corpus(): Array<[string, Automation]> {
  const out: Array<[string, Automation]> = [];
  const packs = path.join(REPO, 'configs/platform/custom/automations');
  for (const provider of dirs(packs)) {
    for (const pack of dirs(path.join(packs, provider))) {
      const file = path.join(packs, provider, pack, 'workflow.yml');
      const doc = asAutomation(parse(readFileSync(file, 'utf8')));
      if (doc === null) throw new Error(`${file} is not a document`);
      out.push([`pack ${provider}/${pack}`, doc]);
    }
  }
  out.push(['get_docs example', DOC_EXAMPLE.automation]);

  // The end-to-end probe pack is a template literal in a Playwright spec,
  // which a unit test cannot import; it is read from the spec's text.
  const spec = readFileSync(
    path.join(PLATFORM, 'tests/e2e/specs/automations.spec.ts'),
    'utf8',
  );
  const slug = /const PROBE_SLUG = '([^']+)'/.exec(spec)?.[1];
  const probe = /const PROBE_WORKFLOW_YML = `([^`]*)`/.exec(spec)?.[1];
  if (slug === undefined || probe === undefined) {
    throw new Error('the e2e probe pack moved — update corpus.test.ts');
  }
  const probeDoc = asAutomation(parse(probe.replaceAll('${PROBE_SLUG}', slug)));
  if (probeDoc === null) throw new Error('the e2e probe is not a document');
  out.push(['e2e probe pack', probeDoc]);

  // Every complete document in the English docs (a named one with nodes;
  // fragments that show a single node are left out).
  for (const file of markdownFiles(path.join(REPO, 'docs/en'))) {
    const text = readFileSync(file, 'utf8');
    for (const m of text.matchAll(/```ya?ml\n([\s\S]*?)```/g)) {
      // A snippet that is not YAML on its own (an excerpt) is no document.
      const parsed = parseDocument(m[1]);
      if (parsed.errors.length > 0) continue;
      const value: unknown = parsed.toJS();
      const doc = asAutomation(value);
      if (doc !== null) {
        out.push([`docs ${path.relative(REPO, file)} ${doc.name}`, doc]);
      }
    }
  }
  return out;
}

const store = memoryStore();
const documents = corpus();

beforeAll(() => {
  setCodeRunner(nodeVmRunner());
  loadConnectors(path.join(REPO, 'configs/platform/system'));
  for (const [, doc] of documents) store.save(doc.name, doc);
});

interface Rendered {
  code: string;
  nodeId?: string;
  pointer?: string;
}

async function renderWarnings(): Promise<Record<string, Rendered[]>> {
  const out: Record<string, Rendered[]> = {};
  for (const [label, doc] of documents) {
    const { warnings } = await validate(doc, { store });
    out[label] = warnings.map((w) => {
      const rendered: Rendered = { code: w.code };
      if (w.nodeId !== undefined) rendered.nodeId = w.nodeId;
      if (w.at !== undefined) rendered.pointer = w.at.pointer;
      return rendered;
    });
  }
  return out;
}

describe('the shipped automation corpus', () => {
  it('holds every kind of shipped document', () => {
    const labels = documents.map(([label]) => label);
    expect(labels.filter((l) => l.startsWith('pack ')).length).toBe(10);
    expect(labels).toContain('get_docs example');
    expect(labels).toContain('e2e probe pack');
    expect(labels.some((l) => l.startsWith('docs '))).toBe(true);
  });

  it.each(documents)('%s: has no error', async (_, doc) => {
    const { errors } = await validate(doc, { store });
    expect(errors).toEqual([]);
  });

  it('warns exactly as reviewed', async () => {
    const actual = await renderWarnings();
    if (process.env.CORPUS_UPDATE === '1') {
      writeFileSync(
        SNAPSHOT_PATH,
        HEADER + stringify(actual, { lineWidth: 0, singleQuote: true }),
      );
      return;
    }
    const snapshot: unknown = parse(readFileSync(SNAPSHOT_PATH, 'utf8'));
    expect(actual).toEqual(snapshot);
  });

  it.each(documents)(
    '%s: every node can run and the paths are enumerated',
    async (_, doc) => {
      const { analysis } = await validate(doc, {
        store,
        detail: ['analysis'],
      });
      expect(analysis?.paths.truncated).toBe(false);
      const unreachable = Object.values(analysis?.nodes ?? {})
        .filter((n) => !n.reachable)
        .map((n) => n.id);
      expect(unreachable).toEqual([]);
    },
  );
});

/** What a trace entry says happened to its node. */
function traced(entry: NodeTrace): 'ran' | SkipReason | 'other' {
  if (entry.status === 'ok') return 'ran';
  if (entry.status === 'error') return 'error';
  if (entry.status !== 'skipped') return 'other';
  const note = entry.note ?? '';
  if (note.startsWith('skipped: when=')) return 'when';
  if (note.startsWith('skipped: elseOf')) return 'else';
  if (note.startsWith('skipped: reads from')) return 'upstream';
  return 'other';
}

describe('the flow model predicts the shipped tests', () => {
  const withTests = documents.filter(([, doc]) => (doc.tests ?? []).length > 0);

  it('has documents with tests to replay', () => {
    expect(withTests.length).toBeGreaterThan(3);
  });

  it.each(withTests)('%s', async (_, doc) => {
    const model = flowModel(doc.nodes);
    expect(model).not.toBeNull();
    if (model === null) return;
    let replayed = 0;
    for (const t of doc.tests ?? []) {
      const run = await execute(doc, { input: t.input, mode: 'mock', store });
      if (run.status !== 'success') continue;
      replayed++;
      const byId = new Map(run.trace.map((e) => [e.node, traced(e)]));
      const assignment: Record<string, boolean> = {};
      for (const atom of model.atoms) {
        if (atom.fixed === true) continue;
        const what = byId.get(atom.nodeId);
        if (atom.kind === 'when') {
          if (what === 'when') assignment[atom.id] = false;
          else if (what === 'ran' || what === 'error') {
            assignment[atom.id] = true;
          }
        } else if (what === 'ran' || what === 'error') {
          assignment[atom.id] = what === 'error';
        }
      }
      const predicted = simulate(model, assignment);
      const fromTrace = run.trace.map((e) => ({
        node: e.node,
        outcome: byId.get(e.node),
      }));
      const fromModel = model.nodes.map((n) => ({
        node: n.id,
        outcome: predicted.ran.includes(n.id)
          ? 'ran'
          : predicted.skipped.find((s) => s.nodeId === n.id)?.reason,
      }));
      expect({ test: t.name, outcomes: fromModel }).toEqual({
        test: t.name,
        outcomes: fromTrace,
      });
    }
    expect(replayed).toBeGreaterThan(0);
  });
});
